bootloader/common/stb.h
Error message:
../common/main.c: In function 'stb_decompress_fromfile':
../common/stb.h:10105:9: error: ignoring return value of 'fread',
declared with attribute
warn_unused_result [-Werror=unused-result]
../common/main.c: In function 'stb_fget_string':
../common/stb.h:5718:9: error: ignoring return value of 'fread',
declared with attribute
warn_unused_result [-Werror=unused-result]
cc1: all warnings being treated as errors
=> Fix bootloader compilation

PyInstaller/utils/hooks/hookutils.py
The fix for #1148 introduced a syntax error, this solves it
=> Fix syntax error (re #1148)

pyinstaller-gui.py
- python3 tkinter
- python3 command
=> Update pyinstaller-gui.py to support python3

PyInstaller/hooks/hook-_tkinter.py
For discussion, see issue #621
I've run it all through `flake8`, but let me know if there's any other formatting reqs.
=> Handle ActiveTcl installs on OS X. Fixes #621

PyInstaller/hooks/hook-pint.py
Pint: https://github.com/hgrecco/pint.
It uses some units dictionaries stored in .txt files, so we have to copy them over.
=> add hook for Pint

PyInstaller/build.py, PyInstaller/compat.py, PyInstaller/hooks/hook-PyQt5.py, PyInstaller/hooks/hook-distutils.py, PyInstaller/hooks/hook-sysconfig.py, PyInstaller/utils/hooks/hookutils.py
Looks right now, thanks for the guidance!
=> Python3 updates again

PyInstaller/hooks/hook-lensfunpy.py
=> Added hook file for lensfunpy

PyInstaller/hooks/hook-rawpy.py
Hook for [rawpy](https://github.com/neothemachine/rawpy).
=> Added rawpy hook

PyInstaller/loader/pyi_archive.py, PyInstaller/loader/pyi_carchive.py, bootloader/common/pyi_archive.c
This patch is use to fix issue #1145 
First time I want remove member fp and lib but that had to change many code.
So I took the simple solution.
Please run all tests before merge it,
on my system is the result is failures=6, errors=2, skipped=35 in 108 tests.
=> Fix file locking on windows #1145

PyInstaller/hooks/graph/hook-six.moves.py
[matysek](https://github.com/matysek) recently refactored relative to [absolute library imports](https://github.com/pyinstaller/pyinstaller/commit/c40c348d0e1e82582f08d63255805045a840e833). That's good. However, I *suspiciously* neglected to check whether the relative `modulegraph` import in the `six` graph hook had been refactored as well. It hadn't, so that's bad.
This commit fixes that in the trivial way. *"Eat hot lead, space invader!"* :space_invader:
=> "modulegraph" Import in "six" Graph Hook Fixed

PyInstaller/compat.py, PyInstaller/utils/misc.py, PyInstaller/utils/win32/winmanifest.py, bootloader/src/main.c, bootloader/src/pyi_archive.h, bootloader/src/pyi_global.c, bootloader/src/pyi_global.h, bootloader/src/pyi_launch.c, bootloader/src/pyi_pythonlib.c, tests/functional/conftest.py, tests/functional/scripts/pyi_path_encoding.py, tests/functional/test_basic.py
Find out if these tests fail on Appveyor. I know they fail on Travis and the next commits will pass them.
=> Add path encoding tests

PyInstaller/building/osx.py, PyInstaller/hooks/hook-enchant.py, PyInstaller/loader/rthooks.dat, PyInstaller/loader/rthooks/pyi_rth_enchant.py, PyInstaller/utils/hooks/hookutils.py, PyInstaller/utils/hooks/subproc/enchant_datafiles_finder.py
Only works with pyenchant installed with pip due to modifications made
to enchant by the pyenchant project.
=> Add hook and runtime hook for pyenchant on Mac OS X

PyInstaller/building/osx.py
Fix symlinks so they are relative to the current directory. Also
simplify symlinking code.
=> Fix and simplify symlinking in Mac OS X app bundle

tests/functional/scripts/pyi_get_datadir.py
This pull request allows correct invocation of test scripts from the Python interpreter.
=> Fix data dir

PyInstaller/archive/readers.py, PyInstaller/archive/writers.py, PyInstaller/building/api.py, PyInstaller/building/build_main.py, PyInstaller/building/templates.py, PyInstaller/building/toc_conversion.py, PyInstaller/depend/utils.py, PyInstaller/loader/pyimod02_archive.py, PyInstaller/loader/pyimod03_importers.py, tests/old_suite/import/test_eggs1.spec, tests/old_suite/import/test_eggs2.spec, tests/old_suite/import/test_pkgutil-get_data.py, tests/old_suite/import/test_pkgutil-get_data.spec, tests/old_suite/runtests.py
=> Enable including data-files from eggs

PyInstaller/building/build_main.py
Trivial change in an error message to tell the users what is actually missing on the system.
=> Show libpython filename in error message

PyInstaller/hooks/hook-osgeo.py, PyInstaller/loader/rthooks.dat, PyInstaller/loader/rthooks/pyi_rth_osgeo.py
This commit is based on: https://github.com/pyinstaller/pyinstaller/issues/1522
=> Add hook for osgeo [<2.0] libraries

PyInstaller/hooks/hook-PyQt5.QtWebEngineWidgets.py, PyInstaller/loader/rthooks.dat, PyInstaller/loader/rthooks/pyi_rth_qt5webengine.py
Fixes https://github.com/pyinstaller/pyinstaller/issues/1193
=> QWebEngineProcess osx dock icon fix

bootloader/wscript
1) Fix Solaris detect
2) Fix Solaris link with zlib
=> Some fixes for Solaris

PyInstaller/building/datastruct.py, PyInstaller/building/imphook.py, PyInstaller/building/imphookapi.py, PyInstaller/depend/analysis.py, PyInstaller/hooks/hook-_tkinter.py, PyInstaller/hooks/hook-enchant.checker.wxSpellCheckerDialog.py, PyInstaller/hooks/pre_find_module_path/hook-PyQt4.uic.port_v2.py, PyInstaller/hooks/pre_find_module_path/hook-PyQt4.uic.port_v3.py, PyInstaller/hooks/pre_find_module_path/hook-PyQt5.uic.port_v2.py, PyInstaller/hooks/pre_find_module_path/hook-PyQt5.uic.port_v3.py, PyInstaller/lib/modulegraph/modulegraph.py, tests/functional/modules/pyi_import_pyqt.uic.port/PyQt5/Qt.py, tests/functional/modules/pyi_import_pyqt.uic.port/PyQt5/QtCore.py, tests/functional/modules/pyi_import_pyqt.uic.port/PyQt5/__init__.py, tests/functional/modules/pyi_import_pyqt.uic.port/PyQt5/uic/__init__.py, tests/functional/modules/pyi_import_pyqt.uic.port/PyQt5/uic/port_v2/__init__.py, tests/functional/modules/pyi_import_pyqt.uic.port/PyQt5/uic/port_v2/test.py, tests/functional/modules/pyi_import_pyqt.uic.port/PyQt5/uic/port_v3/__init__.py, tests/functional/modules/pyi_import_pyqt.uic.port/PyQt5/uic/port_v3/test.py, tests/functional/scripts/pyi_import_pyqt5.uic.port.py, tests/functional/test_import.py
This closes #1557 and closes #1405.
=> Issue #1557 replace FakeModule by PostGraphAPI

PyInstaller/building/build_main.py, PyInstaller/depend/analysis.py, PyInstaller/depend/utils.py, tests/functional/test_import.py
=> Fixes and enhancements on scan_for_types

PyInstaller/hooks/hook-boto.py, PyInstaller/hooks/hook-boto3.py, PyInstaller/hooks/hook-botocore.py, PyInstaller/hooks/hook-gevent.monkey.py, PyInstaller/utils/tests.py, tests/functional/scripts/pyi_lib_boto.py, tests/functional/test_libraries.py, tests/requirements.txt
The docs on contributing new hooks seem to be slightly out of date, so I just tried to mimic how existing hooks (and tests for hooks) are written.
=> add hooks for botocore, boto3 and gevent

.travis.yml, appveyor.yml, tests/functional/test_libraries.py, tests/requirements.txt
Related to: https://github.com/pyinstaller/pyinstaller/pull/1614
Replace for PR: https://github.com/pyinstaller/pyinstaller/pull/1638
=> Add lxml.isoschematron test

PyInstaller/hooks/hook-distorm3.py, doc/CREDITS.rst
Hook to load the dll required by distorm3 (https://github.com/gdabah/distorm)
=> Distorm3 Hook

PyInstaller/hooks/hook-sklearn.metrics.cluster.py
Add data files for skimage and fix skimage.filters spelling.
Add hooks for sklearn.metrics.cluster.
Fixes #1732
=> Update hooks for skimage & sklearn.

PyInstaller/lib/modulegraph/modulegraph.py, tests/unit/test_modulegraph.py
Resolves https://github.com/pyinstaller/pyinstaller/issues/1750
=> Don't resolve symlinks in modulegraph.py

PyInstaller/hooks/hook-PyQt5.QtGui.py
Tis PR fixes the bug https://github.com/pyinstaller/pyinstaller/issues/1769
=> Add import of platformthemes on linux

PyInstaller/hooks/hook-pkg_resources.py, tests/functional/scripts/pyi_hooks/use_pkg_resources.py, tests/functional/test_hooks/test_pkg_resources.py
As requested here is the pull request to fix #1773.
=> Fix pkg resources

PyInstaller/hooks/hook-wx.lib.pubsub.py
Now passing in src to _match which was missed during last refactoring of this file
=> Fixed hook by adding src param to _match

PyInstaller/hooks/hook-cherrypy.py, tests/functional/test_libraries.py, tests/requirements.txt
Adds hook for CherryPy (http://www.cherrypy.org/).
=> Hook for CherryPy

bootloader/src/pyi_utils.c
this is some minor correction around previous bootloader win32 unicode issue which I missed.
=> fix pyi_open_target win32 unicode handling

doc/source/Manual.rst
=> Fix typo in manual

PyInstaller/hooks/hook-PyQt4.QtCore.py, PyInstaller/hooks/hook-PyQt4.QtGui.py, PyInstaller/hooks/hook-PyQt4.QtNetwork.py, PyInstaller/hooks/hook-PyQt4.QtScript.py, PyInstaller/hooks/hook-PyQt4.QtSql.py, PyInstaller/hooks/hook-PyQt4.phonon.py, PyInstaller/hooks/hook-PyQt4.py, PyInstaller/hooks/hook-PyQt5.QtCore.py, PyInstaller/hooks/hook-PyQt5.QtGui.py, PyInstaller/hooks/hook-PyQt5.QtMultimedia.py, PyInstaller/hooks/hook-PyQt5.QtNetwork.py, PyInstaller/hooks/hook-PyQt5.QtScript.py, PyInstaller/hooks/hook-PyQt5.QtSql.py, PyInstaller/hooks/hook-PyQt5.py, PyInstaller/hooks/hook-PySide.QtCore.py, PyInstaller/hooks/hook-PySide.QtGui.py, PyInstaller/hooks/hook-PySide.py, PyInstaller/hooks/hook-gi.repository.GdkPixbuf.py, PyInstaller/utils/hooks/__init__.py, tests/functional/modules/pyi_import_pyqt_uic_port/PyQt5/QtCore.py, tests/functional/scripts/pyi_helloworld.py
This should fix #1615, #1261, #1879, and #1884.
=> Cleanup and simplify PyQt/PySide code

tests/requirements-libraries.txt
sphinx_rtd_theme is an optional dependency of sphinx as of sphinx 1.4+.
=> Add sphinx_rtd_theme

PyInstaller/utils/win32/winmanifest.py
Changes needed:
1. Manifest was being written unconditionally to disk thus was always different
2. Manifest was written to TOC in an non de-serializable manner
3. Diff of manifests was not working
=> Winmanifest issues are causing unnecessary rebuilds

bootloader/src/pyi_launch.c
Just noticed this while debugging another issue and thought I'd fix it. Thank you for creating such a great tool!
=> Fix small typo in error message.

setup.py
=> add future to requirements in setup.py

PyInstaller/utils/hooks/qt.py
Cosmetic only patch, list all checked paths as comma separated values.
=> List all checked paths in qt dirs exceptions

PyInstaller/hooks/hook-django.py
Migration scripts of Django-based apps are now also included as data files.
=> Collect migrations of Django-based apps

appveyor.yml, tests/requirements-libraries.txt, tests/scripts/appveyor/run_with_env.cmd
See #2100. This gives me a chance to see AppVeyor output on the Pyinstaller account.
=> Appveyor fix

PyInstaller/compat.py, PyInstaller/depend/bindepend.py, bootloader/src/pyi_utils.c, bootloader/wscript
Add support for HPUX for python 2.7 and gcc compiler.
=> Changes on bootloader to support HPUX, with python 2.7 and gcc.

PyInstaller/hooks/hook-numpy.core.py
If numpy is built with MKL support it depends on a set of libraries loaded at runtime. Since PyInstaller's static analysis can't find them they must be included manually (fix #1881).
The current `hook-numpy.core.py` only searches for libraries in the numpy package folder. The anaconda distribution for example places them in Python/Libraries/bin, so both folders must be searched for support and in particular the MKL libraries.
This PR should also enable numpy+MKL support on Linux and OSX systems.
=> Modify numpy.core hook for supporting numpy MKL builds (fix #1881)

PyInstaller/hooks/hook-zeep.py, tests/functional/test_libraries.py, tests/requirements-libraries.txt
New pull request after attempted rebase of #2121 went badly astray.
=> Add hook for zeep for issue #2120

doc/runtime-information.rst
=> document how to invoke system programs

PyInstaller/building/utils.py
=> Fix hasher digest bytes not str

bootloader/src/pyi_utils.c
=> Bootloader: fix segfault, fixes #2176

PyInstaller/hooks/hook-skimage.transform.py
Pull request to address issue #2195
=> Added skimage._shared.transform to the skimage transform hook.  

README.rst
=> README: Remove download statistics.

PyInstaller/hooks/hook-mpl_toolkits.basemap.py
added additional places to check for auxiliary data (conda specific)
=> Hooks: mpl_toolkits.basemap: Add conda specific places to check for auxiliary data.

PyInstaller/hooks/hook-pylint.py, PyInstaller/hooks/hook-setuptools.py
Fixes pylint test with pylint>=1.7
=> Hooks: Add setuptools.msvc hidden import

README.rst
Fix python version description in README
=> Small Update README.rst

PyInstaller/hooks/hook-sphinx.py
sphinx.parsers is a hidden import from sphinx 1.6.2+
=> Add Sphinx 1.6.2+ hidden import

PyInstaller/hooks/hook-gi.repository.GstAudio.py, PyInstaller/hooks/hook-gi.repository.GstBase.py, PyInstaller/hooks/hook-gi.repository.GstPbutils.py, PyInstaller/hooks/hook-gi.repository.GstTag.py, PyInstaller/hooks/hook-gi.repository.GstVideo.py, PyInstaller/hooks/pre_safe_import_module/hook-gi.repository.GstAudio.py, PyInstaller/hooks/pre_safe_import_module/hook-gi.repository.GstBase.py, PyInstaller/hooks/pre_safe_import_module/hook-gi.repository.GstPbutils.py, PyInstaller/hooks/pre_safe_import_module/hook-gi.repository.GstTag.py, PyInstaller/hooks/pre_safe_import_module/hook-gi.repository.GstVideo.py
=> Hooks: GStreamer: add additional gstreamer typelibs

bootloader/src/pyi_utils.c
if the program is actived by a systemd socket, then there are some
envs(LISTEN_PID, LISTEN_FDS) for it.
LISTEN_PID is set to the pid which is forked by systemd that is the
parent process of the bootloader.
This patch is trying to correct the env to the child pid of bootloader.
parent fds are duplicated to child process, so it's OK to modify
LISTEN_PID.
I test it with gunicorn which [supports](http://docs.gunicorn.org/en/stable/deploy.html#systemd) systemd socket.
Some [related code](https://github.com/benoitc/gunicorn/blob/c54426c1e4b26b30c5feee2cec4450656ae147a3/gunicorn/systemd.py#L36-L39) in gunicorn which detects the LISTEN_PID env.
=> bootloader: set proper LISTEN_PID in child process

PyInstaller/hooks/hook-libaudioverse.py
Hopefully this all works. I've tried to run it with Python 2 and 3 with no luck (because pyinstaller as a whole is acting odd on this machine), but I can't see any problem with it. If it's not I know what to do to fix it.
=> Added a hook for the Libaudioverse module.

PyInstaller/hooks/hook-PyQt5.QtWebEngineWidgets.py, PyInstaller/hooks/hook-PyQt5.QtWebKit.py, PyInstaller/hooks/hook-PyQt5.py, PyInstaller/loader/rthooks.dat, PyInstaller/utils/hooks/__init__.py, PyInstaller/utils/hooks/qt.py, tests/functional/test_libraries.py
Since no one took this up, let's see how much work this is going to be...
=> Hooks: Qt WebEngine

doc/contributing.rst, doc/usage.rst
=> Doc: Add infos about bundling the "Universal C Run-time".

PyInstaller/building/build_main.py, PyInstaller/lib/modulegraph/modulegraph.py, doc/when-things-go-wrong.rst
=> Always write modulegraph xref-html

README.rst
Update system requirements to reflect Python 3.6 compatibility.
=> Update README for consistency re: Python 3.6 support

PyInstaller/hooks/hook-accessible_output2.py, PyInstaller/hooks/hook-libaudioverse.py, PyInstaller/hooks/hook-sound_lib.py
Fixed the capitalisation of PyInstaller.
=> Fixed names.

PyInstaller/compat.py, appveyor.yml, tests/functional/conftest.py, tests/requirements-tools.txt
As usual, the commits are absolutely horrible, but I will clean them up eventually. Feel free to force push to this branch and clean them up if you have time.
=> Enable parallel testing on windows and update psutil

doc/usage.rst
=> Doc: Add docs for running PyInstaller with Python optimizations

PyInstaller/depend/utils.py
this sets the timestamp in base_library.zip
=> Make base_library.zip reproducible: Set date of files.

PyInstaller/hooks/hook-cytoolz.itertoolz.py, PyInstaller/hooks/hook-eth_abi.py, PyInstaller/hooks/hook-eth_utils.py, PyInstaller/hooks/hook-web3.py, tests/functional/test_libraries.py, tests/requirements-libraries.txt
=> Hooks: Add hooks for web3 and its dependencies

PyInstaller/compat.py
=> Fix and simplifying find for python library on windows, msys2 and cygwin

PyInstaller/hooks/hook-flex.py
Add hook for flex package.
https://github.com/pipermerriam/flex
=> Add flex hook

PyInstaller/compat.py, tests/functional/conftest.py, tests/functional/test_basic.py
=> Make test_option_w_ignore verify 'warnings' get imported

.dockerignore, tests/scripts/Dockerfile, tests/scripts/test-docker.sh
Just a little something I found useful while working on PyInstaller
from a mac; this lets me easily run the tests on Linux.
=> Tests: add script for running tests in docker

PyInstaller/hooks/hook-phonenumbers.py, tests/functional/test_libraries.py, tests/requirements-libraries.txt
=> Hooks: Add hook for phonenumbers.

doc/hooks.rst
=> [misc] spelling/syntax error

PyInstaller/hooks/hook-dynaconf.py
Hi,
I used PyInstaller to freeze an application which needed [dynaconf](https://github.com/rochacbruno/dynaconf). I have written a basic hook for that and I am proposing to add it to PyInstaller.
=> Adds support for dynaconf.

PyInstaller/hooks/hook-torch.py
this hook allows bundling of torch. The whole dir is required.
=> adding pytorch hook

PyInstaller/hooks/hook-resampy.py, PyInstaller/news/3702.hooks.rst
Great library 👍 
Resampy is a dependency of librosa, a popular audio-analysis library. It has two data files that need to be brought along. (See: https://github.com/bmcfee/resampy/tree/master/resampy/data )
=> Add resampy hook

doc/CHANGES.rst, doc/_dummy-roles.txt, doc/_extensions/pyi_sphinx_roles.py, news/_template.rst, setup.py
This produces a more useful `changes.rst` IMHO.
=> doc: Insert hyperlinks to issues referenced by towncrier.

bootloader/src/pyi_utils.c, news/3722.bootloader.rst, news/3723.bootloader.rst
=> * fixed invocation of setenv when HAVE_UNSETENV is not defined

PyInstaller/compat.py
=> Remove instructions to install pypiwin32.

PyInstaller/building/utils.py, news/3662.bugfix.rst
=> Fix #3309: Changing from -F to -D on consecutive runs causes crash 

PyInstaller/hooks/hook-gooey.py, PyInstaller/news/3773.hooks.rst
just a simple one
gooey carry some language json and images for it's UI to function.
=> Hooks: add gooey hook

bootloader/zlib/README, bootloader/zlib/adler32.c, bootloader/zlib/crc32.c, bootloader/zlib/gzguts.h, bootloader/zlib/inffast.c, bootloader/zlib/inflate.c, bootloader/zlib/inflate.h, bootloader/zlib/inftrees.c, bootloader/zlib/zconf.h, bootloader/zlib/zlib.h, bootloader/zlib/zutil.c, bootloader/zlib/zutil.h, news/3742.bootloader.rst
=> bootloader: Update bundled zlib library to version 1.2.11.

PyInstaller/hooks/hook-wavefile.py, news/3785.hooks.rst
hi,
this is the hook for python-wavefile which is available at https://github.com/vokimon/python-wavefile
=> hooks: added a hook for python-wavefile

PyInstaller/hooks/hook-nanite.py, news/3860.hooks.rst
Please add this hook for nanite: Loading, fitting, and rating AFM force-indentation data
https://nanite.readthedocs.io
=> hooks: add nanite hook

doc/when-things-go-wrong.rst
Following #3870, added some documentation for "operation not permitted" error.
=> Document operation not permitted

doc/development/documention.rst
Changed "you" to "your" on line 25
=> Doc: Fix small typo in documentation.rst

doc/_common_definitions.txt
$ curl -I http://upx.sourceforge.net/
HTTP/1.1 301 Moved Permanently
Location: https://upx.github.io/
=> upx moved to github

PyInstaller/hooks/hook-notebook.py, news/3950.hooks.rst
Hook to collect data files and hiddenimports from notebook.
=> Add hook for notebook.

PyInstaller/hooks/hook-nbformat.py, news/3946.hooks.rst
Hook to collect data files from nbformat
=> Add hook for nbformat

PyInstaller/hooks/hook-nbconvert.py, news/3947.hooks.rst
Hook to collect data files and metadata from nbconvert
=> Add hook for nbconvert.

PyInstaller/building/api.py, news/1729.bugfix.rst, news/3746.bugfix.rst
It seems to work and fix #1729.
=> Add manifest embedding when --onefile

PyInstaller/building/api.py, PyInstaller/building/osx.py, PyInstaller/utils/win32/icon.py, news/3333.feature.rst, news/3444.feature.rst
The code changes are I believe complete for this issue. There are problems with the manual, but I don't want to put doc changes into this pull request. After it is accepted I will open a new issue specifically to better document these various command parameters and their related spec file values.
=> relative paths for icon and version in spec file #3333

PyInstaller/hooks/hook-pywt.py, news/4120.hooks.rst
Create a hook for [pywt](https://pywavelets.readthedocs.io/en/latest/) library
=> Add pywt hook

PyInstaller/hooks/hook-migrate.py, news/4250.hooks.rst
Hook file for the sqlalchemy-migrate package:
https://github.com/openstack/sqlalchemy-migrate
=> Hooks: Create hook-migrate.py.

PyInstaller/hooks/hook-magic.py, news/4267.hooks.rst
hook for python-magic and python-magic-bin
=> hooks: add magic hook

PyInstaller/hooks/hook-astropy.py, news/4274.hooks.rst
The hook required for the [astropy package](https://github.com/astropy/astropy) is non-trivial, so I thought it would make sense to include here (I am one of the astropy developers).
=> Add a new hook for astropy package

PyInstaller/building/utils.py
Inform to the user NO is the default (i.e. If you press enter)
=> Inform default to user

PyInstaller/hooks/hook-BTrees.py, PyInstaller/hooks/hook-textdistance.py, news/4239.hooks.1.rst, news/4239.hooks.2.rst
Hook file for the BTrees package: https://pypi.org/project/BTrees/
Hook file for the textdistance package: https://pypi.org/project/textdistance/
=> Hooks: Create hook-BTrees.py,hook-textdistance.py

PyInstaller/hooks/hook-gi.repository.GtkSource.py, PyInstaller/hooks/pre_safe_import_module/hook-gi.repository.GtkSource.py, news/3893.hooks.rst
Add a hook for GtkSource (https://wiki.gnome.org/Projects/GtkSourceView). Fixes #3855.
=> Add hook for GtkSource.

doc/_common_definitions.txt
Issue: the current url results in a GitLab 404 error.
Fix: Update the url.
=> Docs: Fix Graphviz url

.github/CONTRIBUTING.md
working on saving some clicks - one at a time.
=> use direct link to "Read The Docs" in GitHub's contribution guidelines

PyInstaller/hooks/hook-google.cloud.speech.py, news/3888.hooks.rst
I would like to add a hook for the google cloud speech api.
=> Hooks: add hook for google cloud speech

PyInstaller/hooks/hook-google.cloud.pubsub_v1.py, news/4446.hooks.rst
Add a hook file for Google's PubSub library
=> Add hook file for google.cloud.pubsub

PyInstaller/hooks/hook-avro.py, news/4388.hooks.rst
=> add avro hook

PyInstaller/compat.py, PyInstaller/depend/bindepend.py, PyInstaller/depend/utils.py, README.rst, bootloader/wscript, doc/hooks.rst, doc/index.rst, doc/man/pyinstaller.rst, doc/requirements.rst, news/4545.build.rst
This will allow the installation and usage of PyInstaller on OpenBSD system.
=> openbsd support

PyInstaller/hooks/hook-text_unidecode.py, news/4327.hook.rst, news/4530.hooks.rst
Fixes: #4327
Adds hook for text_unidecode package which depends on a data.bin file
=> feat: Adds text_unidecode hook

PyInstaller/depend/imphook.py, news/4626.hooks.rst
Closes #4626 
Related to #4538 
Supercedes #4684
=> Add assertion message to assert statement in ModuleHook

PyInstaller/hooks/hook-bcrypt.py, news/4735.hooks.rst
=> hooks: Add bcrypt hook.

tests/requirements-libraries.txt
=> Monthly dependency update

PyInstaller/hooks/hook-jaraco.text.py, news/4576.hooks.rst, news/4632.hooks.rst
simple new hook for jaraco.txt to fix #4576
=> Issue pyinstaller#4576: Add hook for jaraco.text

PyInstaller/hooks/hook-lightgbm.py, news/4634.hooks.rst
Tested on Windows 10 & macOS 10.14 with Python 3.7.5
fix https://github.com/pyinstaller/pyinstaller/issues/4155 & https://github.com/pyinstaller/pyinstaller/issues/3863
=> Hook LightGBM

PyInstaller/configure.py
upx version with git
3.96-git-d7ba31cab8ce
=> parse upx, if it is a git version

bootloader/src/pyi_pythonlib.c, news/4728.bugfix.rst, news/4734.bugfix.rst
Initialize variable len before using it - so test for DLLNAME buffer size succeds when a .so file is used on AIX.
Closes #4728
=> initialize variable len before using it

.gitignore, PyInstaller/depend/analysis.py, PyInstaller/depend/imphook.py, news/4876.feature.rst, tests/unit/hook_order_hooks/pyi_example_package/__init__.py, tests/unit/hook_order_hooks/pyi_example_package/hook-pyi_example_package.py, tests/unit/hook_order_hooks/pyi_example_package/rthooks.dat, tests/unit/hook_order_hooks/pyi_example_package/rthooks/pyi_rth_naughty.py, tests/unit/hook_order_hooks/rthooks.dat, tests/unit/hook_order_hooks/rthooks/pyi_rth_good.py, tests/unit/hook_order_hooks/setup.py, tests/unit/test_additionalfilescache.py, tests/unit/test_hook_order.py, tests/unit/test_pyimodulegraph.py
This PR changes hook priority to:
1. Hooks from the command line.
2. Hooks from packages using the `pyinstaller40` entry point.
3. Hooks from PyInstaller itself.
Closes #4806 Closes #1835
=> Feature/Hooks: Allow user provided hooks to override built-in hooks

.github/workflows/main.yml, .travis.yml, tests/requirements-tools.txt
=> CI: add a new GitHub action for running lint

news/5214.tests.rst, setup.cfg, tests/requirements-tools.txt
=> Test/CI: Treat all tests as flaky by default.

PyInstaller/building/osx.py, news/4337.build.rst
=> build: OSX: Use high resolution mode by default for GUI applications

PyInstaller/__main__.py, PyInstaller/_recursion_to_deep_message.py, news/4406.core.rst, news/5156.core.rst, tests/unit/test_recursion_limit.py
=> main: Add informative message what do to if RecurrsionError occurs.

PyInstaller/depend/imphook.py, news/5277.bugfix.rst
Edit logging to remove dulpicate messages.
=> Remove duplicate logging messages.

PyInstaller/utils/conftest.py, PyInstaller/utils/tests.py, news/1427.tests.rst, setup.cfg, tests/functional/test_apple_events.py, tests/functional/test_basic.py, tests/functional/test_import.py, tests/functional/test_libraries.py, tests/functional/test_path_encodings.py, tests/functional/test_signals.py, tests/functional/test_updating_manifest.py, tests/unit/test_TOC.py, tests/unit/test_depend_utils.py, tests/unit/test_modulegraph_more.py
=> tests: replace skipif_xxx for platform-specific tests by markers

PyInstaller/compat.py, bootloader/wscript, news/5296.bugfix.rst
Signed-off-by: Petrus.Z <silencly07@gmail.com>
=> fixed sw_64 architecture supported

.github/workflows/macos.yml, .travis.yml, PyInstaller/compat.py, README.rst, appveyor.yml, doc/hooks.rst, news/5289.feature.rst, setup.cfg, tests/requirements-libraries.txt, tox.ini
=> Feature: Add Python 3.9 support.

.travis.yml, tests/functional/data/appimage/AppIcon.svg, tests/functional/data/appimage/DirIcon.png, tests/functional/data/appimage/create.sh, tests/functional/data/appimage/org.pyinstaller.appimage.test.appdata.xml, tests/functional/data/appimage/org.pyinstaller.appimage.test.desktop, tests/functional/test_linux_appimage.py
Part of #4693.
So the test cannot pass right now, of course, but it works. It will hopefully be very usefull at preventing regressions (and I pray that it will attract people to fix the current errors :).
=> Tests: Add an AppImage test

PyInstaller/depend/bindepend.py, bootloader/src/pyi_path.c, bootloader/wscript
https://github.com/pyinstaller/pyinstaller/pull/3930#issue-238898175
=> Fix build fail on cygwin.

PyInstaller/hooks/hook-sqlalchemy.py, news/5679.hooks.rst
Rebasing #5675 on top of this should in theory fix its CI errors.
=> Hooks: sqlachemy: Fix compatibility with 1.4.

.github/workflows/ci.yml, setup.cfg, tests/requirements-libraries.txt
I observed that the CI hung. This may fix it.
=> tests/ci: add global timeout for tests

.github/workflows/ci.yml, tests/functional/test_django.py, tests/requirements-tools.txt
This may cut down on the flakiness.
=> tests/ci: rerun failures

.github/ISSUE_TEMPLATE/bug_report.md
Scope of changes is restricted to docs only. Change is in agreement with Standard American English.
=> fix(docs): corrects typo in project ISSUE_TEMPLATE

PyInstaller/compat.py
This code is observed to lead to the timeout, which requires the node to be crashed. If patched, pytest can rerun the test without having to start a new node.
=> compat: implement timeouts on subprocess

PyInstaller/building/datastruct.py
Typo fix in docs: tytecode => typecode
=> Typo fix in docs: tytecode => typecode

bootloader/src/pyi_pythonlib.c
Use `PyMarshal_ReadObjectFromString()` instead of invoking python `loads` function via `PyObject_CallFunction()`.
=> bootloader: simplify code object unmarshalling for bootstrap modules

PyInstaller/building/api.py, PyInstaller/building/osx.py, PyInstaller/building/utils.py, PyInstaller/depend/analysis.py, news/5851.bugfix.rst, tests/unit/test_building_utils.py
=> Fix collection of duplicated extensions with mangled filenames

PyInstaller/building/api.py, PyInstaller/utils/win32/winmanifest.py, news/5921.bugfix.rst
Fixes https://github.com/pyinstaller/pyinstaller/issues/2239
=> Fix exe being rebuilt every time on windows

PyInstaller/building/makespec.py, doc/spec-files.rst, doc/when-things-go-wrong.rst
Hi there, I would love a review to get some thoughts on this PR and maybe some word-smithing. This addresses #5961.
=> docs: clarify where `--paths` option updates in spec file

PyInstaller/compat.py, news/6029.bugfix.rst
Fixes #6027 Darwin architecture detection problem using the method suggested by @bwoodsend.
Tested against the exemple in the issue.
=> Fix for #6027

PyInstaller/building/build_main.py, news/6080.bugfix.rst
=> Fix hookloader function bug when whitespaces in path
