setup.py

Change the requirement from distribute to setuptools, 
as was fixed for #791 on the develop branch ( 0ea8f92ac63468551135dffa67853cb12563bc6e ),
but not for the python3 branch

Issue #791 on python3 branch: distribute to setuptools

---

PyInstaller/hooks/hook-distutils.py
PyInstaller/hooks/hook-sysconfig.py

When running PyInstaller from within a pep405 venv,
the sysconfig hook calculates the wrong relative path
(causing a SecurityAlert). The point is that in these
new venvs, the `include` dir is not copied or symlinked,
and the `pyconfig.h` path is relative to `sys.base_prefix`
(new since Python3.2). Outside a venv nothing changes.
https://www.python.org/dev/peps/pep-0405/

PY3: sysconfig hook: support pep405 style venv

---

PyInstaller/hooks/hook-_tkinter.py

change the "code" string in case of python3 using "is_py3" from PyInstaller.compat

Update hook-_tkinter.py to support python3 tkinter

---

pyinstaller-gui.py

Tkinter filedialog in python2 is a different import
sys.executable for whichever python version is beeing used running the gui

Update pyinstaller-gui.py for python 2 and 3

---

PyInstaller/build.py

Absolute paths won't work on anyone else's system.

Use relative symlinks when moving data files out of `MacOS` folder.

---

PyInstaller/loader/pyi_importers.py

A few more erroneous `print()` statements are now commented out. Thus dies issue #1196.

Debug output squelched, fixing #1196.

---

PyInstaller/build.py

This method was fundamentally broken when passed a directory rather than glob or file. Specifically, directory walking accumulated invalid directories via the local `dest_dir` variable. This corrects that, thereby also correcting issue #1190 and hence matplotlib integration.
To support these changes, this method has been lightly refactored. Single-and double-letter variable names have been renamed for human-readability, multi-line comments and docstrings have been added, and various subtle errors in the original have been amended.
~~In particular, the original implementation assumed that existing paths which do *not* satisfy `os.path.isfile(pathname)` must be directories. This was an erroneous assumption: since `os.path.isfile(pathname)` returns False for *all* most special files (e.g., …

Analysis._format_hook_datas() fixed for #1190.

---

PyInstaller/utils/hooks/hookutils.py

The utility function `opengl_arrays_modules()` called `exec_statement()` in a fundamentally broken manner, thereby breaking the `hook-OpenGL.py` hook. This fixes that, as well as adding a **TODO** comment suggesting that function be moved directly into that hook. (It's not called anywhere else. Time to put down stray dogs, I reckon.)
See #1210 for curmudgeonly details.

opengl_arrays_modules() fixed, fixing #1210.

---

PyInstaller/hooks/hook-zmq.py

When `hook-zmq.py` was modified to also find libsodium, the wrong syntax was used for `glob.glob` which does not accept the `{foo,bar}` syntax (see [`fnmatch.fnmatch`](https://docs.python.org/2/library/fnmatch.html)). This change allows libzmq.pyd to be found correctly.

Fix zmq not being found in hook-zmq.py

---

PyInstaller/build.py
PyInstaller/depend/analysis.py
PyInstaller/hooks/hook-_tkinter.py
PyInstaller/loader/rthooks/pyi_rth__tkinter.py

This pull request properly bundles Tcl/Tk data files with frozen executables importing `tkinter`, completing [prior work](https://github.com/pyinstaller/pyinstaller/pull/1174) by [matysek](https://github.com/matysek) and others. It does *not* fix  #1164. It merely ensures that when we *do* fix #1164, everything will work as expected. Which seems nice.
~~This pull request now fixes  #1164. Don't ask how, as you *really* don't want to know. (See the conversation at #1164 for details. Take it from me, though: it's bad. **Real bad.**)~~
**EDIT:** The fanatically awesome [codewarrior0](https://github.com/codewarrior0) appears to have [independently solved #1164](https://github.com/codewarrior0/pyinstaller/commit/a52e1a7ab006c0628b86bca615a68f693d8ca0a4). This pull request together with that …

Tcl/Tk data file bundling fixed.

---

PyInstaller/hooks/hook-matplotlib.backends.py
PyInstaller/utils/hooks/hookutils.py

This minor pull request:
* Adds metadata logging to the existing `matplotlib.backends` hook, improving both debugging and usability.
* Fixes several significant bugs in this hook.
* Documents and refactors this hook for readability.
The `matplotlib.backends` hook is arguably the slowest hook in the PyInstaller repository. Users importing `matplotlib` can expect to become familiar with the following output:
...
21733 INFO: Processing hook   hook-docutils.py
25967 INFO: Processing hook   hook-pygments.styles.py
25974 INFO: Processing hook   hook-pygments.lexers.py
27290 INFO: Processing hook   hook-IPython.py
27293 INFO: Processing hook   hook-matplotlib.backends.py
At which point, PyInstaller silently hangs for ten to twenty seconds before silently proceeding onward. As [user experience …

"hook-matplotlib.backends" Output Improved

---

bootloader/wscript

the gcc has no '-m64' option under sw64 machine. And, the __x86__64__ macro need add by hand.

fix bootloader compile bug under 'sw_64' machine.

---

PyInstaller/hooks/hook-appy.pod.py
PyInstaller/hooks/hook-appy.py

The package needs a couple of xml files that aren't added without a hook, this way code seems to execute correctly.
I'm not sure if this would be the correct way to do it, please feel free to adapt it as you wish.
appy: https://pypi.python.org/pypi/appy/0.9.1

Add hook for appy package

---

PyInstaller/utils/winmanifest.py

This commit adds a compatibility section to the manifest file created for windows exe's, particularly important when --onefile is used.
Without this, I always get a window popup after my program is exited stating:
“This program might not have installed correctly”
with the buttons to:
"Reinstall using recommended settings"
"This program installed correctly"
I believe this is triggered because my application copies files onto C: presumably causing windows to detect it as an installer.
At this stage I don't know for certain if there would be any unintended side-effects from having this compatibility section in all applications, however I don't expect it would cause any problems.
Original information on the topic came from:
http://stackoverflow.com/questions/898220/how-to-prevent-this-program- …

Avoid “This program might not have installed correctly” on Windows

---

PyInstaller/build.py

Some shared libraries on Windows are packaged as **Assemblies**, which can either be **Shared** or **Private**. Shared assemblies can only be loaded from system-wide locations under the Windows folder. In order to package a shared assembly into a PyInstaller app, the assembly must be transformed into a private assembly. Since the shared/private status of an assembly *forms part of its identity*, all files which depend on this assembly must also be altered.
This patch applies the needed changes to the packaged assemblies and all of their dependents as part of the build process. This patch also fixes a bug where a `onefile` app cannot launch because it depends on the very files it is going to extract.
Executable files that use shared libraries ("DLLs") must have a way of identifying which …

Correct linkage information for Windows Side-by-Side Shared Assemblies

---

PyInstaller/build.py

in class TOC, make append method to normalize path when object typecode is "BINARY" or "DATA" instead of just "BINARY"

Fixes multiples pyconfig.h warns with --onefile option

---

PyInstaller/build.py

For various reasons, a single file can get included multiple times in the built app. When duplicate files are excluded using the filesystem name, the file will not appear in all of the locations requested by the spec file and/or hooks. 
This was causing a certain lib (`libzmq.pyd`, I think) to be randomly (depending on dict ordering or something) included in the "wrong" location. Some module is looking for that lib in one of the requested locations, and when the lib appears in a different internal location, a vague sounding ImportError results. Seemingly unrelated changes that would result in differing TOC lists, such as adding extra imports, would change the location the lib ends up being in and would apparently fix the problem, but the real issue is that `PKG.assemble()` is only …

Skip duplicate binaries using the internal name, not the filesystem name

---

PyInstaller/__init__.py
PyInstaller/depend/analysis.py
PyInstaller/hooks/hook-pythoncom.py
PyInstaller/hooks/hook-pywintypes.py
PyInstaller/utils/hooks/hookutils.py
PyInstaller/utils/win32/winutils.py

This pull request substantially improves PyInstaller integration with [Anaconda](http://continuum.io/downloads) under Windows, fixing #1247. The solution is fairly simple. We define two new utility functions:
* `import_pywin32_module()`, importing the passed PyWin32 module (e.g, `pywintypes`, `pythoncom`) in an Anaconda-aware manner. Attempting to import this module directly results in an exception resembling `"ImportError: No system module 'pywintypes' (pywintypes34.dll)"`. Why? Because Anaconda installs the referenced DLL into the `site-packages\pywin32_system32\` and `site-packages\win32\` directories, which PyWin32 does *not* search when attempting to find the DLL. (**Insanity.** We know.) This function instructs PyWin32 to search the first directory with a dollop of [vile black …

PyWin32 Anaconda Support

---

PyInstaller/build.py

I made the patch on python2 not knowing that file() was removed in python3. Now I know to use open() everywhere from now on.

Change file() to open() in updating manifests

---

PyInstaller/build.py

Allows simultaneous building on different CPU types. A great addition to simultaneous building on different python versions.

Use a different bincache for each processor architecture

---

PyInstaller/hooks/hook-PyQt5.py
PyInstaller/utils/win32/winresource.py

Fixes:
ImportError: No module named 'PyInstaller.utils.winutils'
TypeError: 'str' does not support the buffer interface
During building of EXE
Fixes:
ImportError: No module named 'PyQt5.Qt'
During startup of newly built EXE with Qt where Pyinstaller missed to include PyQt5.Qt

Python3 - PyQt5, winutils, winresource

---

bootloader/common/pyi_pythonlib.c

This is the same change as #1217, backported to the develop branch.
[Py_SetProgramName](https://docs.python.org/2.7/c-api/init.html#c.Py_SetProgramName) requires that its argument be a pointer to "a string in static storage". Moving the string buffer to a statically allocated global fulfills this requirement. SetProgramName simply stores the pointer it is given and does not copy the string contents, nor does it ever attempt to free the memory pointed to.
This fixes problems with modules using the result of Py_GetProgramName for various things, [such as _tkinter described here.](https://github.com/pyinstaller/pyinstaller/issues/1164#issuecomment-82262657)

Pass static-allocated memory to Py_SetProgramName (backported)

---

bootloader/src/pyi_pythonlib.c

[Py_SetProgramName](https://docs.python.org/3.4/c-api/init.html#c.Py_SetProgramName) requires that its argument be a pointer to "a string in static storage". Moving the string buffer to a statically allocated global fulfills this requirement. SetProgramName simply stores the pointer it is given and does not copy the string contents, nor does it ever attempt to free the memory pointed to.
This fixes problems with modules using the result of Py_GetProgramName for various things, [such as _tkinter described here.](https://github.com/pyinstaller/pyinstaller/issues/1164#issuecomment-82262657)

Pass static-allocated memory to Py_SetProgramName

---

bootloader/wscript

Modifications are valid if you use msvc (tested with MS VS 2010 Expre…ss and MS Win SDK v7.1) / Linux and OSX untested
- Restructured configure to correctly identify msvc compiler
- Added configure option --target-cpu=[x86, amd64] to manually choose build architecture
- Commented out strip tool, as it isn't working and necessary on windows

Corrections and modifications to wscript to correctly build bootloader on Windows

---

bootloader/common/pyi_launch.c

The bootloader would not compile because `langinfo.h` and `nl_langinfo()` are not available on win32. This patch moves the related code into `#ifndef WIN32` blocks.
StackOverflow suggests the equivalent Win32 API function is `GetLangInfoEx()`

Fix bootloader to compile on win32 again.

---

PyInstaller/__init__.py
doc/source/Manual.rst
doc/source/pyi-build.rst
doc/source/pyi-make_comserver.rst
doc/source/pyi-makespec.rst

When building multiple branches of my project simultaneously, PyInstaller simultaneously tries to modify the same files. By specifying different config directories, I can avoid this problem.

Allow customising CONFIGDIR

---

tests/setupenv_windows.py

Fix: Missing ispy27.
Provide a default tempdir, so that the --download_dir isn't required.
Before these fixes:
```
C:\Users\bjones\Documents\pyinstaller-git\tests>python setupenv_windows.py
File "setupenv_windows.py", line 99, in <module>
'twisted': is_py27,  # wheels are avalable for 2.7 only
NameError: name 'is_py27' is not defined
```
and
```
C:\Users\bjones\Documents\pyinstaller-git\tests>python setupenv_windows.py
Already installed... markdown
Installing module... pyusb
pyusb
Searching for pyusb
Reading https://pypi.python.org/simple/pyusb/
Best match: pyusb 1.0.0b2
Downloading https://pypi.python.org/packages/source/p/pyusb/pyusb-1.0.0b2.tar.gz#md5=bc12e83ff3ef104
5d4306d13a9955fc1
Processing pyusb-1.0.0b2.tar.gz
Writing …
```

Correct syntax errors in setup_windows.py for testing.

---

PyInstaller/build.py
bootloader/common/main.c
bootloader/common/pyi_launch.c
bootloader/common/pyi_launch.h

As discussed in issue #1078 , this pull requests fixes the problem with the missing menu at startup on OSX. I tested the code OSX Mountain Lion, Maverick and Yosemite.
For discussion please see issue #1078 !
More information about this issue is here:
http://dvitonis.net/blog/2015/01/07/menu-bar-not-visible-when-building-pyqt-app-bundle-pyinstaller-mac-osx-mavericks-yosemite/

Fix for Menu not displayed with app bundle on OSX

---

bootloader/src/pyi_pythonlib.c

Out of sheer curiosity (as I don't develop for Python 3), I checked out the `python3` branch to try the new py.test suite on Windows. I found that several tests fail in a way that displays the Windows Error Reporting dialog, which stalls the test suite until it is dismissed.
(Incidentally, the test failures may be related to running the suite from within a virtualenv, which gets some-path-or-another wrong causing `create_py3_base_library` to fail, saying `py.test.exe\\__main__.py not found`...but that's a separate issue.)
The dialog is caused by Py_Initialize. Py_Initialize when failing calls `abort()` to terminate the entire application. (This is very rude, especially for embedded pythons.) `abort()` on Windows triggers the Windows Error Reporting Dialog, which will pause the test suite …

Suppress Windows Error Reporting dialogs while calling Py_Initialize

---

tests/basic/expected_stdxxx_encoding.py
tests/basic/test_stderr_encoding.py
tests/basic/test_stdout_encoding.py

This updates https://github.com/pyinstaller/pyinstaller/pull/1243#issuecomment-116799566, in which the Windows encoding was left as a fixme.
The underlying problem -- the bootloader doesn't select the correct stdout/stderr encoding on Windows -- isn't resolved, but at least this pull requests makes the test correct.

Fix: Provide correct encoding for Windows based on querying chcp.

---

PyInstaller/depend/utils.py
PyInstaller/lib/modulegraph/modulegraph.py
tests/functional/conftest.py

Preface: I've only tested these on 32-bit Python 3.4 for Windows.
These three changes (well, two of them at least) allow the py.test suite to run on Windows.
The original error reads: `Fatal Python error: Py_Initialize: unable to load the file system codec` when running the .exe created by any test. Reading the output log reveals `ERROR: base_library.zip could not be created!`, so the first change makes this error fatal so we can see why it fails.
This reveals the error in `create_py3_base_library`:
```
>                       st = os.stat(mod.filename)
FileNotFoundError: [WinError 3] The system cannot find the path specified: '(...)\\pyinst1328\\env34\\Scripts\\py.test.exe\\__main__.py'
```
This is caused by modulegraph trying to analyze the `__main__` module, so the second change is a …

A few fixes to get py.test working on Windows

---

PyInstaller/build.py

```
File "C:\Python34\lib\runpy.py", line 170, in _run_module_as_main
"__main__", mod_spec)
File "C:\Python34\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\Python34\Scripts\pyinstaller.exe\__main__.py", line 9, in <module>
File "C:\Python34\lib\site-packages\PyInstaller\main.py", line 96, in run
run_build(opts, spec_file, pyi_config)
File "C:\Python34\lib\site-packages\PyInstaller\main.py", line 49, in run_build
PyInstaller.build.main(pyi_config, spec_file, **opts.__dict__)
File "C:\Python34\lib\site-packages\PyInstaller\build.py", line 2168, in main
build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
File "C:\Python34\lib\site-packages\PyInstaller\build.py", line 2114, in build
exec(text, …
```

fix NameError: name 'CONF' is not defined

---

PyInstaller/hooks/hook-speech_recognition.py

`speech_recognition` comes bundled with FLAC encoding binaries, which need to be bundled with PyInstaller in order for the library to work properly.

Add hook for `speech_recognition`.

---

PyInstaller/compat.py
PyInstaller/hooks/hook-logilab.py
PyInstaller/hooks/hook-pygments.formatters.py
PyInstaller/hooks/hook-pylint.py
tests/libraries/test_pygments.py

These commit fix two failing tests (libraries/test_pylint and libraries/test_pygments). Details:
* Add a logilab hook to add the hidden configparser import (dynamically imported by six)
* Add an extra import in test_pygments to make the test pass.

Hook fixes

---

PyInstaller/loader/rthooks/pyi_rth_qt5plugins.py

This fixes an issue where, at least on Windows, trying to use a PyQt5 module results in an ImportError at runtime.
Without this patch, a module using python-qt5 exits with the following error:
```
File "<string>", line 36, in <module>
File "C:\Python27\Lib\site-packages\PyInstaller\loader\pyi_importers.py", line
420, in load_module
fp = open(filename, 'rb')
ImportError: No module named sip
LOADER: RC: -1 from pyi_rth_qt5plugins
```
When I looked at the built binary, it looks like the module is just getting named `PyQt5.sip`. The python-qt5 package expects the name `sip`. This small patch is sufficient to fix the problem, but if you would prefer a different approach, please let me know.

Make PyQt5.sip available as sip at runtime

---

PyInstaller/loader/pyi_importers.py

When frozen, a module that dynamically recreates itself at runtime (by replacing itself in sys.modules) doesn't seem to interact well with the loader.
The main symptom of this problem is something like this:
```python
>>> sys.modules[<dynamic_module>] is __import__(<dynamic_module>)
False
```
The fix seems just to be to make sure to re-read the module from sys.modules before returning it from load_module

Reread from sys.modules before returning module

---

tests/libraries/test_pygments.py

Pygments modifies sys.modules, which needed a work-around for Pyinstaller until now.

Fix: Remove unneeded imports now that PR #1352 is merged.

---

PyInstaller/depend/bindepend.py
PyInstaller/hooks/hook-sphinx.py
PyInstaller/hooks/hook-sqlalchemy.py
PyInstaller/utils/hooks/hookutils.py

This pull request adds a utility function for safely comparing module versions and then refactors import hooks requiring such comparisons to call this function.
The SQLAlchemy hook checks whether the currently installed module is version 0.6 or newer like so:
```
version = exec_statement('import sqlalchemy; print(sqlalchemy.__version__)')
is_alch06 = version >= '0.6'
```
This is me doing my disgusted face. :disappointed: 
**Version specifiers are _not_ reliably comparable as strings.** Since string comparison is lexicographic rather than numeric, comparing version specifiers as strings results in erroneous results in common edge cases: e.g.,
```
>>> '0.7' >= '0.6'
True
>>> ' 0.7' >= '0.6'
False
>>> '0.5' >= '0.6'
False
>>> '00.5' >= '0.6'
True
```
Version specifiers should _always_ be …

Robust Module Version Comparisons

---

bootloader/src/pyi_archive.c

No longer needed as LC_CTYPE is set since main.
Potential fix for #1378

Remove redundant call to setlocale in pyi_arch_cache_argv

---

PyInstaller/hooks/hook-PyQt5.py

This fixes pyinstaller/pyinstaller#1332
Let me know if there is anywhere I could add a test case.
Question: Do I need to add a dependency on `pkg_resources`/`setuptools` or is it safe to say that `setuptools` will be installed?

PyQt5: Made OS X `qt_menu.nib` requirement conditional on Qt version

---

pyinstaller-gui.py

[self.fout = '']  is not actually used in the script
added [self.filein.delete(0, 'end')] because otherwise if you would choose another file, it would just append it to self.filein

Small changes for clarity

---

pyinstaller-gui.py

import ttk (overwrites widgets from tkinter) to make the application look more native on windows and osx (nothing really changes on linux)
Without ttk
With ttk

Make pyinstaller-gui look more native

---

tests/functional/test_libraries.py

This updates #1356 for the python3 branch. It skips the USB test if no backend is present.

Add: Skip USB tests if no backend is available.

---

PyInstaller/depend/dylib.py
PyInstaller/depend/utils.py

Loading a different version of the libc cause a segfault at runtime.
A simple test case is:
````python
import ctypes
ctypes.CDLL("libc.so.6")
````
building this on debian wheezy (glibc 2.13) and running it on debian jessie (glibc 2.19) was causing a segfault.
If found the issue with the "watchdog" package which use inotify on linux and have this piece of code.
As a workaround we can use this sample code in the spec file:
````python
a = Analysis(...)
for e in a.binaries[:]:
if e[0] in ("libc.so", "libc.so.6"):
a.binaries.remove(e)
[...]
````

Fix: don't bundle excluded libraries

---

PyInstaller/hooks/hook-weasyprint.py

Add the needed html5_ua.css datafile.
Note I don't know the weasyprint package very well, but at least this file is required for generating a pdf in the simple use case.

Add a hook for weasyprint

---

PyInstaller/compat.py

it did not find the libpython because it searched for the wrong filename.

fix PYDYLIB_NAMES for FreeBSD 10.2 64bit

---

PyInstaller/building/build_main.py

Original message was not correct from the following 2 points:
1. Python library may not be found on platforms other than Debian GNU/Linux
2. Debian's `python-dev` package doesn't contain `libpythonN.M.so`
(`libpythonN.M.so` is a content of `libpythonN.M` package)
This should fix #1505

Modify error message on missing Python shared library

---

PyInstaller/hooks/hook-mpl_toolkits.basemap.py

This hook avoid to use a solution similar to what is described here: http://stackoverflow.com/questions/17749296/get-pyinstaller-to-import-basemap

Add hook for `mpl_toolkits.basemap` auxiliary data

---

PyInstaller/hooks/hook-netCDF4.py

The added hidden imports are also described here: https://github.com/poidl/slidenc
This should help to fix this type of SO issues: http://stackoverflow.com/questions/29067588/problems-building-python-distribion-containing-netcdf4

Add hook for netCDF4 due to hidden imports

---

PyInstaller/hooks/hook-osgeo.py

Minor fix to osgeo to make the row platform-independent (as pointed out at: https://github.com/pyinstaller/pyinstaller/pull/1528)

Minor fix to osgeo hook

---

PyInstaller/compat.py

I tried to build a binary with python 3.5 and it did not find the
python dynlib again. Seems to have another extension now.

fix PYDYLIB_NAMES for FreeBSD 10.2 64bit, try 2

---

PyInstaller/hooks/hook-django.py

Try to fix import issue for "HTMLParser" and "Cookie" when using Django, due to differences between Python 2 and 3.
It is an explicit solution: in the future could be replaced by a better management of six library (#1231?)

Fix import of cookies and htmlparser on Python 2.x used by Django.

---

PyInstaller/hooks/hook-django.py
PyInstaller/hooks/hook-django.template.loaders.py
PyInstaller/utils/hooks/subproc/django_import_finder.py

In Django-based projects all relevant modules of installed apps should now be collected by PyInstaller.

Fix django imports

---

PyInstaller/lib/modulegraph/modulegraph.py

This reduces the number of recursion levels in modulegraph when importing. Instead of processing the import immediately when found by the AST-visitor, the imports *per module* are collected and processed after visiting the AST.
So with this approach, the recursion looks like this:
_import_module
_load_module
_scan_code
_process_import
_safe_import_hook
import_hook
_find_head_package
_import_module (loop)
Whereas before, the recursion could look like this:
_import_module
_load_module
_scan_code
_scan_ast
Visitor.visit
Visitor.generic_visit
Visitor.visit
Visitor.generic_visit
-- [plus *any number* of Visitor method calls] --
Visitor.visit_Import / Visitor.visit_ImportFrom
_process_import
_safe_import_hook
import_hook
_find_head_package
_import_module (loop)
So we are saving approx. 5 …

Issue #1289 maximum recursion exeeded

---

PyInstaller/building/utils.py

Some libraries on FreeBSD have immunable flag (libthr.so.3, for example)
If flags still remains, os.chmod will failed with:
OSError: [Errno 1] Operation not permitted.add comment

Flush special flags with os.chflags() on cache files

---

PyInstaller/hooks/hook-sphinx.py
PyInstaller/hooks/pre_safe_import_module/hook-six.moves.py

This pull request fixes a **critical defect** in the `six.moves` module, and should probably be merged in time for the **PyInstaller 3.0** milestone.
Previously, our `six.moves` pre-safe import module hook mapped "moved modules" (i.e., modules marked as moved by `six.moves`) but _not_ "moved attributes" (i.e., module attributes marked as moved by `six.moves`). Any attempt to import a moved attribute therefore currently fails.
This is unspeakably bad.
Commit 0df9267 fixes this by mapping both moved modules _and_ attributes. Thankfully, it was trivial. (No applause, please.)
Commit 37270f6 demonstrates this defect by removing all `six.moves`-specific hidden imports from the Sphinx hook. Previously, all `six.moves` imports required by Sphinx were previously listed as hidden – but only under …

`six.moves` Hook Fixed for the Good of (Wo)Mankind

---

PyInstaller/hooks/hook-PyQt4.uic.py
tests/functional/test_libraries.py

I'm not sure how this got deleted...but it's certainly needed. The hook-PyQt5.uic.py file was also deleted; I would assume it's also important, but don't have PyQt5 expertise to check.

Fix: Restore PyQt4 uic hook, which makes the PyQt4 uic test pass.

---

tests/functional/test_libraries.py

This is an updated, cleaner version of 9f8e9ae16be34ff523a26dd08559c7bff9fcab5a. See also https://github.com/pyinstaller/pyinstaller/pull/1355.

Fix: Skip scapy tests if its dependences aren't installed.

---

PyInstaller/utils/hooks/__init__.py
tests/functional/conftest.py
tests/functional/modules/pyi_collect_submodules_mod.py
tests/functional/scripts/pyi_collect_submodules.py
tests/functional/scripts/pyi_hooks/hook-pyi_collect_submodules_mod.py
tests/functional/test_basic.py

I've run into a problem in which `PyInstaller.utils.hooks.collect_submodules` fails, since its call to `is_package` returns False. Apparently, this happens because `sys.path` does not include the path given in the `pathex` .spec-file argument.
The (probably wrong) fix: ignore a False return value from `is_package`.
The tests included pass in py.test without the fix...but fail from the command line, meaning the py.test environment doesn't quite duplicate the actual execution environment. See `pyi_collect_submodules.py` for an explanation of the somewhat convoluted working on the test itself.
Ideas?

Fix collect submodules

---

PyInstaller/hooks/hook-lxml.isoschematron.py

This should solve this issue: https://github.com/pyinstaller/pyinstaller/issues/1613

Add hook for auxiliary data required by lxml.isoschematron

---

PyInstaller/hooks/hook-weasyprint.py

Forgotten part of commit 2a853f6eeadcc8ffbe95468bfc9b7223d3e32cd0

Rename PyInstaller.utils.hooks.hookutils into PyInstaller.utils.hooks.

---

PyInstaller/hooks/hook-scipy.linalg.py

The current development branch fails to works with `scipy.linalg` in  Scipy 0.16 as `scipy.linalg.cython_blas` and   `scipy.linalg.cython_lapack` modules are not included. This was discussed at length in issue #1430 and was supposed to be fixed then, but I still experience this problem with the current development branch.
This PR adds a hook for `scipy.linalg`  as mentioned by @matysek in issue #1430 .  I checked that this fixes the issue for PY2, PY3 on Linux and PY3 on Windows using conda with scipy-0.16. Also checked that this does not break anything with scipy-0.15 (PY3, conda, Windows)  which does not include those cython modules.  
This PR is also related to the issue #1465 (although apparently adding this hook did not solve the problem for @Csega ). 
**Edit**: test …

Adding a scipy.linalg hook for Scipy 0.16+

---

bootloader/wscript

Setting MSVC_MANIFEST before ctx.load has no effect as it is overwritten in "find_msvc". This fixes "Runtime error R6034" when compiling the bootloader using "Visual C++ 9.0 Compiler for Python 2.7".

Don't embed manifest file in bootloader

---

PyInstaller/depend/bindepend.py
PyInstaller/lib/README.rst
PyInstaller/lib/pefile_py2.py
PyInstaller/lib/pefile_py3.py
appveyor.yml
tests/speed/speed_pefile.py

Addresses issue #1484
With these changes, pefile.py will skip parsing those parts of the imports and exports tables that we don't care about. This cuts about 10 minutes off of the test suite run times for each Python version, and has a larger impact for builds that include a lot of compiled extensions (e.g. PySide).

pefile.py optimization

---

PyInstaller/lib/modulegraph/modulegraph.py
appveyor.yml

This adds a modest optimization, removing an extra `compile()` call from `ModuleGraph._scan_code()` and its callers. This also removes the timeout from the pytest invocation, allowing tests to run to completion. This should show us that all tests pass if allowed to run to completion.
Previous changes added a list of the 10 longest-running tests to the output, the longest of which is usually `test_pandas_extension[onefile]` at 300+ seconds. A more generous timeout may be added later if desired.
The longest-running tests are generally `matplotlib`, `django`, `pandas`, `sqlalchemy`, `sphinx`, and `ipython` (which optionally imports matplotlib and could probably exclude it.). Initial profiling on `matplotlib` showed that most of the time is spent creating the modulegraph (~55%) and running …

Remove redundant compile() calls

---

PyInstaller/depend/dylib.py

Sometimes os.path.realpath decides to change the case of the path

Issue #1665: don't include Windows system DLLs

---

PyInstaller/building/api.py

See the beginning of the story at #1664
I've got an exception on Windows 7 on both `master` and `develop` branches when building Enki with [this spec](https://github.com/hlamer/enki/blob/master/win/enki-all.spec) and [this script](https://github.com/hlamer/enki/blob/master/win/build_exe.bat).
The exception
```
68640 INFO: Found binding redirects:
[BindingRedirect(name=u'Microsoft.VC90.MFC', language=None, arch=u'x86', oldVers
ion=(9, 0, 21022, 8), newVersion=(9, 0, 30729, 6161), publicKeyToken=u'1fc8b3b9a
1e18e3b'), BindingRedirect(name=u'Microsoft.VC90.CRT', language=None, arch=u'x86
', oldVersion=(9, 0, 21022, 8), newVersion=(9, 0, 30729, 6161), publicKeyToken=u
'1fc8b3b9a1e18e3b')]
68640 INFO: Warnings written to C:\github\enki\build\enki-all\warnenki-all.txt
Traceback (most recent …
```

Fix: exception on Windows when calculating common prefix

---

PyInstaller/depend/analysis.py

When ``Analysis`` has ``hookspath=["path/to/hooks"]``, and ``path/to/hooks`` has a ``pre_find_module_path`` folder (or a ``pre_safe_import_module`` folder), during analysis, there are a bunch of errors like this:
```
1158 ERROR: Hook directory '<os.getcwd()>/p' not found
1158 ERROR: Hook directory '<os.getcwd()>/a' not found
1158 ERROR: Hook directory '<os.getcwd()>/t' not found
1158 ERROR: Hook directory '<os.getcwd()>/h' not found
1159 ERROR: Hook directory '<os.getcwd()>/t' not found
1159 ERROR: Hook directory '<os.getcwd()>/o' not found
1159 ERROR: Hook directory '<os.getcwd()>/h' not found
1159 ERROR: Hook directory '<os.getcwd()>/o' not found
1159 ERROR: Hook directory '<os.getcwd()>/o' not found
1159 ERROR: Hook directory '<os.getcwd()>/k' not found
1159 ERROR: Hook directory …
```

Fix iteration bug with user-defined hook directories

---

bootloader/wscript

When used with GCC (4.9.2 in this case), C99 with GNU extension is required.

Compiling bootloader on Solaris 11

---

PyInstaller/hooks/hook-astroid.py
PyInstaller/hooks/hook-logilab.py
PyInstaller/utils/hooks/__init__.py
tests/functional/test_libraries.py

This fix makes pylint (and its tests) work.

Fix: Provide missing hidden imports for astroid v. 1.4.1.

---

PyInstaller/hooks/hook-sphinx.py
PyInstaller/hooks/hook-wx.lib.pubsub.py

Fix: Actually include autosetuppubsubv1.py.
The existing hook docs state that it should be included...but it wasn't. Now it is. This applies to wxPython v 2.8.

Wx pubsub fix

---

PyInstaller/depend/bindepend.py
PyInstaller/hooks/hook-gi.repository.GLib.py
PyInstaller/hooks/hook-gi.repository.Gio.py
PyInstaller/hooks/hook-gi.repository.Gst.py
PyInstaller/hooks/hook-gi.repository.Gtk.py
PyInstaller/hooks/hook-gi.repository.PangoCairo.py
PyInstaller/hooks/hook-gi.repository.cairo.py
PyInstaller/hooks/pre_safe_import_module/hook-gi.repository.PangoCairo.py
PyInstaller/hooks/pre_safe_import_module/hook-gi.repository.cairo.py
PyInstaller/utils/hooks/__init__.py

- Older PyGObject Gdk doesn't declare cairo as a dependency
- Add cairo/pangocairo repositories
- Include all system data directories when collecting glib data files

More PyGObject fixes

---

tests/unit/test_modulegraph.py

This makes more unit tests pass in Windows.

Fix: Join pathnames in an OS-independent manner.

---

doc/source/Manual.rst

Using this
```
pip install -e git://github.com/pyinstaller/pyinstaller.git#egg=PyInstaller
```
installs PyInstaller from master, which is confusing since the latest development happens on the develop branch.
(For some reason, GitHub introduced some superfluous changes to the diff. I'll try to get rid of those.)

For development version, install from develop branch

---

PyInstaller/loader/rthooks/pyi_rth_django.py

that was caused by rewritten django.core.management.get_commands function
runserver command from django.contrib.staticfiles application does not
work for the 'django.exe runserver 0.0.0.0:80' command line

fixed No module named management.commands.runserver (issue #1721)

---

PyInstaller/hooks/hook-PyQt5.py
PyInstaller/hooks/hook-sphinx.py
PyInstaller/hooks/hook-sqlalchemy.py
PyInstaller/utils/hooks/__init__.py

This pull request completes my [previously incomplete pull request](https://github.com/pyinstaller/pyinstaller/pull/1373).
Like that request, this request refactors the `is_module_version()` hook helper to behave more sensibly. Unlike that request, this request provides additional support for validating whether a module satisfies multiple constraints – including both versions _and_ extras (i.e., optional install-time features). Hence, this helper has been renamed to `is_module_satisfies()`.
Unrelatedly, the docstring for the `get_pywin32_module_file_attribute()` hook helper was a confusing lie. That's been fixed, too.
As consensus (rightfully) demanded, the `is_module_satisfies()` helper now accepts three parameters:
1. A mandatory `setuptools`-formatted requirements string (e.g., …

Robust Module Version Comparisons ~ Redux Redux

---

PyInstaller/loader/rthooks.dat

This is required to make pyinstaller include the gstreamer rthook when kivy uses gstreamer.
Hopefully not too late for 3.1 :)

Detect gst usage in kivy.

---

tests/functional/modules/pyi_testmod_path/__init__.py
tests/functional/modules/pyi_testmod_path/a/b.py
tests/functional/modules/pyi_testmod_path/b.py
tests/functional/scripts/pyi_hooks/hook-pyi_testmod_path.py
tests/functional/test_hooks/test_wx_lib_pubsub.py
tests/functional/test_import.py

This shows a corner case not (yet) correctly handled by PyInstaller: `__path__` is not respected when imports come from the filesystem. For this reason, some of the wxPython tests are also marked as xfail. See #1704.

Wx python fail

---

tests/requirements.txt

when the boto hook was added, boto not added to
test/requirements.txt, causing the boto tests to be skipped by CI

add boto as a test requirement

---

MANIFEST.in

The full MANIFEST.in syntax is [here](https://docs.python.org/3/distutils/commandref.html#creating-a-source-distribution-the-sdist-command).

Simplify MANIFEST.in commands

---

PyInstaller/hooks/hook-lib2to3.py

A hook for lib2to3, used by networkx library for their GML language ( https://github.com/networkx/networkx/blob/master/networkx/readwrite/gml.py )

Lib2to3 hook

---

PyInstaller/__init__.py
PyInstaller/archive/readers.py
PyInstaller/building/api.py
bootloader/src/pyi_archive.c
tests/functional/test_basic.py

Use objcopy to create a valid ELF file. This stops prelink stripping off the archive. 
https://github.com/pyinstaller/pyinstaller/issues/1812

Use objcopy to create a vaild ELF file

---

PyInstaller/building/utils.py

On OS X, if the binary cache is in NFS, the chflags call fails (presumably because NFS doesn't support that operation)
See https://github.com/pyinstaller/pyinstaller/pull/1573#issuecomment-158563618

Don't exit if chflags fails

---

PyInstaller/hooks/hook-cryptography.py

Related discussion: https://bitbucket.org/cffi/cffi/issues/247/listing-hidden-imports-when-freezing-a
Fixes #1425.

Add missing hidden import for Cryptography: _cffi_backend

---

bootloader/src/pyi_win32_utils.c

first few is just some cosmetic change that can be ignore,
the point is e5cd9cb
I found that malloc the wrong size which result in random 
> Failed to get ANSI buffer size error
as the screenshot shows although the mainpath passed in is nothing related to multibyte, it's been effect by the buffer overflow cause false result
to trigger this require longer CJK in path that will overflow a lot to make something broken,
here is some report probably related
https://github.com/docker/compose/issues/2779
http://stackoverflow.com/questions/34449674/exe-file-produced-by-pyinstaller-cannot-be-used-in-others-pc

fix: buffer overflow under win32 wchar multibyte string convert

---

PyInstaller/hooks/hook-PyQt5.QtPrintSupport.py
PyInstaller/utils/hooks/__init__.py
tests/functional/conftest.py
tests/functional/test_libraries.py
tests/requirements-mac.txt
tests/requirements.txt

Needed for pyinstaller/pyinstaller-osx-tests#1:
- Add a requirements-mac.txt for pip
- Cleanup requirements.txt
- Delete temporary directory of tests that pass (to minimize space used on test machines)
- Skip QtWebKit dependent tests on Qt 5.6+
- Add an extra location for qt_menu.nib check
Add QtPrintSupport hook
Remove unnecessary Mac OS X specific xfails

General Mac OS X tests fixups and Qt fixes

---

PyInstaller/building/build_main.py
PyInstaller/building/imphook.py
PyInstaller/building/imphookapi.py
PyInstaller/building/utils.py
PyInstaller/compat.py
PyInstaller/configure.py
PyInstaller/hooks/pre_find_module_path/hook-site.py
PyInstaller/utils/tests.py
bootloader/wscript
tests/functional/test_hooks/test_pil.py

Greetings again, earthbound meat suits.
Welcome to this first of three pull requests implementing [codewarrior0](https://github.com/codewarrior0)'s lazy hook loading scheme. I call it "The Lazy Hook Trilogy." You may call it "really, really pretentious."
In this first pull request, we:
* Define a new `PyInstaller.building.imphook.ModuleHook` class encapsulating a lazy loadable hook.
* Define a new `PyInstaller.building.imphook.ModuleHookCache` class caching all lazy loadable hooks.
* Refactor the `PyInstaller.building.build_main.Analysis.assemble()` method to leverage these new classes.
Let's shamble to it, shall we?
Six months ago, [tallforasmurf](http://github.com/tallforasmurf) noted my solution of isolating different hook functions to different hook scripts in different hook …

Lazy Hook I: A Not Really New Hope

---

PyInstaller/compat.py
PyInstaller/hooks/hook-gi.repository.GdkPixbuf.py
PyInstaller/utils/tests.py
tests/functional/test_hooks/test_gi.py
tests/functional/test_hooks/test_matplotlib.py
tests/functional/test_libraries.py

Greetings and wintry salutations, PyInstaller goodfellows.
This pull request generalizes [wailinygn](https://github.com/wailinygn)'s [open pull request](https://github.com/pyinstaller/pyinstaller/pull/1819) for the `hook-gi.repository.GdkPixbuf` hook – now with 43% more support for:
* Python 3 under OS X.
* Efficient writes without extraneous decodes and encodes.
* A new functional test exercising this hook.
Yes. Yes, there is. And it's awe inspiring in its simple simplicity. Unfortunately, it also:
* Fails for Python 3 under OS X (_as does the current version of this hook, to be fair_).
* Has yet to be revised to write without extraneous decodes and encodes under Windows and Linux.
* Has no functional tests.
This is a blocker for my [lazy hook …

Update `hook-gi.repository.GdkPixbuf.py` for Great Glory

---

PyInstaller/hooks/hook-sphinx.py

The sphinx_rtd_theme is no longer a required dependency as of sphinx 1.4.

Fix: Adjust sphinx hook for sphinx 1.4+

---

PyInstaller/hooks/hook-PyQt5.QtQuick.py
PyInstaller/utils/hooks/qt.py
PyInstaller/utils/misc.py

I've extended the QtQuick hook to include `qmldir` and `*.qmltypes` files. These are required for PyQt5 QML applications.
Fixes #1922

QtQuick hook adding 'qmldir' and '*.qmltypes'. Fixes pyinstaller#1922

---

PyInstaller/hooks/hook-sqlalchemy.py

SQLAlchemy 0.9 introduced the decorator 'util.dependencies'.  This decorator does imports.  eg:
```python
@util.dependencies("sqlalchemy.sql.schema")
```
This addition to the hook scans for included SQLAlchemy modules and then scans those modules for any util.dependencies and marks those modules as hidden imports.

Add hook to find any SQLAlchemy @util.dependencies() imports

---

PyInstaller/loader/rthooks/pyi_rth_gstreamer.py

The previous code separated the paths placed in GST_PLUGIN_PATH
using a semicolon, leading to failures trying to load plugins, as the paths are colon separated.
Instead, the paths were interpreted as a single path.
This commit replaces the semicolon with a colon, as per[1].
[1] https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gstreamer/html/gst-running.html
Please note that, related to this issue, at least for me, the gstreamer hook-gst._gst.py does not work. It seems to attempt to copy from incomplete/relative paths and it also attempts to put the plugins in a directory called "gst_plugins", instead of "gst-plugins". (underscore vs dash)
I'm hopeful that someone who I work with can fix the gstreamer hook and send those upstream as well. But this branch/pull-request can safely be …

GST_PLUGIN_PATH is colon separated.

---

PyInstaller/depend/bindepend.py

For Python 3, in `getImports_macholib()` (depend/bindepend.py) the rpaths are not getting extracted from the LC_RPATH records successfully. The crucial line is 
`rpath = str(command[2])`
Performing same steps manually:
```
>>> import sys
>>> import os.path
>>> sys.version
'3.4.4 |Continuum Analytics, Inc.| (default, Jan  9 2016, 17:30:09) \n[GCC 4.2.1 (Apple Inc. build 5577)]'
>>> pth = /Users/dauerbach/miniconda3/envs/pycal56/lib/python3.4/site-packages/PyQt5/QtGui.so
>>> pth_dir = os.path.dirname(pth)
>>> bytestr = b'/Users/dauerbach/Qt-5.6.0/lib\x00\x00\x00\x00\x00\x00\x00'
>>> rpath = str(bytestr)
>>> rpath
"b'/Users/dauerbach/Qt-5.6.0/lib\\x00\\x00\\x00\\x00\\x00\\x00\\x00'"
>>> rpath = rpath.rstrip('\x00')
>>> rpath
"b'/Users/dauerbach/Qt-5.6.0/lib\\x00\\x00\\x00\\x00\\x00\\x00\\x00' …
```

use decode("utf-8") to convert bytes to str in getImports_macholib()

---

PyInstaller/compat.py

This allows PyInstaller to find python library as installed by Conda/Miniconda python environment manager.

Add libpython%d.%dm.dylib to Darwin (is_darwin) PYDYLIB_NAMES.

---

PyInstaller/depend/bindepend.py

Following up on #1970, the failure concerns:
``` Python
exportSymbols = getattr(pe, 'DIRECTORY_ENTRY_EXPORT', None)
if exportSymbols:
for sym in exportSymbols.symbols:
if sym.forwarder is not None:
dll, _ = sym.forwarder.split('.')
dlls.add(winutils.convert_dll_name_to_str(dll) + ".dll")
```
Per the [pefile source](https://github.com/erocarrera/pefile/blob/master/pefile.py#L2342), this invokes [self.parse_export_directory](https://github.com/erocarrera/pefile/blob/master/pefile.py#L3373), where [forwarder = forwarder_str](https://github.com/erocarrera/pefile/blob/master/pefile.py#L3484) is assigned as [forwarder_str = self.get_string_at_rva(symbol_address)](https://github.com/erocarrera/pefile/blob/master/pefile.py#L3521). [get_string_at_rva](https://github.com/erocarrera/pefile/blob/maste …

Correctly decode a bytes object produced by pefile

---

PyInstaller/depend/bindepend.py

Hi,
I would like to use PyInstaller on OS X with a Python interpreter installed in my home directory.
The interpreter is installed in `$HOME/pkg/bin` and is dynamically linked with the Python shared library in `$HOME/pkg/lib`. This is done using run-time search paths, like so:
$ otool -L $HOME/pkg/bin/python
/Users/foo/pkg/bin/python:
@rpath/lib/libpython2.7.dylib (compatibility version 2.7.0, current version 2.7.0)
$ otool -l $HOME/pkg/bin/python
...
Load command 15
cmd LC_RPATH
cmdsize 32
path @loader_path/.. (offset 12)
The loader replaces `@loader_path` with the location of the interpreter, which is `$HOME/pkg/bin`, and finds the shared library at `$HOME/pkg/bin/../lib/libpython2.7.dylib`.
When I run PyInstaller, I get this error:
1765 INFO: Building PKG (CArchive) out00-PKG.pkg
3859 …

Replace run-time search path keywords

---

PyInstaller/depend/bindepend.py
PyInstaller/lib/pefile.py
setup.py

As a a start for #1920 I have applied the previous pefile deltas to the latest pefile and submitted the changes [upstream](https://github.com/erocarrera/pefile/pull/117).  As a partial fix for #1920, I would like to have the new version of pefile put back into the distribution until the pefile shortcuts are adopted upstream.  The slow down due to these changes not being present are quite significant in my application.
In an effort to keep the code changes to a minimum, and assuming that the pypi version is where PyInstaller is going, I did not remove all references to PyPi version of pefile.

Pefile optimizations

---

PyInstaller/building/toc_conversion.py

directory can already exist if there are dependency of multiple executables on setuptools or any other data files

Fix don't fail if directory already exists

---

PyInstaller/depend/bindepend.py
PyInstaller/utils/win32/versioninfo.py

Do not know if this will fix the problems in #2024 since appveyor always times out on my private builds, but closing things when finished with them shouldn't hurt anything.

Close PE() object to avoid mmap memory leak

---

PyInstaller/utils/cliutils/grab_version.py
PyInstaller/utils/cliutils/set_version.py

Allow grab_version and set_version to respond to ```--help``` on non-windows
systems.
Quick change to help with #2052.

Make grab version more polite on non-windows

---

PyInstaller/compat.py

Since OS X 10.11 the environment variable DYLD_LIBRARY_PATH is no
more inherited by child processes, so we proactively propagate
the current value using the `-e` option of the `arch` command.
This fixes a problem detecting PyQt when one wants to package a non system Qt version.

Forward DYLD_LIBRARY_PATH through `arch` command.

---

PyInstaller/utils/hooks/__init__.py

PYTHONPATH could be defined in the original `os.environ` too, use the
merged dictionary to be sure not to overwrite a non empty value.
This fixes a problem detecting PyQt installed in a virtualenv when executing the hooks.

Fix typo: `env` as been already merged in `pp_env`.

---

appveyor.yml

- Implement a better way of cleaning up temp files from a test run that works cross platform.
- Allow a scheduled Appveyor build to only install dependencies and not run tests.
This allows the cache to be kept fresh even when the tests are failing. Requires the "Build schedule" setting to be set on appveyor. See https://ci.appveyor.com/project/springermac/pyinstaller/build/1.0.90 for an example of a scheduled run.

Appveyor fixes

---

PyInstaller/loader/pyimod02_archive.py
tests/functional/test_libraries.py
tests/unit/test_hookutils.py
tests/unit/test_loader.py

Running this via `py.test -k test_threading_import[onedir] -s` (note: the `-s` flag is essential) produces the output below. Note that, all though py.test believes all tests pass, there's a failure and an exception produced.
I assume that there's only one instance of the `ArchiveFile` class in `pyimod02_archive.py`, meaning that `import` statements from multiple threads can corrupt its state, as the failure below shows. It appears that one thread closes the `ArchiveFile.fd` while another assumes that this file is still open.
There are two problems with this pull request I'm hoping that other can help with:
1. To reproduce the bug involves an ugly modification of `pyimod02_archive.py`, introducing a delay in one thread (which imports `csv`) but not in the other. Is there some cleaner …

Add: Example demonstrating a threading bug while processing imports.

---

appveyor.yml

This will hopefully help fix failures on Python 3.4, 3.3, and 2.7 with Appveyor, in which xdist seems to inject failures.
It doesn't run to completion on my personal Appveyor account, so I'm submitting this as a pull request to get a better build.

Fix: Run Appveyor library tests without xdist.

---

PyInstaller/building/imphook.py
PyInstaller/building/imphookapi.py
PyInstaller/compat.py
PyInstaller/hooks/pre_safe_import_module/hook-six.moves.py
PyInstaller/lib/modulegraph/modulegraph.py
tests/functional/modules/pyi_testmod_submodule_global_shadowed/__init__.py
tests/functional/modules/pyi_testmod_submodule_global_shadowed/submodule.py
tests/functional/modules/pyi_testmod_submodule_global_unshadowed/__init__.py
tests/functional/modules/pyi_testmod_submodule_global_unshadowed/submodule.py
tests/functional/test_hooks/test_scipy.py
tests/functional/test_import.py

Welcome to another pompously entitled pull request. In this family- and eco-friendly series of harmless commits, we:
* Fix #1919, a newly unveiled edge-case in `ModuleGraph` import detection.
* Add functional tests exercising this fix.
* __Document, comment, and refactor `modulegraph`__ for readability, maintainability, and consistency.
The future begins tomorrow.
To explain #1919, I should probably first explain a curious edge-case in CPython behaviour. I didn't know about it. You might not either! <sup>_...unless you're the sort of faceless mongoloid Pythonista who gets off on obscure_ `__init__.py` _abuse._</sup>
Consider a hypothetical package `ran` containing:
* A submodule `min`.
* A submodule `__init__` defining a global string variable `min` like so:
min = 'He shall hold a blade …

Shadows over ModuleGraph: Scaling the Impenetrable Wall of Bugs

---

PyInstaller/building/makespec.py

I improved the descriptions of the --add-data and --add-binary options
and removed the backticks which will hopefully fix
https://github.com/pyinstaller/pyinstaller/issues/2079

Doc update of two options in makespec.py and doc formatting issue fix

---

PyInstaller/hooks/hook-usb.py
tests/requirements-libraries.txt

Fix for #1891.
Fix custom locator to place found library in same directory as
executable.  (This was a regression from last September or so)
Added code to use pyusb's builtin library locator, before trying to use our custom locator.
Add pyusb to requirements so that tests are actually run. (This maybe why this bug was present for so long)
Also had to downgrade Pillow to 2.9.0 as 3.0.0 is not working on Appveyor

Fix 1891 usb.core no backend error

---

bootloader/src/pyi_pythonlib.c
bootloader/src/pyi_utils.c
bootloader/wscript

Added HAVE_MKDTEMP flag for AIX with GCC compiler

Changes to work with python 2.7 built with gcc on AIX platform

---

PyInstaller/hooks/hook-openpyxl.py
tests/functional/test_libraries.py

Add openpyxl hook

---

PyInstaller/hooks/hook-adios.py

Adds a hook with hidden imports for [ADIOS](https://www.olcf.ornl.gov/center-projects/adios/)' [numpy wrapper](https://pypi.python.org/pypi/adios).
Required for HDF-Compass packaging, see
https://github.com/HDFGroup/hdf-compass/pull/173
(side note: from a user, package & api perspective, this is all very close to the `h5py` package)

Add hook ADIOS

---

PyInstaller/loader/pyiboot01_bootstrap.py
tests/functional/test_import.py

If you try to wrap pip with pyinstaller on Ubuntu 14.04, it fails because it calls `ctypes.CDLL(None)` (see https://github.com/pypa/pip/blob/8.1.2/pip/pep425tags.py#L188).
This fixes that and adds a test.

First argument to ctypes.CDLL can be None

---

PyInstaller/hooks/hook-pytest.py
tests/functional/test_hooks/test_pytest.py

This hook makes it possible to embed the pytest runner into an executable using PyInstaller, making use of the `pytest.freeze_includes` function.
I decided to write this hook after converting pytest's own "freeze" testing environment from `cx_freeze` to `PyInstaller` (pytest-dev/pytest#1773) and seeing how much simpler is to use `PyInstaller`. Thanks for the excellent library!

Add hook for pytest modules

---

PyInstaller/hooks/hook-llvmlite.py
PyInstaller/hooks/hook-numba.py

Add install hooks for numba and llvmlite.
Numba has some optional support for IPython and scipy, so I'm excluding those if the application isn't using them elsewhere.
Numba requires llvmlite, which in turn comes with a binary lib that needs to be installed too.
Tested with Anaconda for Windows as well as numba self compiled on Linux.

Add install hooks for numba and llvmlite

---

.travis.yml
appveyor.yml
tests/requirements-libraries.txt
tests/requirements-tools.txt
tests/requirements-win.txt

Based on @jstewmon's idea at https://github.com/pyinstaller/pyinstaller/pull/2078#issuecomment-234361619, this moves from using `pip-accel` (which forces use of pip v7) to using `pip` (the current v8) to install packages, since newer pip can both cache installed packages and install some packages (numpy, Pillow) that old pip can't.
@htgoebel, @matysek, any concerns from the Unix/Mac side in moving in this direction?

Use pip instead of pip-accel for testing

---

bootloader/src/pyi_utils.c
doc/advanced-topics.rst

rather:
- prepend our path to the existing path
- save the original path in the environment
also:
implement pyi_strjoin (oh the joys of string processing in C!)
for more info, see #625, #1759 and the comments in the changeset.

bootloader: do not overwrite/lose LD_LIBRARY_PATH

---

PyInstaller/hooks/hook-cryptography.py

Fix for *Pyinstaller interaction with cryptography module*. #2013

Fix cryptography module missing backend

---

bootloader/src/pyi_utils.c

This reverts commit 1fab36c7108304db6c8fdae60b5143606a0534aa.
memcpy introduces a glibc 2.14 requirement, strcat is satisfied with glibc 2.2.5.
As strjoin is only called a few times, there is no need for this micro opt.

Revert "micro-optimize pyi_strjoin for no good reason", fixes #2160

---

PyInstaller/depend/bindepend.py
bootloader/src/pyi_utils.c

To address issue #1309.  Somewhere along the way, argv emulation (which was originally authored by me for 32-bit) was broken for 64-bit.  This emulation has been reimplemented for 64-bit OSX.
argv emulation is what allows a program to be able to grab the filename of a drag/dropped file onto an app.

(Re)add argv emulation for OSX, 64-bit

---

PyInstaller/hooks/hook-xsge_gui.py

Tested on Ubuntu 16.04, 64-bit.
This hook is to include the data files of xsge_gui so that it will work properly: https://pypi.python.org/pypi/xsge_gui
To test, use Pyinstaller on a game that uses it. The simplest such game is Kitten Command:
https://onpon4.itch.io/kitten-command

Added a hook for xsge_gui.

---

PyInstaller/hooks/hook-botocore.py

botocore requires html.parser (or HTMLParser in the case of python 2). This change adds them as a hidden import.

Issue #2094: Fix hook for botocore

---

PyInstaller/hooks/hook-gi.repository.GObject.py

Fix #2338
`gi._gobject.option.py` does not exist. The correct file to import is `gi._option.py` which is already imported by `hook-gi.py`

Remove non-existant gi._gobject.option import

---

PyInstaller/hooks/hook-redmine.py

When access some redmine attr in exe file will have following error
```
File "site-packages\redmine\__init__.py", line 47, in __getattr__
File "site-packages\redmine\managers.py", line 40, in __init__
redmine.exceptions.ResourceError: Unsupported Redmine resource
```
in `redmine/managers.py ResourceManager __init__` function will import
resource from redmine.resources

Add hook for redmine

---

PyInstaller/utils/hooks/gi.py

when using pygi provided by [PyGObject for Windows](https://sourceforge.net/projects/pygobjectwin32/), it will report gir-1.0 directory could not be found.
This will correct the path on windows and avoid unnecessary check for gir files.
expected to fix the issue [#1966](https://github.com/pyinstaller/pyinstaller/issues/1966)

patch to fix bugs on windows platform.

---

PyInstaller/hooks/hook-botocore.py

Pyinstaller is unable to bundle a package which imports boto3.
It fails with import error
`ImportError: No module named is_module_satisfies`
this issue occur after fix of issue #2304 
occurs with pyinstaller version 3.2.1

ImportError: No module named is_module_satisfies #2304

---

PyInstaller/utils/hooks/qt.py

it was missing bin/
This is a cherry pick of the unmerged commit from https://github.com/pyinstaller/pyinstaller/pull/2238

qt: fix homebrew qmake path

---

PyInstaller/loader/rthooks/pyi_rth_gstreamer.py

Fixed from https://github.com/pyinstaller/pyinstaller/pull/2214.

Run-time hooks: fix GST_PLUGIN_PATH separator being os dependant.

---

PyInstaller/hooks/pre_safe_import_module/hook-win32com.py

win32com hooks will skip adding path to process if not on windows. 
fixes #2462
Works fine for on my system. Mac and Ubuntu.
Note: I have not tested this on ``darwin + wine``  system or any other windows compatibility layer tools

Dissable processing win32com on non windows systems

---

PyInstaller/depend/dylib.py

Python 3.5 and Python 3.6 require `vcruntime140.dll` to be
available in Path. Otherwise, a python3x.dll error code
126 results.
For a related comment, see: https://github.com/pyinstaller/pyinstaller/issues/1566#issuecomment-284426877

Dylib: Add vcruntime140.dll to_win_includes for Py 3.(5,6)

---

PyInstaller/loader/pyiboot01_bootstrap.py

Commit b66f244 in the development version introduced the new exception type `PyInstallerImportError` that gets thrown if a library cannot be loaded with ctypes. However, this changes the behavior of previously working applications. 
For example, my application uses a library ([scikit-cuda](https://github.com/lebedov/scikit-cuda)) that tries to load multiple versions of DLLs of which only one has to be present. To handle missing libraries, it catches `OSError` and continues with the next one.
But when run with PyInstaller, `ctypes.CDLL` etc. do not throw `OSError` anymore, but instead `PyInstallerImportError`, which scikit-cuda does not catch, so it aborts.
Right now, I have to manually patch either PyInstaller or scikit-cuda to make it work (again).
The proper solution would be to …

Fix: Subclass PyInstallerImportError from OSError.

---

PyInstaller/compat.py

I'm using PyInstaller in MSYS2, and it's unable to find the python dynamic library during the build process, so this is a possible fix for that situation.
I've tried to detect MSYS2 using several methods (`sys.platform`, `os.uname`, etc.), but none really works consistently across different environments, so I'm just doing the simplest thing here and add the dynamic library name to `PYDYLIB_NAMES`

Look for libpython%.%.dll in Windows MSYS2

---

PyInstaller/building/osx.py

XML tag has encoding set to UTF-8 but the file is just plain ASCII. This crashes when any bundle property has any Unicode chars.

macOS bundle Info.plist should be in UTF-8

---

PyInstaller/hooks/hook-google.cloud.py
PyInstaller/hooks/hook-google.cloud.storage.py

Fixes https://github.com/GoogleCloudPlatform/google-cloud-python/issues/1187

PyInstaller: add hooks for google.cloud and google.cloud.storage

---

PyInstaller/building/utils.py

I ran into this and it took me awhile to figure out what had happened. Add an error message so that users can more easily figure it out and recover.

building: warn users if bincache gets corrupted

---

PyInstaller/hooks/hook-numpy.core.py

Fix for #2544, following up #2111, this grabs the MKL libraries on a Mac.

Look for OS X .dylib libraries in Numpy hook

---

bootloader/src/pyi_pythonlib.c

Within the `pyi_wargv_from_argv` function there is a condition which checks if `PI_Py_DecodeLocale` succeeded (for each argument). 
When this is not the case, the function terminates by returning `NULL`
Before exiting the function, `oldloc` is freed, but `wargv` and its content (added within the for loop) is never freed when the function is aborted.
This pull request adds the proper cleanup for `wargv` and its content before returning NULL , in the case that `PI_Py_DecodeLocale` fails.
Note: According to the [Python documentation](https://docs.python.org/3/c-api/sys.html):
> Decoding errors should never happen, unless there is a bug in the C library.
But it should still be handled gracefully as with the `oldloc` variable.
If I overlooked something or this behavior was desired/accepted for …

Fix potential memory leak in the bootloader

---

bootloader/src/pyi_archive.c
bootloader/src/pyi_utils.c

**Memory leak:**
Within `pyi_archive.c` in the function `pyi_arch_extract` the trough `malloc` allocated buffer `data` is not freed when the `fread` call fails. It immediately returns NULL.
Add `free(data)` to prevent a memory leak.
**Resource leak:**
Within `pyi_utils.c` in the function `pyi_copy_file` it is checked if `in` and `out` where correctly opened. Currently if `in` is successfully opened and `out` is not, `in` is never closed and vise versa.
These leaks where found using [Codacy](www.codacy.com).

Fix memory and resource leak

---

PyInstaller/utils/win32/versioninfo.py

I noticed that the "Product version" string in the file details tab doesn't display correctly for PyInstaller built executables. It's just empty...
This is caused by differences/errors in the way we serialize the `VS_VERSIONINFO` structure and substructures, so I tried to fix those differences/errors, so that the version info structure round trips correctly.
I essentially fixed this two issues:
* The String structure `wValueLength` is in *words*, not bytes.
* We used to somehow remove two bytes from the size of
`{String,Var}FileInfo` which seems wrong and causes Windows to skip an
entry.
I figured this out by binary diffing and not by some magical intimate knowledge of those structures so I hope this is correct.
I think Windows also pads the entire structure to some boundary (I don't know …

Make versioninfo.py round trip the version info correctly

---

PyInstaller/hooks/hook-shapely.py

Tested this hook file with Shapely 1.5.17 on Windows 7 64-bit when Shapely was installed via whl file.  Also successfully tested a build in CentOS 6.4.  Oddly enough the `so` file is copied over correctly in Linux, but Shapely didn't know how to find it in a `frozen` state.  I've submitted a pull request to the shapely library for that fix as well.
https://github.com/Toblerity/Shapely/pull/485

Add hook file for shapely library to correctly copy DLL

---

bootloader/src/pyi_main.c

On Mac, launching an application that's already open puts it in the
foreground. This didn't work for apps built with PyInstaller because
of the parent -> subprocess structure at runtime. The present commit
fixes the problem for --onedir mode by using a single process.
Closes #2616.

Use single process on Mac for --onedir mode

---

PyInstaller/hooks/hook-imageio.py

Imageio is a Python library that provides an easy interface to read and write a wide range of image data, including animated images, video, volumetric data, and scientific formats.
http://imageio.github.io/
This hook script will make it possible to include binaries for ffmpeg, avbin, and freeimage.
References:
- https://github.com/imageio/imageio/pull/270
- https://github.com/imageio/imageio/issues/32
[skip ci] no test case for this

Add hook for imageio

---

tests/functional/test_libraries.py

Fixes #2361. The module `idlelib.TreeWidget` name was changed to `idlelib.tree`.

Tests: functional: Fix idlelib test for python 3.6+

---

PyInstaller/__main__.py
PyInstaller/compat.py
PyInstaller/depend/dylib.py
PyInstaller/lib/modulegraph/find_modules.py
setup.py
tests/functional/scripts/pyi_win_py3_no_shortpathname.py

pypiwin32 doesn't work on msys2 for a variety of reasons, but pywin32-ctypes (once https://github.com/enthought/pywin32-ctypes/pull/53 is merged and a 0.1.0 release is made)
supports the minimum API that pyinstaller needs to work (except win32com, but that doesn't seem to be used anymore?).
There are ~40 test failures without msys2, and even more failures with msys2. If you're willing to accept this patch eventually, I can look into the tests some more. However, if that's not the case, then I'll probably just make a shim package that emulates pywin32 instead and has the correct pacakge names.
See also: https://github.com/Alexpux/MINGW-packages/issues/751

Support using pypiwin32 or pywin32-ctypes

---

PyInstaller/loader/pyiboot01_bootstrap.py

this fix #2585,
after some simple exam shows that os.path.abspath incorrect handle multibyte path,
so only apply it when necessary.

fix: py2 non-unicode sys.path been tempted by os.path.abspath

---

tests/functional/test_libraries.py

Test crashes the runner which significantly slows the test suite and exhausts disk space.

tests: functional: disable usb

---

.travis.yml
appveyor.yml
tests/functional/test_basic.py

Unmark macOS as an allowed failure. Some failing tests may have recently been missed because of this.
Also fix a couple issues on AppVeyor, i.e., when the cache was being cleaned, and which tests were being run in which stage.

Use Travis stages

---

PyInstaller/hooks/hook-wx.lib.pubsub.py
PyInstaller/utils/hooks/__init__.py

Two items:  
1) don't allow RuntimeErrors to terminate Pyinstaller's search
2) add appropriate hidden imports for wx.lib.pubsub so that
all of the package's modules make it into the TOC.
After these two fixes,  an application using wx.lib.pubsub can be successfully packaged and run.  There are still warnings in the Pyinstaller output, but they are expected, and I'm not sure how to suppress them.  This is because of the path manipulation that takes place within wx.lib.pubsub.core, which causes these imports to come from wx.lib.pubsub.core.kwargs or wx.lib.pubsub.core.arg1 as appropriate, not the locations listed below.
3755 WARNING: Hidden import "wx.lib.pubsub.core.listenerimpl" not found!
3756 WARNING: Hidden import "wx.lib.pubsub.core.publishermixin" not found!
3758 WARNING: Hidden …

Fix for issue #2215: hook-lib.wx.pubsub is not working.

---

PyInstaller/hooks/hook-wx.lib.pubsub.py
PyInstaller/utils/hooks/__init__.py

Reverts pyinstaller/pyinstaller#2233
This pull request caused test failures related to pyzmq. We need to be stricter about only merging pull requests when the tests pass now.

Revert "Fix for issue #2215: hook-lib.wx.pubsub is not working."

---

PyInstaller/utils/cliutils/grab_version.py
PyInstaller/utils/win32/versioninfo.py

As in the title. Fixes Issue #859.

Display a friendly error message when grab_version.py utility fails (#859)

---

bootloader/wscript

-m64 flag is not supported in arm64/aarch64 machines. So, this ignores the flag for these machines

for 64-bit arm/aarch linux ignore -m64 flag

---

PyInstaller/lib/modulegraph/modulegraph.py

Main culprit is `osgeo._gdal`. This module is first imported by
`osgeo/__init__.py` via `import _gdal`. It is also imported "properly"
from `osgeo/gdal.py` which is the corresponding SWIG python module. By the time `osgeo/gdal.py` is imported the `_gdal` module has already been defined as missing and never gets imported.
This solution was chosen as the least obstructive while still being
generic enough to help other modules in the future.
An argument could be made (see related issue) that the osgeo hook should just handle this, but since osgeo/gdal may not be the only one breaking the mold on how to use SWIG modules this may be useful again. I leave it up to the maintainers on what the best option is. I've copied the important part of my last comment in the related issue below:
Test file …

Fix #1522: Fix modulegraph to reimport failed SWIG C modules (_gdal)

---

PyInstaller/loader/rthooks/pyi_rth_multiprocessing.py
tests/functional/scripts/pyi_multiprocess.py
tests/functional/scripts/pyi_multiprocess_forking.py
tests/functional/scripts/pyi_multiprocess_pool.py
tests/functional/test_basic.py
tests/functional/test_multiprocess.py
tests/functional/test_runtime.py

This PR is based on @springermac's #2793. It fixes issues #2322 and #2759. It supersedes #2505.
See my comments in #2322 for a diagnosis of the underlying issue.
This PR adds a runtime hook that patches `multiprocessing.freeze_support` to catch the Python library's attempts to start the semaphore tracker and fork server processes.  It also includes the logic from https://github.com/pyinstaller/pyinstaller/wiki/Recipe-Multiprocessing.

Runtime hooks: Fixes #2759, multiprocess spawn mode on POSIX OSs

---

PyInstaller/__init__.py
PyInstaller/compat.py
PyInstaller/utils/win32/icon.py
PyInstaller/utils/win32/versioninfo.py
PyInstaller/utils/win32/winresource.py
PyInstaller/utils/win32/winutils.py
setup.py

Reverts c901c4265c1bd41332396e6e7ec7f5290bd79bb4 and fixes the problem instead*
... I'm not currently able to run the tests reliably on Windows, so I'm doing this so I can watch them on appveyor. I'll comment here if I think it got fixed.

Change "early pywin32 import" warning back into an error

---

bootloader/wscript

"python setup.py install" failed due to missing translation map entries.
works, tested within the freebsd 64bit borgbackup build.
can we have a v3.3-maint branch (to later create 3.3.n from)?

freebsd: fix bootloader install, fixes #2861

---

PyInstaller/hooks/hook-unidecode.py
tests/functional/test_libraries.py
tests/requirements-libraries.txt

This should fix `unidecode ` ignoring non-ASCII characters when frozen (see e,g. SO threads [here](https://stackoverflow.com/questions/30919966/unidecode-inconsistent-behavior-when-using-pyinstaller) and [here](https://stackoverflow.com/questions/25184178/using-pyinstaller-on-a-script-the-imports-unidecode)). 
Urgh, sorry - I see CI is not happy on 2.7. I'll check in the afternoon.

Hooks: Add hook for unidecode

---

doc/development/pull-requests.rst

Also move the text up in front of "git push" (since it should be done prior to pushing).

Doc: More details how to sync a github fork with upstream.

---

PyInstaller/hooks/hook-accessible_output2.py
PyInstaller/hooks/hook-sound_lib.py

This pull request fixes hooks for @CToth libraries (accessible_output and sound_lib) by importing from `PyInstaller` instead of `pyinstaller`.

Fix accessible_output, sound_lib hooks.

---

bootloader/wscript

This PR address ticket #2876 when using MSVC compiler.
Basically this makes the linker use the option /SUBSYSTEM, with its 4 combinations:
*  `/SUBSYSTEM:WINDOWS,5.01`
*  `/SUBSYSTEM:CONSOLE,5.01`
*  `/SUBSYSTEM:WINDOWS,5.02`
*  `/SUBSYSTEM:CONSOLE,5.02`
Where 5,01 is used for 32bit arch and 5,02 for 64bit.
I ran a few manual tests which worked ok, if there's some suite, please let me know how to run it.
I'm not sure if for an automated build system, an extra setup (package having support for that platform is required to be installed for MSVC, in that case, please let me know).

bootloader Windows XP compatibility 

---

PyInstaller/compat.py

https://github.com/pyinstaller/pyinstaller/issues/2849
Currently the aarch64 machines use `Linux-64bit` to run Pyinstaller. It should regard the architecture as well to run Pyinstaller.

Regards architecture for aarch64 platform

---

PyInstaller/hooks/hook-sysconfig.py

The CPython implementation adds additional modules for importing in sysconfig for Python 3.6 and above.
Anaconda's Python 3.5.4 backports this feature for this version. This fixes the hook by removing the Python version check since there are cases where Python 3.5 may have the additional modules. Instead, sysconfig is checked for a function that was added for the additional module to get the name.
Fixes #3105

Fix ImportError for sysconfig for 3.5.4 Conda

---

PyInstaller/depend/bindepend.py

Previously runtime search path keywords like @loader_path and @executable_path were only properly replaced if they were followed by a slash, for example for a value like "@executable_path/Frameworks".
If the LC_RPATH value is just "@executable_path" without slashes, it would not be replaced, resulting in an invalid path string computed from executable_path + "/" +  "@executable_path".
The fix is to match just the keyword which is not followed by a slash.

Fix replacement of runtime search path keywords

---

.travis.yml

The need for the cache stage is now questionable because
the PyInstaller build stage has enough extra time to cache
dependencies that need to be compiled. Also, there's only
a need for linting Python 2.7 and Python 3.6 because the
syntax is all the same on Python 3.
Closes #2865.

Tests/CI: clean-up travis.yml

---

tests/unit/test_modulegraph/test_modulegraph.py

`__slotnames__` can appear on objects that have slots, and needs
to be removed before comparing an object's dict.
This came up on #3107.

Tests: modulegraph: remove __slotnames__ from methods

---

PyInstaller/hooks/hook-usb.py

`hook-usb.py` "asks" pyusb which library to pack by inspecting `usb.backend`. This only result in a library name (e.g `libusb-1.0.so.0`), which is sufficient for `ctypes` to load the library, but not enough for pyinstaller to find the file and pack it.
This fix solves this problem by using `_resolveCtypesImports` to figure out the full path to the file pyusb loads.

Fix #2633: Resolve library name reported by usb.backend in hook-usb

---

PyInstaller/hooks/hook-PySide.QtSql.py
PyInstaller/hooks/hook-PySide.phonon.py

Current PySide hooks properly include both QtSql and Phonon dll and pyd files, but plugins for sql drivers and phonon backends are missing. These additonal hooks fix the problem.

Hooks: Add hooks for PySide.phonon and PySide.QtSql

---

PyInstaller/loader/pyimod03_importers.py

If PyInstaller fails to add a DLL into the package, then the error message looks like:
```
...
line 631, in exec_module
exec(bytecode, module.__dict__)
File "site-packages\scipy\fftpack\basic.py", line 12, in <module>
File "c:\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 714, in load_module                                                                
ImportError: DLL load failed: The specified module could not be found.
```
This pull request improves the error message. In my case it becomes:
```
...
line 631, in exec_module
exec(bytecode, module.__dict__)
File "site-packages\scipy\fftpack\basic.py", line 12, in <module>
File "c:\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 717, in load_module
raise ImportError(f'{err}: …
```

Better ImportError message in case a DLL was not added into the package

---

PyInstaller/building/utils.py

This fixes #2526. Pyinstaller is updating the resources for python35.dll and makes its signature invalid. This then prevents that dll from being signed with the 'signtool' utility (which then can have more consequences, like the inability to publish the app to a repository where signing is mandatory).
In this commit, the resource update is skipped if it is not necessary, i.e. it is only performed if there have been som redirections or if the dll has been made private.
Test scenario: run pyinstaller on a Python app (https://github.com/tlecomte/friture) without these changes and 'signtool' fails to sign python35.dll with the error code 0x800700C1, ERROR_BAD_EXE_FORMAT. With these changes, the packaged python35.dll still shows its "Python Software Foundation" signature, and 'signtool' can …

Only update resources when necessary to keep signature valid

---

doc/advanced-topics.rst
doc/runtime-information.rst

The docs make it seem like `LD_LIBRARY_PATH_ORIG` is always set on Linux. That's not the case. It's only set when `LD_LIBRARY_PATH` was set. Update the docs to reflect this.

Doc: Reflect actual behavior in "Run-time Information"

---

PyInstaller/utils/win32/icon.py

An invalid file path argument to --icon is detected in one of two places. If it ends in `.ico` an attempt to open the file is in the `__init__()` method of the `IconFile` class. Here trap any IOError subclass, which would include nonexistent file, unreadable file, etc, and raise SystemExit with a simple "could not open" message.
Other file extensions are opened using win32api.LoadLibraryEx which expects to get an EXE (or a DLL?). If it fails, win32api raises its unique exception which includes the windows error string and error code. These are formatted into a message string for SystemExit.

utils/win32: trap invalid --icon arguments and terminate with a message

---

.gitignore
PyInstaller/hooks/hook-usb.py
tests/functional/test_libraries.py

This PR addresses the issues raised in https://github.com/pyinstaller/pyinstaller/issues/2633:
~~1. Enable, always, `library_test::test_usb`. Make sure a backend exists on Travis by adding `libusb-1.0` to the package list. The code tests for the presence of a usb backend, which on some versions of Linux can crash Python when finalization happens (`libusb_exit` crashes), and seems related to whether libusb was loaded on a worker thread. Anyway, since asking if we have USB crashes, just ensure that a USB backend actually exists. This seems reasonable, since `requirements-library.txt` already installs `pyusb` and the expectation of pyusb is that you can do USB work.~~
1. Ugh, ok, it's really challenging to tiptoe around the linux pyusb issue. Currently the entire test_usb function is skipped …

Linux usb hook fixes

---

PyInstaller/compat.py

When you use the -W option to python interpreter some of the modules
present in base_library.zip requires the warnings module, raising an
error. The issue is solved by adding it to the PY3_BASE_MODULES set.
Closes: #3397

Add missing warnings module in base_library.zip

---

PyInstaller/hooks/hook-numpy.py
PyInstaller/hooks/hook-scipy.py

This hook will add the new private `scipy._lib` C-extension modules to the archive, and when building on Windows, include the DLL bundle used by the official wheel provider stored in `site-packages/scip/extra-dll`

Update scipy hook to support 1.0.0 revision

---

PyInstaller/hooks/hook-pandas.py

pandas>=0.21 has a hidden import of "pandas._libs.tslibs.timedeltas.so".

Hooks: Add hook-pandas.py to fix issue #2978.

---

PyInstaller/hooks/hook-gi.repository.GdkPixbuf.py
PyInstaller/hooks/hook-gi.repository.Gst.py
PyInstaller/loader/rthooks/pyi_rth_gdkpixbuf.py

Tested on msys2 and Fedora. Probably fixes #3257.

Hooks: update Gst and GdkPixbuf to work on msys2

---

PyInstaller/hooks/hook-gi.repository.xlib.py
PyInstaller/hooks/pre_safe_import_module/hook-gi.repository.xlib.py

PyInstaller need a hook to correctly import `gi.repository.xlib` module
and the associated files.
Fixes #2634

Add missing gi.repository.xlib hook

---

PyInstaller/hooks/hook-Cryptodome.py

Since version 3.4.8, also the package Cryptodome.Math contains
binary files that needs to be included.

Look for binaries also in package Cryptodome.Math

---

PyInstaller/archive/writers.py
PyInstaller/building/utils.py

Directly bundling pyc-files makes the build output dependent on the modification time of pyinstaller source files. This change removes that relation and re-enables deterministic builds.
I didn't find a better place to add this than here. We need low-level access to the file to change the header so it can't be done after compressing it.
PEP552 actually made this a bit harder as it changed the pyc-header format. Since we don't know the magic number for the outstanding release that adds PEP552 support, I checked for the presence of the bit-field instead:
> The pyc header currently consists of 3 32-bit words. We will expand it to 4. The first word will continue to be the magic number, versioning the bytecode and pyc format. The second word, conceptually the new word, will be a bit field. The …

Fake timestamp in pyc-header

---

PyInstaller/utils/hooks/gi.py

It was giving error:
31529 INFO: Loading module hook "hook-gi.repository.GObject.py"...
Empty DEST not allowed when adding binary and data files. Maybe you want to used '.'.
Caused by '/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0'.

correction in gi-hooks for binary paths

---

PyInstaller/hooks/hook-Crypto.py

PyCryptodome is an almost drop-in support for the now unmaintained PyCrypto library (`Crypto` namespace).
**Important:** this PR adds support for applications that use PyCryptodome, but it does not allow encryption of the python script (``--key`` option). The reason is that PyInstaller assumes that either `Crypto.Cipher.AES` or `Crypto.Cipher._AES` are **native** Python extensions, but they are not in PyCryptodome.

Hooks: hook-Crypto: support for PyCryptodome

---

doc/installation.rst
doc/operating-mode.rst

Several pages in the documentation have code-blocks improperly formatted as quote blocks. This leads to commands being displayed improperly.
For example, in [`operating-mode.rst`](https://pyinstaller.readthedocs.io/en/stable/operating-mode.html#what-pyinstaller-does-and-how-it-does-it), the option for single-executable mode:
pyinstaller --onefile --windowed myscript.py
Incorrectly renders with a single dash, causing the command to fail.
pyinstaller -onefile -windowed myscript.py

Fix code block formatting in Documentation

---

PyInstaller/utils/win32/winmanifest.py
PyInstaller/utils/win32/winresource.py

I have faced issue that PyInstaller crashes when trying to add resources to Windows executable using `--resource` option. This pull request contains minimal fix tested on Python 2.7.14 and 3.6.3.
There is also an issue proposing the same fix: https://github.com/pyinstaller/pyinstaller/issues/2675

Fix of the addition of resources for Windows executables

---

PyInstaller/building/osx.py

Some useful items in Info.plist of a Mac bundle involve keys referencing
other arrays or dicts.  (e.g. CFBundleDocumentTypes or
UTExportedTypeDeclarations)  Before this commit all of these items would
have to be added outside of pyinstaller by hand.
This commit adds a recursive parsing function so that a hierarchical
info_plist python object in a spec file can be parsed into a
hierarchical Info.plist dict.  It also properly tabs the resulting XML.
* Python dicts resolve to XML `<dict>`
* Python lists resolve to XML `<array>`
* All other Python items are added as an XML `<string>` (as before)

Build: OSX: Add new hierarchical handling of info_plist.

---

doc/_common_definitions.txt
doc/spec-files.rst

See Issue #3540 
As plistlib has been added to the code to process the info_plist build argument dict, info_plist can now accept nested python objects, and python datatypes other than strings.  This update to the documentation reflects these new capabilities and includes new examples, as well as removing descriptions of limitations that no longer exist.

Doc: Revise section on info_plist for plistlib functionality.

---

PyInstaller/utils/win32/winutils.py

Python.net override built-in __import__ function and is too strict on its signature. This change allow import to work with all Python (and python.net) versions.

Make it compatible with applications using Pythonnet package

---

PyInstaller/hooks/hook-PyQt5.QtNetwork.py
tests/functional/test_libraries.py

Fixes #3511 . Tested to work on Windows.
I wish I could have added a functional test as well, but I can't seem to get the tests to run even after installing pypiwin32. I'm getting the following error:
```console
> py.test -n 8 tests\functional
PyInstaller cannot check for assembly dependencies.
Please install PyWin32 or pywin32-ctypes.
pip install pypiwin32
```

Hooks: Fix missing SSL libraries on Windows with PyQt5.QtNetwork

---

PyInstaller/hooks/hook-PySide2.QtGui.py

This adds the styles directory to binaries and should fix #3374 . I was having the same problem on MacOS. This resolved it for me.

3374 - added styles to PySide2 hook to fix style mismatch

---

PyInstaller/hooks/hook-PyQt5.py

@bjones1 
`opengl32sw.dll` was being copied into `PyQt5\Qt\bin\opengl32sw.dll\opengl32sw.dll` so it was creating the destination as a directory and then copying the file into it.
This is what binaries contained for me.
```
>>> binaries
[('C:/users/testvm/desktop/gui/venv/lib/site-packages/PyQt5/Qt/bin\\opengl32sw.dll', 'PyQt5\\Qt\\bin\\opengl32sw.dll')]
```

Hooks: Place PyQt5 DLLs in the correct location

---

.travis.yml
PyInstaller/__main__.py
PyInstaller/building/makespec.py
appveyor.yml

This is a fix for issue #3585 
The bug was introduced when DEBUG_ALL_CHOICE was placed inside a new list here: https://github.com/pyinstaller/pyinstaller/commit/bbede2ea3cb86c998bd21c3ccfa4a94633039e88#diff-98596315ae5d573e2ec661f6cd25f560R181
argparse was having trouble parsing the arguments.

3585 - Fix broken arguments including -h flag

---

PyInstaller/building/api.py

resolves #2641
following up on an issue where the security alert is triggered when
building my code, and ran into this issue. PR seemed trivial, so putting
it up to help.
Not sure this will resolve my own issue with `inm` having a crazy path in my case

Fix Security-Alert: try to store file outside of dist-directory. Aborting. 'my..data.txt'

---

PyInstaller/hooks/hook-bokeh.py

Hook for packaging bokeh (https://bokeh.pydata.org/en/latest/) applications.

support for bokeh visualization library

---

PyInstaller/hooks/hook-jedi.py

#3535 jedi import fails because it doesn't find files from `site-packages\jedi\evaluate\compiled\fake\*.pym`
On `jedi\evaluate\compiled\fake.py", line 19, in _get_path_dict` there is not check if directory exists is `os.listdir` raises `FileNotFoundError`. 
This hook adds the required files.

Add jedi hook

---

PyInstaller/building/api.py
PyInstaller/building/osx.py
bootloader/src/pyi_launch.c

A possible fix for #1917.
As proposed by @codewarrior0 in his [comment](https://github.com/pyinstaller/pyinstaller/pull/1206#issuecomment-165976396), I added a bootloader runtime option `pyi-osx-background` that triggers the right transform type in `pyi_launch_initialize()`.
This is the simplest option as it does not require to add new bootloaders nor a new argument to handle this specific case. The behavior is restored as it should have been: when the user sets `LSUIElement` in the Info.plist dict, PyInstaller handles it.
The patch is good but does not work automatically because the TOC option is not yet forwarded to the bootloader.
In `$project/build/BUNDLE-00.toc`, I have the line `('pyi-osx-background', '', 'OPTION')` setted, which is what we need.
But as this kind of TOC line is …

Bootloader: OSX: Respect Info.plist options

---

bootloader/src/pyi_utils.c

On Linux, `wait` is used to wait for child process to exit. However, as stated in the manual:
```
The call wait(&status) is equivalent to:
waitpid(-1, &status, 0);
```
Doing so works fine in most cases, but when the child process itself plays with `switch_root`, it seems to signal the parent process, consequently leaving the function before its child has exited.
It will then delete the previously extracted files, and so create a race condition (the child might not have loaded all its libraries yet).
Using `waitpid` ensures that the child process that we just created has finished.

bootloader: use waitpid instead of wait

---

PyInstaller/hooks/hook-google.api_core.py
PyInstaller/hooks/hook-google.cloud.translate.py

Add hooks to allow building of scripts using google.cloud.translate and google.api_core imports e.g:
```
from google.cloud import translate
from google.api_core.exceptions import ...
```
This should also resolve pr: #3251

Add hooks for google-cloud-translate and google-api-core

---

PyInstaller/hooks/hook-rdflib.py
PyInstaller/news/3708.hooks.rst

This hook adds the plugins included in `rdflib.plugins`, when `rdflib` is imported.
The RDFlib organizes the serializers and parsers in a plugin system, which is not loaded with import statements.
- https://github.com/RDFLib/rdflib
- https://rdflib.readthedocs.io/
- https://rdflib.readthedocs.io/en/stable/plugins.html

Add hook for rdflib

---

PyInstaller/hooks/hook-gi.repository.Champlain.py
PyInstaller/hooks/hook-gi.repository.Clutter.py
PyInstaller/hooks/hook-gi.repository.GtkChamplain.py
PyInstaller/hooks/hook-gi.repository.GtkClutter.py
PyInstaller/hooks/pre_safe_import_module/hook-gi.repository.Champlain.py
PyInstaller/hooks/pre_safe_import_module/hook-gi.repository.Clutter.py
PyInstaller/hooks/pre_safe_import_module/hook-gi.repository.GtkChamplain.py
PyInstaller/hooks/pre_safe_import_module/hook-gi.repository.GtkClutter.py
tests/functional/test_hooks/test_gi.py

Hi,
I used PyInstaller to freeze an application which needed [`Clutter`](https://wiki.gnome.org/Projects/Clutter), `GtkClutter`, [`Champlain`](https://wiki.gnome.org/Projects/libchamplain/) and [`GtkChamplain`](https://developer.gnome.org/libchamplain-gtk/). I have written some basic hooks for that and I propose to add them in PyInstaller.
I also modified the test suite of `gi` hooks to be able to handle the weird version number of `Champlain` and `GtkChamplain` (0.12)

Add the support and the tests of Champlain and Clutter

---

PyInstaller/archive/writers.py
PyInstaller/building/makespec.py
PyInstaller/compat.py
PyInstaller/depend/bindepend.py
PyInstaller/depend/dylib.py
PyInstaller/lib/modulegraph/modulegraph.py
PyInstaller/lib/modulegraph/util.py
PyInstaller/loader/pyimod03_importers.py
PyInstaller/utils/cliutils/archive_viewer.py
PyInstaller/utils/cliutils/grab_version.py
PyInstaller/utils/misc.py
PyInstaller/utils/osx.py
PyInstaller/utils/win32/versioninfo.py
PyInstaller/utils/win32/winmanifest.py
PyInstaller/utils/win32/winresource.py
news/3677.core.rst
old/e2etests/win32/NextID.py
setup.py
tests/functional/conftest.py
tests/functional/scripts/pyi_module_attributes.py
tests/old_suite/runtests.py
tests/unit/test_altgraph/test_dot.py
tests/unit/test_modulegraph/test_zipio.py

Fixes Python 3 warnings:
```python
utils/misc.py:224: DeprecationWarning: 'U' mode is deprecated
f = open(filename, 'rU', encoding='utf-8')
```
I fixed the whole module in several places to be consistent.
---
Also fixes a lot of resource leaks:
```python
utils/misc.py:150: ResourceWarning: unclosed file <_io.BufferedReader name='/.../loader/pyimod03_importers.pyc'>
(open(obj_fnm, 'rb').read()[:4] != BYTECODE_MAGIC)
archive/writers.py:86: ResourceWarning: unclosed file <_io.BufferedReader name='.../project/PYZ-00.pyz'>
self.add(toc_entry)  # The guts of the archive.
```
Actually, there were numbers of those 2 specific warnings, more another one not really spotted:
```python
Exception ignored in: <_io.FileIO name='.../struct.pyo' mode='rb' closefd=True>
ResourceWarning: unclosed file …
```

Fix several ResourceWarnings and DeprecationWarnings

---

PyInstaller/hooks/hook-PyQt5.QtWebEngineWidgets.py
PyInstaller/loader/rthooks/pyi_rth_qt5webengine.py
news/pr3661.hooks.rst
tests/functional/test_libraries.py

This fixes issue #3652 so that the QtWebEngine can be used on macOS.

Hooks: fix QtWebEngine hooks

---

PyInstaller/hooks/hook-PyQt5.QtWebEngineWidgets.py
news/3758.hooks.rst

On Archlinux, the NSS package ships with /usr/lib/libnss3.so.
The auto detection works fine with that, but the fix from #3439 breaks it again
since no /usr/lib/nss/libnss3.so exists:
INFO: Loading module hook "hook-PyQt5.QtWebEngineWidgets.py"...
Unable to find "/usr/lib/nss/*.so" when adding binary and data files.
Thus, it should only be added on distributions where it's really necessary.
With this change, test_PyQt5_QWebEngine works on Archlinux (it failed before).

Only add NSS subdir path if it exists

---

PyInstaller/building/build_main.py
news/2326.bugfix.rst
news/3694.bugfix.rst

This commit fixes issue #2826, '"datas" is "binaries"?'.

fix issue #2826: "datas" is "binaries"?

---

PyInstaller/compat.py
PyInstaller/news/3513.core.rst
setup.py

This reverts commit 250d72b4f884912b2c1ef4605c1de31c8d5cb55a, which causes PyInstaller to be uninstallable on Windows without pywin32-ctypes.
See https://github.com/pyinstaller/pyinstaller/pull/3513#discussion_r222240942 - cc @rth

Revert "setup: Remove hack required to not fail when pypiwin32 isn't found."

---

PyInstaller/hooks/hook-PyQt5.QtWebEngineWidgets.py

On macOS with a case-sensitive filesystem, this failed because the folder name
is QtWebEngine and not QtWebengine.
cc @melvyn2 (introduced in 33e9adfb78c2cbec07bd06f01214581754c36cec)

hooks: Fix QtWebEngine casing.

---

PyInstaller/depend/utils.py

Current implementation of PEP552 was only valid for Python 3.7.
By the way I've replaced the helper function _write_long with standard Python lib calls.

Write additional bitfield for Python 3.7 and later.

---

PyInstaller/building/api.py
PyInstaller/building/osx.py
news/3653.core.rst

This will allow us to pass folders as data to BUNDLE and COLLECT and for them to be added like files instead of raising an exception.

Handle folders in COLLECT and BUNDLE

---

PyInstaller/hooks/hook-jsonpath_rw_ext.py
news/3841.hooks.rst

This is a simple hook that adds a hook to support the following python library: https://pypi.org/project/jsonpath-rw-ext/.

Add support for the jsonpath_rw_ext library

---

PyInstaller/hooks/hook-soundfile.py
news/3844.hooks.rst

hi,
this module can be installed by using pip install pysoundfile
it depends on libsndfile, which is located at _soundfile_data, which this hook loads it and put's it in its directory for loading.

added a hook for pysoundfile

---

PyInstaller/compat.py
news/3536.feature.rst
news/3881.feature.rst

The current patterns does not match the way python is installed
with RedHat SCL python36 on RHEL7.
libpython3.6m.so (libpython%d.%dm.so) points to the right library

Fix python library lookup for RHSCL python 3.6

---

PyInstaller/hooks/hook-pendulum.py
PyInstaller/hooks/hook-pytzdata.py
news/3906.hooks.rst
tests/functional/test_libraries.py
tests/requirements-libraries.txt

This PR addresses the issues with Pendulum, as discussed in #3528.
The hooks were tested on the following setup:
- OSX 10.13.6
- Python 2.7.15
- Python 3.7.0
- Pendulum 2.0.4
- Pytzdata 2018.7

Added hook for Pendulum and its dependency pytzdata

---

PyInstaller/fake-modules/site.py
news/3945.bugfix.rst
news/3945.feature.rst

Jupyter Notebook requires USER_BASE to be a 'str' not None.

Set USER_BASE to empty string

---

PyInstaller/compat.py
PyInstaller/depend/bindepend.py
news/3885.bugfix.rst
news/4015.bugfix.rst
news/is_conda.bugfix.rst

Fixes #3885
* PyInstaller/depend/bindepend.py: On Unix with Anaconda look
in compat.base_prefix for Python dynamic library.
* PyInstaller/compat.py: Fix is_conda.

depend/bindepend: Fix Linux Anaconda Python library search.

---

PyInstaller/hooks/hook-imageio_ffmpeg.py
news/4051.hooks.rst

In imageio version 2.5, ffmpeg is installed via the imageio-ffmpeg package and not via downloading to the resources directory. The initial imageio hook (https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/hooks/hook-imageio.py) still applies and should remain in PyInstaller.
https://github.com/imageio/imageio-ffmpeg
https://github.com/imageio/imageio-ffmpeg/issues/5

Add hook for imageio_ffmpeg

---

.travis.yml

Work around not being able to open /etc/init.d/xvfb.

Tests/CI: Use services for xvfb on xenial

---

PyInstaller/utils/win32/versioninfo.py
news/3142.bugfix.rst
news/3572.bugfix.rst

When updating the PE file version resource on some platforms, the Windows API calls
exclude the overlay region when writing back the executable. PyInstaller stores its
archive in the overlay region and the executable unusable without it.
This change restores the overlay region if it is eliminated during version update.
Commit resolves #3142.

versioninfo: Fixes PE file corruption during version update.

---

PyInstaller/compat.py
PyInstaller/depend/bindepend.py
news/1566.core.rst
news/3736.core.rst

bindepend: don't generate warnings regarding missing UCRT dependencies on windows 10 as these files do not exist on purpose (see issue #1566)

UCRT warnings on win10

---

PyInstaller/hooks/hook-importlib_resources.py
news/4095.hooks.rst

This is the backport module for `importlib.resources` in Python 3.7+. Because of that depending on Python version much of the code can be removed. It also uses itself to set the `__version__` attribute, requiring that data file.

Hooks: Add hook for importlib_resources

---

tests/functional/data/requests/server.pem
tests/functional/scripts/pyi_lib_requests.py
tests/functional/test_libraries.py

This should fix the requests test case on all platforms.
I got the same error that is mentioned in the `@skipif` annotation on Linux, so I just generated a new key for the webserver.
I took the liberty to remove the restriction to TLSv1, so the test server can negotiate any TLS version the current Python supports.

Update certificate for mock HTTPS server

---

doc/spec-files.rst

The international English spelling of NSPrincipleClass doesn’t work.

Correct spelling of NSPrincipalClass in Spec File docs

---

doc/runtime-information.rst

Just checking `sys.frozen` is not enough to check if a program is
running from PyInstaller - some other Python packages also seem to set
this.
Mention that in most cases `__file__` can be used from a bundled app as
one usually does. Also mention that this does not work from the main
script as it doesn't know where it lives in the module hierarchy.
Fix #2882

doc: update runtime information

---

PyInstaller/building/makespec.py
doc/operating-mode.rst
news/4001.feature.rst

Force --windowed option for .pyw files as described in issue #3326.  This behavior is documented in appendix 16 of the Python manual as noted by @tallforasmurf .

building: force --windowed option for .pyw

---

PyInstaller/building/api.py
PyInstaller/building/makespec.py
PyInstaller/building/osx.py
PyInstaller/building/templates.py
PyInstaller/building/utils.py
news/3821.feature.rst

closes #2659.
With this PR, one can run PyInstaller with (for example) `--upx-exclude "vcruntime140.dll"`. This will exclude the "vcruntime140.dll" binary from being compressed with UPX.
I could only test with this specific dll (because i didn't stumble over any other that fails with UPX), but it appears to be working, both in onefile and onedir mode. In the specfile, this option looks like this:
```
[...]
upx=True,
upx_exclude=['vcruntime140.dll'],
runtime_tmpdir=None,
[...]
```
I'm marking this as WIP because there's still stuff to be done. According to the docs i should add some tests for this (a field i have no experience whatsoever in), ~~and the news fragment is missing as well~~. Also i would would be surprised if all tests passed *and* you approved this right away (it's my first …

(WIP) Exclude selected binaries from compression with UPX using `--exclude-upx`

---

PyInstaller/hooks/hook-ttkthemes.py
news/4105.hooks.rst

[ttkthemes](https://github.com/RedFantom/ttkthemes) is a package that provides a set of themes for Tkinter. In order to achieve this, it uses Tcl-code files and image files. These are not properly copied by PyInstaller by default on Windows. There are various work-arounds, including for users to adjust their `spec` file, writing custom release scripts and maybe even other ways, but given the amount of confusion this has caused so far, I would like for a hook to be included with PyInstaller.
It is my understanding that this is the best way to achieve this. I have tested the hook, and the files are now copied over correctly and the result of PyInstaller on Windows runs without the need of manually copying over files.
Issue references:
- PyInstaller Issue pyinstaller/pyinstaller#3517
- …

Hooks: Add hook for ttkthemes

---

.gitattributes

Modified .gitattributes to get \n EOL regardless of host OS.

Tests: Test data should get consistent line ending regardless of host

---

PyInstaller/hooks/hook-radicale.py
news/4109.hooks.rst

This hook fixes:
1. Failure to import due to get_distribution('radicale') failing
2. Missing data files needed for the web interface
Radicale - A Free and Open-Source CalDAV and CardDAV Server
https://radicale.org/

Add a hook for Radicale

---

PyInstaller/hooks/hook-notebook.py
news/4270.bugfix.rst
news/4270.hooks.rst

When trying to build an application inside a docker image where Jupyter packages were installed as a user installation (within the home directory) I ran into an issue where the paths returned by ``jupyter_core.paths`` don't necessarily exist:
```
33598 INFO: Loading module hook "hook-scipy.py"...
33599 INFO: Loading module hook "hook-sqlite3.py"...
33651 INFO: Loading module hook "hook-notebook.py"...
Unable to find "/usr/share/jupyter" when adding binary and data files.
##[error]Bash exited with code '1'.
##[section]Finishing: Building application
```
This PR simply updates the hook for the ``notebook`` package to make sure that paths are only included in ``datas`` if they actually exist.
I've also switched to using the helper functions instead of the constants from ``jupyter_core`` - …

Make notebook hook more robust to whether directories actually exist

---

PyInstaller/loader/rthooks.dat
PyInstaller/loader/rthooks/pyi_rth_certifi.py
news/3952.hooks.rst

Use certificate from certifi only if cafile could not find by ssl.

Add runtime hook for certifi.

---

PyInstaller/hooks/hook-skimage.io.py
news/3934.hooks.rst

Hooks: Add hook for skimage.io
The skimage.io package (of Scikit-Image) uses the additional package skimage.io._plugins as hidden import and its data. When skimage.io is being used, the added hook makes sure that pyinstaller imports the skimage.io._plugins package and its data too.
This solves issue #3313

add hook-skimage.io.py

---

PyInstaller/hooks/hook-pint.py
news/4280.hooks.rst

Accessing pint version at runtime requires setuptools metadata.

Hooks: hook-pint should copy metadata.

---

PyInstaller/hooks/hook-pysnmp.py
news/4287.hooks.rst

Closes #4286
Added hook to collect missing `pysnmp` files.
Not sure that this is the best way but it worked for me.

Hooks: Add hook for pysnmp.

---

PyInstaller/depend/utils.py
news/4096.core.rst

For the pyc files in base_library.zip, produce the deterministic pyc files as described in PEP-552.
The reason for this is that I found when using pyenv and trying to do deterministic builds with multiple machines, builds were not deterministic due to the pyc file in base_library.zip having different timestamps that corresponded to the time that pyenv installed python.
I was unable to figure out how to get this to work when the hashes are checked so this uses the unchecked mode.

Produce deterministic pyc files in base_library.zip

---

doc/development/commit-messages.rst

Fix wording in "Please Write Good Commit Messages" section

Doc: Fix wording

---

PyInstaller/hooks/pre_find_module_path/hook-distutils.py
news/4064.bugfix.rst
news/4372.bugfix.rst

When run in a venv, `distutils` present in the venv is not suitable for freezing, instead the system-wide `distutils` should be used. `pyinstaller` relies on a pre-find-module-path hook to change the search path to point to this system-wide `distutils` location.
To do this, it made use of a `distutils_path` attribute that was set in `virtualenv`, which pointed to the system-wide `distutils` dir. This `distutils_path` was never meant to be part `virtualenv`'s public api. Consequently, as part of a [change in `virtualenv 16.3`](https://github.com/pypa/virtualenv/pull/1289), this `distutils_path` points to the `__init.py__` of the system-wide `distutils` when run on python >= 3.4, as opposed to the dir. Consequently, the `os.path.dirname` used in the original hook returns the wrong result. …

hooks: Don't rely on virtualenv internals for system distutils detection, fixes #4064

---

PyInstaller/building/utils.py
news/4440.bugfix.rst

strip_paths_in_code() now uses CodeType.replace() if available to
support the new CodeType construction (PEP 570: Positional-Only
Parameters).
Co-Authored-By: Pablo Galindo Pablogsal@gmail.com

Fix strip_paths_in_code() for Python 3.8

---

bootloader/src/pyi_path.c
news/3823.bootloader.rst
news/3829.bootloader.rst
tests/functional/scripts/pyi_symlink_basename_is_kept.py
tests/functional/specs/symlink_basename_is_kept.spec
tests/functional/test_basic.py

This fixes #3823 
As far as I understand; the current behavior is wrong: when doing `execvp()` we are passing the **resolved** `argv[0]`. This means that the name under `/proc/self/status` will be incorrect.
If the new behavior is desired (it is for me at least; telegraf is reporting parent and child as different processes and that confuses my monitoring system) then the whole reading from `/proc/` to get our full path is not needed anymore (as that will resolve all symlinks).
Let me know if you want me to change anything

Bootloader: Ensure that symlinks to binaries do not get resolved.

---

bootloader/src/pyi_global.c
bootloader/src/pyi_global.h
doc/when-things-go-wrong.rst
news/4288.feature.rst

When running a DEBUG WINDOWED application on win32 we don't have any
console to send debug messages to. I find the repeating message boxes
annoying and propose to send the output text to the debugger.
If no debuggers are attached to the process DebugView tool
(https://docs.microsoft.com/en-us/sysinternals/downloads/debugview) can
be used.
If this PR seems useful I will add the changelog item.

Bootloader: don't use debug message boxes on win32.

---

bootloader/src/pyi_path.h
bootloader/src/pyi_pythonlib.c
news/1566.bootloader.rst
news/2170.bootloader.rst
news/4230.bootloader.rst

As #2170 (comment), current PyInstaller onefile mode with Python 3.5 or later has not working properly on legacy windows(7, 8, 8.1) that Universal CRT update is not installed, even though all dependencies related Universal CRT are packaged.
It caused by that that SetDllDirectory function only affects explicit linking(ex-LoadLibrary) not implicit one, so api-ms-win-crt-runtime-l1-1-0.dll couldn’t load ucrtbase.dll on temppath(extractionpath) while Python library loading.
In order to workaround this issue, I put some codes that loading ucrtbase.dll manually before Python library loading if it is packaged.
I've tested and verified it on a clean install of Windows 7 SP1.

Bootloader: win: Add a workaround for Python library loading failure in onefile mode

---

doc/spec-files.rst

Hey,
Have been using PyInstaller for a while and decided, in the spirit of Hacktoberfest, to contribute back to the project. You have been doing incredible work!
I have contributed to other projects, such as `pytest`, but never to `PyInstaller` so feel free to correct me if I have made any errors during this flow. I am going to start with a very small change to see how it goes. :smile: 
This commit was prompted by #4283, which reported that the documentation was misleading.
As suggested in the issue, I have added an additional example and made references to "Adding Data Files" in the hopes of making it clearer.
I have tested it according to guidelines found in https://pyinstaller.readthedocs.io/en/latest/development/documention.html.
Hope everything is fine. If you find any issue, please …

Doc: Clarify "Adding Binary Files"

---

doc/usage.rst

Concerned link was in section "Using Pyinstaller/Platform-specific notes/Windows" and was invalid
(redirecting to the Microsoft developer landing page instead of the Windows SDK download page)

Doc: fix broken link to Windows 10 SDK page

---

PyInstaller/depend/utils.py
news/4261.bugfix.rst

In case `ldconfig` is not available in the environment PyInstaller
currently aborts package creation as the `OSError` exception is not
handled. This change catches the execption and logs a warning, while
leaving the LD cache in disabled state. This can allow the package
creation to continue.
This can be very helpful in the following situation: users can populate
`LD_LIBRARY_PATH` with the library paths they want PyInstaller to look
for library dependencies for. If all libraries are found in these
locations the LD cache logic won't be triggered. If however a library
not needed on the platform (e.g. a Windows DLL on Unix) is picked up as
a `ctypes` dependency, it won't be found on the library path and
execution will reach the LD cache logic. In certain sandbox
environments, like a `chroot` …

Depend: Handle ldconfig failure gracefully

---

PyInstaller/building/api.py
PyInstaller/lib/modulegraph/modulegraph.py
news/4125.bugfix.rst
news/4417.bugfix.rst

Fixes: #4125
This PR replaces #4240 that was never finished by updating the commit messages to be more descriptive and adding a changelog entry.
1. MINGW Python packages in MSYS2 name Windows dll files with a -cpython-37m.dll extension. Loading a Python module that depends on a dll, for example struct and zlib, results in a ModuleNotFoundError since modulegraph is not looking for files with this naming convention.
2. Fixes double processing of dependencencies when using COLLECT after EXE. When processing of MINGW Python dll files, this results in corrupted file paths, for example when processing the _struct
dll the resulting filepath is dllruct-cpython-37m/_struct-cpython-37m.dll instead of just
_struct-cpython-37m.dll.

Fix MSYS2 dll's are not found by modulegraph

---

PyInstaller/hooks/hook-google.api.py
news/3251.hooks.rst

In my build, I found a runtime error unless I included these hook files before build.

adding hooks for google cloud & google api modules

---

PyInstaller/hooks/hook-google.cloud.bigquery.py
news/4083.hooks.rst
news/4084.hooks.rst

Add hooks for google.cloud.bigquery and requests library as big query depends on requests.
Fixes issue #4083

Hooks: Add Hook for Google Big Query

---

PyInstaller/hooks/hook-google.cloud.kms_v1.py
news/4408.hooks.rst

The google-cloud-kms client library requires a hook in order to be packaged into an executable with PyInstaller
Client library URL: https://googleapis.dev/python/cloudkms/latest/index.html#
Import Example for client library: https://cloud.google.com/kms/docs/reference/libraries#client-libraries-install-python

Hook: Add hook for the google-cloud-kms client library

---

PyInstaller/hooks/hook-soundfile.py
news/4325.hooks.rst

The hook exists to package the libsndfile binary when required.
However pysoundfile only bundles libsndfile on OSX and Windows,
on Linux it relies on a system package. Attempting to include
_soundfile_data on Linux therefore results in an unexpected
exception as per #4325.
Furthermore the bundled files are different on OSX and Windows
so the data required has to be platform specific.
Closes #4325.

Hooks: Make the soundfile hook platform aware

---

PyInstaller/hooks/hook-sounddevice.py
news/4498.hooks.rst

This PR adds a hook to bundle the port audio binary for Windows and macOS that the `sounddevice` library bundles with its wheel. 
Link to library docs: https://python-sounddevice.readthedocs.io/en/0.3.14/
Link to library repo: https://github.com/spatialaudio/python-sounddevice
I took guidance for creating this PR from #4326

Add sounddevice library hook on Windows and macOS

---

4514.hooks.rst
PyInstaller/hooks/hook-scrapy.py

Scrapy has grown to become one of the ubiquitous components of python for scraping needs. It is only logical to make building projects built with this framework a breeze.
This hook addresses issues with building Scrapy projects with PyInstaller.
Thanks

Add Scrapy hook

---

PyInstaller/hooks/hook-passlib.py
news/4520.hooks.rst

Adds a basic hook for passlib. Maybe we need to add more packages to hidden imports but this is enough so I can distribute a small utility script.
This should also fix #649 (which was closed two years ago due to the lack of activity).

hooks: add hook for passlib

---

PyInstaller/hooks/hook-ttkwidgets.py
news/4484.hooks.rst

[ttkwidgets](https://github.com/RedFantom/ttkwidgets) is a package that provides a set of custom widgets for Tkinter/ttk. Some of these widgets use custom images, located in the `ttkwidgets/assets` folder. These files are not copied by PyInstaller by default. Similarly to the situation with #4105 this causes some confusion (RedFantom/ttkwidgets#34) and therefore I would like for a hook to be included with PyInstaller.
I have tested the hook and the files are copied correctly and the resulting executable runs properly after using PyInstaller with the hook.

Hooks: Add hook for ttkwidgets

---

PyInstaller/hooks/hook-django_babel.py
news/4516.hooks.rst

_Note: This is a corrected version of #4499. I did something horrible on my fork and ended up rewriting the history and erasing my commits._
Hey,
This PR will add a hook for `django-babel`, fixing #4281. The issue there was that `django-babel` uses `pkg_resources.get_distribution` in their `__init__.py`, without having imported `django-babel` explicitly. This means that when freezing, PyInstaller doesn't import `django-babel` and therefore errors when executing the resulting package.
I have tested this with the script given in the issue:
```
import importlib
import django_babel
import datetime
if __name__ == '__main__':
print("Hello dear friend, how are you")
today = datetime.date.today()  
print(today)
```
I have only tested it in Ubuntu 18.04 though. Hope everything is okay. 
Thanks for …

Add hook for django-babel.

---

PyInstaller/hooks/hook-PySide2.QtNetwork.py
news/4467.hooks.rst
news/4468.hooks.rst

As described in issue #4467, the PySide2 QtNetwork hook currently breaks PyInstaller for projects using PySide2. This commit changes the hook to mirror [the changes made to the PyQt5 QtNetwork hook](https://github.com/pyinstaller/pyinstaller/commit/47bd7f10de3b343270fd4d34b356f14617d5d3a1#diff-cfc3f87059223ae1b3d84abe9a90e8f0).
Pinging @bjones1 for review.
Resolves #4467.
As a follow up, it would probably make sense to check for and filter out bogus paths added to the binary dependency list somewhere down the line. An invalid binary dependency should never result in trying to add every file in the project tree as a binary dependency.

Hooks: Fix PySide2.QtNetwork hook by mirroring PyQt5 approach.

---

PyInstaller/hooks/hook-gi.repository.GdkPixbuf.py
news/4486.hooks.rst

Fix #4485. The current GdkPixbuf hook assumes that gdk-pixbuf-query-loaders is in the PATH. In Ubuntu and Debian it is located in the GI libs directory. This change adds the GI lib directory
command to be searched with the other commands on the path.
Signed-off-by: Dan Yeaw <dan@yeaw.me>

Hooks: Fix gdk-pixbuf-query-loaders not in path in Ubuntu

---

PyInstaller/hooks/hook-IPython.py
news/4271.bugfix.rst

IPython imports its own extensions by adding the extensions directory to sys.path and using importlib:
https://github.com/ipython/ipython/blob/master/IPython/core/extensions.py#L79
This means that currently applications built with pyinstaller and including IPython will run into errors such as:
```
File "IPython/core/shellapp.py", line 261, in init_extensions
File "IPython/core/extensions.py", line 80, in load_extension
File "importlib/__init__.py", line 126, in import_module
File "<frozen importlib._bootstrap>", line 994, in _gcd_import
File "<frozen importlib._bootstrap>", line 971, in _find_and_load
File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'storemagic'
```
This PR fixes this by …

Fix loading of extensions for IPython

---

PyInstaller/hooks/hook-PySide2.QtWebEngineWidgets.py
PyInstaller/hooks/hook-PySide2.py
PyInstaller/loader/rthooks/pyi_rth_pyside2webengine.py
news/4377.bugfix.rst
news/4377.hooks.rst
tests/functional/data/PySide2_QWebEngine/test_web_page.html
tests/functional/test_libraries.py

There existing PySide2 QtWebEngine hooks seem to be outdated. In particular, the expected location for supporting files like locales, processes, etc. differ between platforms and from the more mature `PyQt5` module. As a result, they are not copied into the distribution folder correctly because they can't be found. 
For example, the windows layout for the `PySide2` module does not have a `Qt` subdirectory, so many files are not copied over with the [existing hook](https://github.com/pyinstaller/pyinstaller/compare/develop...tangm:4331-missing-pyside2-qtwebengine-files?expand=1#diff-a97672366bee4f42c1427c26d31f099bL21-L25).
This tries to adapt the more updated `PyQt5` hook for `PySide2`, taking into account some input from the [official QT for python …

hooks: Updating PySide2 hooks for QtWebEngine

---

PyInstaller/hooks/hook-pyarrow.py
news/3720.hooks.rst
news/4517.hooks.rst

_Note: This is a corrected version of #4500. I did something horrible on my fork and ended up rewriting the history and erasing my commits._
Hey,
I saw #3720 and decided to pull the code into an appropriate hook and submit a PR for it. I have removed `pyarrow.formatting` and `pyarrow.compat.*` from the hidden imports as PyInstaller was alerting that those modules could not be found after installing `pyarrow`.
Thanks,
Hugo

Add pyarrow hook

---

PyInstaller/building/api.py
news/4381.bugfix.rst
news/4539.bugfix.rst

building: Allow usage of VSVersionInfo again.

---

bootloader/wscript

Library identifier needs to be changed from 'Z' to 'z'
See #4211

issue-4211: fix bootloader: library identifers are case sensitive on AIX

---

bootloader/wscript
news/4501.build.rst
news/4586.build.rst

Fixes issue #4501. Fixes part of #4513.
When trying to build the bootloader with MinGW-w64, it was giving a windres.exe: windows\run.rc.o: No such file or directory error.
The error was caused because waf only sets the target and source arguments, WINRC_TGT_F and WINRC_SRC_F, when there is no WINRC configuration already set. PyInstaller with MinGW-w64 is setting the WINRCFLAGS which changes the WINRC configuration. The fix for this is to set the WINRC_TGT_F and WINR_SRC_F values manually.
Signed-off-by: Dan Yeaw <dyeaw@ford.com>

Bootloader build: Fix .rc.o file not found with MinGW-w64

---

PyInstaller/building/api.py
news/4591.feature.rst

I have a package called vapoursonic, producing a binary called `vapoursonic` too. File structure is like:
```
-src/
----vapoursonic/
--------main.py
--------config.py
```
and `main.py` imports `config.py` via
```python
import vapoursonic.config
```
During the `COLLECT().assemble()` phase, pyinstaller is trying to copy my packages `*.pyo` files into `$OUTPUTDIR/vapoursonic`, which is correct. However, because my executable name is also `vapoursonic`, pyinstaller checks that the *path* `$OUTPUTDIR/vapoursonic` exists, but doesn't ensure that it's a directory. At this point, the executable already exists and is called `vapoursonic`. Pyinstaller assumes that it is a directory, and tries to copy the `.pyo` into it, resulting in the following error:
```python
NotADirectoryError: [Errno 20] Not …
```

Bootloader collect: Detect when file exists at path we want to be dir

---

PyInstaller/utils/cliutils/archive_viewer.py

This keeps stdout open for true output, so someone can run archive_viewer with stdout redirected and not have error messages mixed in with the output. The concrete benefit of following this convention this is that output can then be piped to programs that don't know how to parse out and ignore the prompts and error messages.

Per POSIX guidelines, diagnostics (error messages, prompts, etc) belong on stderr

---

PyInstaller/hooks/hook-sklearn.mixture.py
news/4612.hooks.rst

Adds missing sklearn hidden imports.
Fixes pyinstaller when trying to compile such minimal example file:
```python
from sklearn.mixture import GaussianMixture
print('test')
```

Hooks: Add hook for sklearn.mixture

---

PyInstaller/hooks/hook-numpy.py
PyInstaller/hooks/hook-scipy.py
news/4593.hooks.rst

On windows, numpy and scipy package dlls under the extra-dlls directory under site-packages. However, if you install numpy/scipy on windows through a mingw compatible terminal like git bash, then those dlls are packaged under the .libs directory.
hook-numpy and hook-scipy are written based on native windows installs. This breaks if you use pyinstaller from a mingw compatible terminal. Update the hooks to account for this difference.

Fix hook-numpy and hook-scipy to account for differences in location of extra dlls on windows

---

doc/runtime-information.rst

the "are we bundled?" check code runs in pyinstaller, but not under the python interpreter.   Obviously, the code should run in both configurations.  When my code found this issue, I found someone on StackOverflow had a fix, adding the False default to the getattr function on line 12.  It makes sense to get this fix back into the documentation to prevent this in the future.

"bundled?" check doesn't run in python interpreter

---

PyInstaller/utils/hooks/qt.py
news/4636.hooks.rst

E.g. conda-forge builds of qt5 have QT_LIBINFIX set to '_conda', thus
generating library binaries called 'Qt5Core_conda.dll' for example on
Windows. Since lib_name is generated from the library's filename, it
won't be found in the '_qt_dynamic_dependencies_dict', leading to
missing hiddenimports, translations and plugins.
If lib_name was not found in the dependencies dictionary, this matches
the dependencies dictionary's keys as prefix to the lib_name, searching
longest keys first.

utils/hooks: match qt5 library names with suffixes.

---

PyInstaller/depend/utils.py
news/4654.bugfix.rst

Ensuring repeatable builds of base_library.zip by iterating over graph nodes sorted by identifier, rather than iterating over graph nodes in arbitrary order.
see https://github.com/pyinstaller/pyinstaller/issues/4654

Fixing Issue #4654 - Builds of base_library.zip not repeatable

---

README.rst

When using python from the windows store with PyInstaller, there are permissions errors that require a major mod to the UAC system in the underlying windows kernel to work around. 
It's caused by the damned `WindowsApps` directory, which, for security reasons, even running as *admin* can't even *read* the directory. This means that when PyInstaller (trys to) copy the python dlls and librarys, it fails. You can work around this, but the method risks jailbreaking, which voids warranty. 
This can be "fixed" by saying that we don't support that build of python. (Note that that is actually standard CPython)
Closes #4507

Remove support for python from the windows store

---

tests/requirements-libraries.txt

Updated:
* `boto3` to 1.12.11
* `botocore` to 1.15.11
* `markdown` to 3.2.1
* `phonenumbers` to 8.11.4
* `pycryptodome` to 3.9.7
* `pycryptodomex` to 3.9.7
* `pyzmq` to 19.0.0
* `requests` to 2.23.0
* `sphinx` to 2.4.1
* `web3` to 5.6.0
* `pandas` to 1.0.1
* `pyenchant` to 3.0.1

Tests/CI: Scheduled monthly dependency update for march

---

PyInstaller/hooks/hook-astor.py
PyInstaller/hooks/hook-tensorflow.py
PyInstaller/hooks/hook-tensorflow_core.python.py
news/4704.hooks.rst
tests/functional/test_libraries.py

Closes #4400
Closes #3754
Closes #4438
Closes #2828
Closes #3103
Closes #3709
As discussed on:
https://github.com/pyinstaller/pyinstaller/issues/4400
This PR should close - #4400 
This should resolve the import error caused by tensorflow farward import logic. 
The astor hook is to resolve this issue:
https://stackoverflow.com/questions/59702200/pyinstaller-tensorflow-bundle-fails
I've noticed this issue as well on my machine

Hook for tensorflow 2.0 and astor (imported by tensorflow)

---

PyInstaller/building/utils.py
news/4727.build.rst

> On your own risk, you can use the option --noconfirm to get rid of this question
seems unnecessary when already using `--noconfirm` and there is no question to get rid of.

Don't inform about --noconfirm if being used.

---

PyInstaller/hooks/hook-puremagic.py
news/4709.hooks.rst

Puremagic depends on data files  that are not collected by default, making the module unusable if they are not supplied together in the final bundle.

Add puremagic support

---

PyInstaller/hooks/hook-xmldiff.py
news/4680.hooks.rst

Created for the latest xmldiff version 2.4
Required due how xmldiff uses pkg_resources.require("xmldiff")[0].version in their main.py
Tested on Windows 10 latest non insider builds.
https://github.com/Shoobx/xmldiff

Hook for xmldiff v2.4

---

PyInstaller/hooks/hook-bleak.py
news/4649.hooks.rst

Tested with `bleak              0.5.1` on Windows 10 Pro 10.0.17763 Build 17763 using `pyinstaller --onefile`

Pyinstaller support for Bleak dotnet backend

---

PyInstaller/compat.py
news/4210.bug.rst
news/4738.bug.rst

(AIX) add pattern to find libpython3.Xm.so
Closes #4210

bootloader: search for python malloc labeled shared libraries (AIX)

---

PyInstaller/hooks/hook-bokeh.py
news/4742.hooks.rst
news/4746.hooks.rst

Per Bryan at Bokeh:
> _sri.json is a new file that must be present in the package.
I simply added `collect_data_files('bokeh')` to datas to include `bokeh/_sri.json`.
https://discourse.bokeh.org/t/bokeh-2-0-0-and-pyinstaller/4904

bokeh==2.0.0 requires bokeh/_sri.json

---

bootloader/wscript
doc/bootloader-building.rst
news/4677.build.rst

This allows end users to target a different macOS version using the environment variable
`MACOSX_DEPLOYMENT_TARGET` and specifying `-mmacosx-version-min` in `CPPFLAGS/CFLAGS`
and `LDFLAGS/LINKFLAGS`

Fallback to a default min macOS version instead of forcing it

---

PyInstaller/hooks/hook-webassets.py
news/4760.hooks.rst

[`webassets`](https://webassets.readthedocs.io/) filters are not included in the generated bundle.
- Add a hook to include the library `.py` files.
- Add reference to `news/` change log. 
#3283
<hr />
Thanks so much for the awesome tool.

Hooks: Add webassets hook.

---

PyInstaller/hooks/hook-nltk.py
news/3900.hooks.rst

Had the same issue as here:
https://github.com/pyinstaller/pyinstaller/issues/3799
proposed change is what htgoebel suggested

fix unable to find "C:\Users\user\nltk_data" #3799

---

PyInstaller/hooks/hook-shapely.py
news/2834.hooks.rst
news/4749.hooks.rst

This is a continuation of PR #3842, which fixes the shapely hook on windows.
This pull request makes the following changes:
1. Only include the geos_c.dll file, as geos.dll is not used by shapely.
2. Search the appropriate directories for geos_c.dll to account for both conda and vanilla python usage. The method used here is similar to that used in shapely itself. 
Closes #2834

Fix shapely hook on windows

---

bootloader/wscript
doc/bootloader-building.rst
doc/usage.rst
news/4730.build.rst
news/4731.build.rst
news/4731.doc.rst

Closes https://github.com/pyinstaller/pyinstaller/issues/4730
The intent is clear - however the value -X32 or -X64 is passed as 3 seperate arguments (-X -3 -2) and these are not recognized by the AIX linker/loader (ld).
The argument -X32 or -X64 is better managed using the environment variable OBJECT_MODE as all AIX utilities recognize this environment variable.

additional argument STRIPFLAGS not passed properly to linker/loader (AIX)

---

setup.cfg

@htgoebel I love statistics. You may have noticed that on some repos (eg https://github.com/numpy/numpy) there's a little button at the top, along with "star" and other such things. It lists the packages dependant on pyinstaller, and I think - I'm quite sure - we don't have one because our *PyPI* package name isn't the same as what everyone installs in a requirements.txt: `PyInstaller` on PyPI, and `pyinstaller` in requirements.txt etc. I know for a fact that case doesn't matter on PyPI, and won't affect anything at all, so can we try changing it to see if "dependants" shows up?

Change the package name to lowercase

---

bootloader/src/pyi_launch.c
bootloader/src/pyi_python.c
bootloader/src/pyi_python.h
news/4213.bootloader.rst
news/4592.bootloader.rst

Adds the Python traceback information to debug errors during pyiboot01_bootstrap when running in Windows in windowed mode. This will allow debugging errors like in Issue #4213.
In order to get the full traceback, you need to use `--debug=noarchive`. I have tried to test this as much as I can for Python 2.7 and < Python 3.7 compatibility using a minimal example, but I don't have a full test app to duplicate pyiboot01_bootloader errors with.
Signed-off-by: Dan Yeaw <dyeaw@ford.com>

Bootloader build: Add traceback to debug pyiboot01

---

bootloader/src/pyi_utils.c
news/4244.bugfix.rst
tests/functional/test_signals.py

Currently, when running a PyInstaller packed program in Linux shell and typing Ctrl-Z, the terminal stops responding. This PR aims at fixing this issue by handling the SIGTSTP signal differently in the PyInstaller bootloader.

Fixed #4057 - Ctrl-Z issue

---

bootloader/src/mkdtemp.h
bootloader/src/pyi_archive.c
bootloader/src/pyi_archive.h
bootloader/src/pyi_global.h
bootloader/src/pyi_launch.c
bootloader/src/pyi_launch.h
bootloader/src/pyi_main.c
bootloader/src/pyi_path.c
bootloader/src/pyi_path.h
bootloader/src/pyi_pythonlib.c
bootloader/src/pyi_pythonlib.h
bootloader/src/pyi_utils.c
bootloader/src/pyi_win32_utils.c
bootloader/tests/test_launch.c
bootloader/tests/test_path.c
bootloader/tests/wscript
bootloader/wscript
news/4585.bootloader.rst

Fixes Issue #4196, picks up work from PR #4219.
GCC 8.1 and later added checks to prevent using strncpy and strncat with the bounds depending on the length of the source str. In order to fix this, a few approaches were made:
1. Where guards already existed to ensure that added paths weren't
larger than the PATH_MAX, I changed to strcpy / strcat which don't take
a length parameter.
2. Where path length checks didn't exist, I set the bounds of the strncpy and strncat to PATH_MAX.
Signed-off-by: Dan Yeaw <dyeaw@ford.com>

Bootloader build: Fix GCC warnings for strncpy and strncat

---

PyInstaller/utils/win32/versioninfo.py
news/4861.bugfix.rst

I think all of the values in this struct should be uint32, especially the ..LS (low word) entries. Otherwise setting a filedate fails.

building: Fix struct format strings for versioninfo

---

bootloader/src/pyi_launch.c
news/4213.bootloader.rst
news/4592.bootloader.rst
tests/functional/test_libraries.py

Disable the extra traceback on Apple as a fix.
This is monkey-patch style; this bug needs fixing. However, I doubt it will get fixed in PyInstaller 4.0, and we don't want to release a known bug if possible.
Tempory fix for #4860

Drop apple traceback

---

PyInstaller/hooks/hook-importlib_resources.py
news/4889.hooks.rst

Since 1.2.0 importlib_resources uses importlib.metadata to pick up
package version.
Since 1.3.1 there is a hidden import of `importlib_resources.trees`
(using `__import__()`).
It also looks like this hook used to set `excludedmodules` variable
which is not even a thing as far as I can tell
(likely meant `excludedimports`).
Tested with importlib_resources 1.5.0.
Fixes #4725

hooks: importlib_resources: Fix for modern versions

---

PyInstaller/compat.py
news/4895.bugfix.rst

Fixes #4893
Python installation in OSX Brew has Python library binary as Python3
which is not considered when importing default binaries

compat: consider Python<version> as possible library binary path

---

PyInstaller/archive/pyz_crypto.py
PyInstaller/building/build_main.py
PyInstaller/building/makespec.py
PyInstaller/loader/pyimod02_archive.py
README.rst
doc/_common_definitions.txt
doc/usage.rst
news/2365.bugfix.rst
news/3093.bugfix.rst
news/3133.bugfix.rst
news/3160.bugfix.rst
news/3198.bugfix.rst
news/3316.bugfix.rst
news/3619.bugfix.rst
news/4241.bugfix.rst
news/4652.bugfix.rst
tests/functional/test_basic.py
tests/requirements-tools.txt

[tinyaes](https://github.com/naufraghi/tinyaes-py) is a minimal AES-only library that wraps the C library [tiny-AES-c](https://github.com/kokke/tiny-AES-c).
Currently the library wraps only the CTR mode that can be used in PyInstaller instead of the CFB mode used before.
Reading various sources, CFB is [somewhat similar to CBC](https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation#Cipher_Feedback_(CFB)) and CTR is suggested as a go-to stream cipher (https://crypto.stackexchange.com/questions/6029/aes-cbc-mode-or-aes-ctr-mode-recommended and links) that can be used instead of CBC.
See the issue comments for more discussion https://github.com/pyinstaller/pyinstaller/issues/2365#issuecomment-578691520
Closes #2365

Replace PyCrypto with tinyaes for encryption support

---

PyInstaller/building/makespec.py
PyInstaller/depend/analysis.py
PyInstaller/loader/pyiboot01_bootstrap.py
PyInstaller/loader/pyimod02_archive.py
PyInstaller/loader/pyimod03_importers.py
PyInstaller/utils/win32/winmanifest.py

I recently went over [Matplotlib](https://github.com/matplotlib/matplotlib/pull/16706), [Pandas](https://github.com/pandas-dev/pandas/pull/32322) and [NumPy](https://github.com/numpy/numpy/pull/15731), fixing a small mistake in the way that Python 3's exception chaining is used. If you're interested, I can do it here too. I've done it on just one file right now. 
The mistake is this: In some parts of the code, an exception is being caught and replaced with a more user-friendly error. In these cases the syntax `raise new_error from old_error` needs to be used.
Python 3's exception chaining means it shows not only the traceback of the current exception, but that of the original exception (and possibly more.) This is regardless of `raise from`. The usage of `raise from` tells Python to put a …

Cleanup: Fix exception causes in winmanifest.py

---

PyInstaller/building/utils.py
news/4922.bugfix.rst

This should result in the removal of the longest possible prefix.
Previously, an empty string at the beginning of sys.path would prevent
this code from doing anything.

building: Sort replace_paths by descending length.

---

bootloader/src/pyi_launch.c
news/4213.bootloader.rst
news/4592.bootloader.rst

#4592 added a new traceback to the bootloader. That caused an error that was originally reported and fixed in #1869 and 36b6ab3. The error was that `SystemExit` - the standard script exit exception, raised by `sys.exit` and other exit functions, was handled as a normal exception, and the bootloader printed `Failed to execute script X`, before erroring.
This PR fixes this by checking if this error is a SystemExit _first_.
Fixes #4860

bootloader: only print "failed to execute" error on non-SystemExit errors

---

PyInstaller/compat.py
PyInstaller/loader/pyimod03_importers.py
PyInstaller/utils/hooks/__init__.py
PyInstaller/utils/win32/icon.py

@Legorooj This is the final installment of #4928 .
In the compat.py module I was careful not to use Python 3-specific syntax, since I'm not sure if it might run on Python 2. Also, I avoided test files.

Cleanup: Fix exception causes all over the codebase

---

PyInstaller/hooks/hook-scipy.stats._stats.py
news/4981.hooks.rst

Which is needed for scipy since 1.5.0 (scipy/scipy#11849) as
there is a hidden import of `scipy.special.cython_special`.

hooks: Add hook for scipy.stats._stats

---

PyInstaller/hooks/hook-cv2.py
news/4999.bugfix.rst

Failing to bundle this DLL may result in different behavior between original and distributed version when dealing with video files.
PyPI version seems to install the DLL into site-packages\cv2, while Conda installs it into prefix\Library\bin.

cv2: try to bundle opencv_videio_ffmpeg*.dll on Windows

---

PyInstaller/hooks/hook-gi.repository.GLib.py
news/5000.bugfix.rst

On Windows, GLib needs a spawn helper (gspawn-winXX-helper.exe and gspawn-winXX-helper-console.exe for non-console and console version, respectively) for g_spawn* API.
Failing to bundle this helper prevents GLib from launching external programs (e.g., opening a web browser when user clicks on a web-site link in a GtkAboutDialog).

GLib: bundle the spawn helper executables on Windows

---

PyInstaller/hooks/hook-PySide2.QtNetwork.py
news/4998.bugfix.rst

Under Windows, the PyPI version of PySide2 requires user to manually install SSL DLLs into the Lib\site-packages\PySide2 directory, which corresponds to the 'PrefixPath' in the pyside2_library_info.location.
Therefore, search for the DLLs in 'PrefixPath' in addition to the 'BinariesPath' (which is used by other versions, e.g., the one provided by Anaconda).

PySide2.QtNetwork: search for SSL DLLs in both PrefixPath and BinariesPath

---

PyInstaller/hooks/hook-packaging.py
PyInstaller/hooks/hook-pkg_resources.py
news/5044.hooks.rst

- Add yet more hidden imports to `pkg_resources` hook. 
- Mirror the `pkg_resources` hook for [packaging](https://packaging.pypa.io/en/latest/) which appears to be a mirror of `pkg_resources._vendor.packaging`. 
Fixes pyinstaller/pyinstaller-hooks-contrib#15 (although we can't reproduce that issue). 
I imagine there may be a cleaner way to mirror a hook - if there is I'll change it.

Add hidden imports to pkg resources

---

.github/workflows/validate-new-news.yml
scripts/verify-news-fragments.py

Add action to enforce our change-log format on pull requests. Fixes #5070.
The brain of the operation is the new script [scripts/verify-news-fragments.py](https://github.com/bwoodsend/pyinstaller/blob/verify-news-fragment-filenames/scripts/verify-news-fragments.py) which reads a `git diff` for new files, filters for new news fragments, then validates them.
This script is invoked by the new workflow [.github/workflows/validate-new-news.yml](https://github.com/bwoodsend/pyinstaller/blob/efcf1cdab3e324f1c2d638f499805826daa91ca5/.github/workflows/validate-new-news.yml) which is very similar to the lint action we already have. Provided the above script doesn't fin any issues, this action then calls `towncrier` to ensure that works too.
I created a [mock pull …

Add action for validation of new news fragments in pull requests

---

PyInstaller/depend/bindepend.py

```
6121 WARNING: Can not get binary dependencies for file: C:\Windows\System32\downlevel\api-ms-win-core-localization-l1-2-0.dll
6121 WARNING:   Reason: too many values to unpack (expected 2)
File "C:\Python37x86\lib\site-packages\PyInstaller\depend\bindepend.py", line 731, in getImports
return _getImports_pe(pth)
File "C:\Python37x86\lib\site-packages\PyInstaller\depend\bindepend.py", line 128, in _getImports_pe
dll, _ = forwarder.split('.')
ValueError: too many values to unpack (expected 2)
6145 WARNING: Can not get binary dependencies for file: C:\Windows\System32\downlevel\api-ms-win-core-memory-l1-1-0.dll
6149 WARNING:   Reason: too many values to unpack (expected 2)
File …
```

fix windows10 build 2004 error

---

doc/development/testing.rst

For issue #5108, changed py.test to pytest at
pyinstaller/doc/development/testing.rst. This is because
py.test is deprecated.

docs: replace deprecated py.test with pytest

---

PyInstaller/depend/imphook.py
PyInstaller/exceptions.py

Please see my attempt to close issue #4537. However when I run PyInstaller with my changes applied, the traceback is still outputted to the terminal instead of the exception message I have created and (tried to) implement.

hooks: failed hook outputs exception message

---

doc/bootloader-building.rst
news/5130.doc.rst

Include a couple of sentences in the building the bootloader section of the docs to say *building the bootoader requires `zlib-devel`*. Fixes #5101.
@simaoafonso-pwt Can you confirm that I have the correct `yum` command - I just pulled it off the web and can't verify it myself.

docs: Add zlib to build requirements.

---

README.rst

I believe this was overlooked in 9de3b4732f599a878e0b3da8470492beee1b1f19.
Python 3.8 support added in 96ad2961d578ce322f3ea80fc9e1fe5d657a1227

Doc: Add missing Python 3.8 reference

---

PyInstaller/hooks/hook-gi.repository.HarfBuzz.py
PyInstaller/hooks/pre_safe_import_module/hook-gi.repository.HarfBuzz.py
news/5133.hooks.rst

Fixes #5129. 
This PR fixes an error for `gi.RepositoryError: Typelib file for namespace 'HarfBuzz', version '0.0' not found`.
The cause of this error is that Gtk and Pango now include HarfBuzz-0.0 as a typelib that needs to be loaded with the other libraries. This change adds hooks for this typelib.

Hooks: Add hook-gi.repository.HarfBuzz

---

PyInstaller/utils/hooks/__init__.py
news/5141.hooks.rst

utils.hooks.collect_all() were collecting _pycache__, py.c and py.o files. This needed to stop because bytecode files were being kept after tests were run. Closes #5115.

hooks: Stopped hooks collecting bytecode files.

---

doc/usage.rst

A minor typo fix in the "Using Pyinstaller" chapter of the docs.

Doc: Correct typo in 'Supporting Multiple Python Environments' section

---

PyInstaller/hooks/hook-PyQt5.QtNetwork.py
PyInstaller/hooks/hook-PySide2.QtNetwork.py

Fix a typo in name of the last SSL DLL (removed trailing 'x'). The change is purely cosmetic; the DLL was picked up in spite of the typo, presumably due to being linked by the other DLL.

hooks: {PyQt5,PySide2}.QtNetwork: fix a typo in SSL DLL name

---

PyInstaller/depend/imphook.py

This amends the already merged PR #5077. See the commit message for the rational. I'm guessing this doesn't get a changelog entry because the original behaviour never made it to a release?

Fix logger calls with no positional arguments.

---

PyInstaller/hooks/hook-PySide2.QtWebEngineWidgets.py
news/5150.hooks.rst

Added `QtQmlModels` to the list of libraries for which .framework directory needs to be collected on macOS. Without it, `QWebEngineView` fails to load a page and spams console with messages about `QtQmlModels` library not being loaded.
The issue is currently masked by #5058, but once that is resolved, `test_PySide2_QWebEngine` will likely start failing with timeout on macOS, because failing to load the page will prevent the timer for exiting the test program from being triggered.

hooks: PySide2.QtWebEngineWidgets (macOS): collect QtQmlModels.framework

---

PyInstaller/hooks/hook-sqlalchemy.py
news/5128.hooks.rst

Closes #5106, added "sqlalchemy.ext.baked" to the hidden imports
list of sqlalchemy hook file hook-sqlalchemy.py. This is because it was
missing.

hooks: Add "sqlalchemy.ext.baked" to sqlalchemy hook.

---

PyInstaller/loader/pyiboot01_bootstrap.py
news/5182.core.rst

When loading a system dynamic library via `ctypes.CDLL()` in a frozen progam, a local directory in `sys._MEIPASS` with a clashing basename ends up preventing the library from being loaded.
To fix this, use `os.path.isdir()` in addition to `os.path.exists()` to decide whether to use frozen or original library name.
Fixes #5178.

loader: prevent local directory from shadowing system library

---

PyInstaller/hooks/hook-_tkinter.py
news/5013.hooks.rst

The python.org OS X python distributions installs a built-in version tcl/tk in a path similar to the system installation. This makes pyinstaller confused and think the python.org built-in tcl/tk is the system installation. This pull request fixes this issue. See https://github.com/pyinstaller/pyinstaller/issues/3753#issuecomment-432464838 .
Resolves #3753 .

Correctly locate macos python.org built-in tcl/tk

---

PyInstaller/depend/dylib.py
news/5172.core.rst

The older python.org builds that use system Tcl/Tk framework have their `_tkinter.cpython-*-darwin.so` library linked against `/Library/Frameworks/Tcl.framework/Versions/8.5/Tcl` and `/Library/Frameworks/Tk.framework/Versions/8.5/Tk`, although the actual frameworks are located in `/System/Library/Frameworks`.
Therefore, we fail to recognize these libraries as system ones, and rewrite their paths with relative ones. The resulting program fails to run due to missing libraries (as we do not bundle them).
To fix the issue, these two libraries need to be explicitly exempted from the path overwrite.

depend: exempt OSX system Tcl/Tk libs from relative path rewrite

---

tests/functional/test_basic.py

Removed the macOS-specific `LC_ALL=cs_CZ` in the test; on all OSes we now use `cs_CZ.UTF-8`. Using `LC_ALL=cs_CZ` causes error on macOS when running under python 3.8, whereas `cs_CZ.UTF-8` seems to work just fine with python 3.5 - 3.8.

tests: test_time_module_localized: use cs_CZ.UTF-8 on all OSes

---

PyInstaller/hooks/hook-PyQt5.QtWebEngineWidgets.py
PyInstaller/hooks/hook-PySide2.QtWebEngineWidgets.py
news/5149.hooks.rst

The glob used to search for extra NSS libraries on linux turns out to have no matches on Fedora 32. 
The `/lib64/nss` directory exists, but contains no libraries, and so adding `/lib64/nss/*.so` to `binaries` results in the following error:
```
Unable to find "/lib64/nss/*.so" when adding binary and data files.
```

hooks: {PyQt5,PySide2}.QtWebEngineWidgets (linux): prevent use of glob if it has no matches

---

bootloader/src/pyi_path.c
news/5189.bootloader.rst

Use `_wfullpath()` instead of `_fullpath()` in `pyi_path_fullpath` to allow non-ASCII characters in the path.
Fixes #5184.

bootloader: pyi_path_fullpath: use _wfullpath()

---

PyInstaller/hooks/hook-PyQt5.QtWebEngineWidgets.py
PyInstaller/hooks/hook-PyQt5.py
PyInstaller/hooks/hook-PySide2.QtWebEngineWidgets.py
PyInstaller/hooks/hook-PySide2.py
PyInstaller/utils/hooks/__init__.py
PyInstaller/utils/hooks/gi.py
news/5110.hooks.rst

Fixes #5058 by removing the jump to the parent directory in `collect_system_data_files`. 
This changes the returned paths to the collected files - the paths are not prefixed by the last component of the input search path anymore. Therefore all hooks using `collect_system_data_files` need to be adjusted in order to avoid misplacing the files in the dist directory.

Fix for #5058: collect_system_data_files() scans parent

---

PyInstaller/hooks/hook-gevent.py
PyInstaller/utils/hooks/__init__.py
news/5113.hooks.rst
news/5201.hooks.rst

utils.hooks.collect_all() now contains an `exclude_datas` parameter
that is passed to util.hooks.collect_data_files(). This means that
when calling utils.hooks.collect_all() the caller can exclude
datafiles they select. Fixes #5113

hooks: Add `exclude_datas` to utils.hooks.collect_all().

---

doc/_common_definitions.txt
doc/runtime-information.rst

I also threw in a little section to say that *if you can put the data files where they're expected to be then you can avoid this altogether*.

Doc: add pathlib example for finding data files at runtime

---

doc/spec-files.rst

The relevant issue https://github.com/pyinstaller/pyinstaller/issues/1441 which will maybe provide a fix in the future is linked.

Add a warning in the docs that the -u option does not work on Windows.

---

PyInstaller/hooks/hook-_tkinter.py
news/5175.hooks.rst

This is (hopefully) the last fix in the current series of attempts to sort out the `tkinter` and `Tcl/Tk` issues on OSX. It comes after #5013 and #5172, and addresses an issue with .app bundles. After this, I can get simple tkinter applications running in both `onedir` and `.app bundle` mode, with both python that uses system Tcl/Tk (3.6.5) and the one that uses its own Tcl/Tk (3.7.6).
-----
The Tcl modules directory is separate from the data/library one, and is typically located at `tcl_root/../tclX`, where `tcl_root` is the Tcl data/library directory and `X` is the Tcl major version.
In most (simple?) cases, failing to collect this directory does not seem to cause any issues. One notable exception are .app  bundles on OSX, which "open and close immediately" due to the following …

hooks: tkinter: collect Tcl modules directory

---

tests/functional/test_apple_events.py

Fix this error on Python 3.5:
```
test_osx_custom_protocol_handler failed (1 runs remaining out of 2).
<class 'TypeError'>
join() argument must be str or bytes, not 'LocalPath'
[<TracebackEntry /Users/runner/work/pyinstaller/pyinstaller/tests/functional/test_apple_events.py:30>, 
```
I kept the change very simple to ease its deletion when 3.5 will be out of support.

Tests: Fix test_osx_custom_protocol_handler() on Python 3.5

---

PyInstaller/hooks/hook-_tkinter.py
PyInstaller/hooks/rthooks/pyi_rth__tkinter.py
news/5217.hooks.rst

After a discussion with @bwoodsend, we reached conclusion that in the case of system Tcl/Tk framework on macOS, it makes no sense to collect data when we do not collect the shared library (which we do not; and is not needed anymore as #5172 ensures that the system libraries are used correctly). So this PR removes the collection of data from macOS' system Tcl/Tk. This affects only python builds that use system Tcl/Tk - older python.org builds (e.g., 32/64-bit 3.6.5) and apparently homebrew python.
As a bonus, this also takes care of the error in `tkinter` hook with homebrew python on macOS 11, which was reported in #5040.
-----
On macOS, we do not collect system libraries in general; if `tkinter` uses system Tcl/Tk 8.5 framework (older 32/64-bit
python.org builds, or brew python), we do …

 hooks: tkinter: avoid collecting data from system Tcl/Tk framework on macOS

---

PyInstaller/hooks/hook-_tkinter.py
news/5222.hooks.rst

The `_handle_broken_tcl_tk()` work-around appears to have been added for python2 `virtualenv` under Windows. It does not seem to be necessary under Windows python3 `venv`/`virtualenv` anymore, and it causes error under MSYS2/MINGW64 python3 `venv`.

hooks: tkinter: remove _handle_broken_tcl_tk() and its use

---

PyInstaller/hooks/hook-gevent.py
news/4857.hooks.rst

hook-gevent.py now passes False to the include_py_files argument and
["**/tests"] to the exclude_datas argument of collect_all() when
calling it.  This means that hook-gevent.py no longer bundles
__pycache__ folders, .c, .h files, tests nor HTML documentation.
Fixes #4857.

hooks: hook-gevent no longer bundles unnecessary files.

---

PyInstaller/building/api.py
news/4693.build.rst

AppImage builds were broken since the commit 392aba1.
The original behavior is now restored and more specific, it will hopefully introduce no regression on the MSYS2 side.
Fixes #4693.

build: Fix AppImage builds.

---

PyInstaller/building/osx.py
news/3550.build.rst

Move the `base_library.zip` file to the `Resources` folder of the app and link it to the `MacOS` folder.
Fixes #3550.
Fixes #5112.

build: OSX: Improve codesigning and notarization robustness.

---

PyInstaller/hooks/rthooks/pyi_rth_pyqt5webengine.py
news/5183.hooks.rst

The jump from `sys._MEIPASS` to `../MacOS` when setting `QTWEBENGINEPROCESS_PATH` in the PyQt5 QWebEngine rthook causes a `Could not find QtWebEngineProcess` error in a program built in `onedir` mode.
This is because when running a program, e.g., `./dist/program/program`, the `sys._MEIPASS` is `dist/program`, and due to the jump, the `QTWEBENGINEPROCESS_PATH` incorrectly becomes `dist/MacOS/PyQt5/...` instead of `dist/program/PyQt5/...`.
The .app bundle works correctly, because its `sys._MEIPASS` becomes `dist/program.app/Contents/MacOS`, so the jump effectively comes back to the original directory.
This commit removes the `../MacOS` jump, so that `QTWEBENGINEPROCESS_PATH` contains correct path for both `onedir`
and `.app` bundle builds. The path is now set in the same manner as in the …

hooks: PyQt5.QtWebEngineWidgets: fix QTWEBENGINEPROCESS_PATH on OSX

---

PyInstaller/depend/dylib.py

These usually come with the graphical stack,
including them may cause unexpected issues.
First regex picks up everything that comes out of `libglvnd`
(https://github.com/NVIDIA/libglvnd,
https://packages.ubuntu.com/source/focal/libglvnd),
a total of 7 libraries.
The second one is for DRM Linux kernel interface library.
Partially-fixes: #4951
P.S. Please note that I do not have a deep understanding of the graphical stack, this is my best effort.

depends: Exclude more unix/Linux graphical interface libraries

---

PyInstaller/utils/hooks/__init__.py
news/5244.hooks.rst
tests/unit/hookutils_files2/foo/bar/__init__.py
tests/unit/test_hookutils.py

Prevent the extra output to stdout during module import from showing up in the modules list collected by `collect_submodules()`.
The package-walking process now encloses the output module names with special prefix and suffix, which allows us to discard extra lines.
This fixes the issue with parts of error messages ending up in the hidden imports (and consequently in warnings about these
spurious modules not being found), as reported in #4813.
The PR also adds a new test, `test_collect_submod_stdout_interference` for testing the effect of extra output to stdout during module import process on the collected submodules list.

 hookutils: robustify the collect_submodules() function

---

bootloader/src/pyi_path.c

Fixes #5257
Fixed path resolution of the archive, for the case the archive is not directory not listed in `PATH` environment variable.
Error message caused by this issue looked like:
"Cannot open self /some_path/appname or archive /some_path/appname.pkg"

bootloader: On Unix fix path lookup of archive

---

PyInstaller/compat.py
PyInstaller/depend/analysis.py
PyInstaller/lib/modulegraph/modulegraph.py
news/5157.bugfix.rst
news/5157.core.rst
tests/functional/test_regression.py
tests/unit/test_building_utils.py
tests/unit/test_modulegraph/test_modulegraph.py
tests/unit/test_modulegraph_more.py

modulegraph's heritage includes code still based on Python 2.x capabilities on
how to find a module and get its source or code. It also contained a anomaly
regarding packages and their ``__init__``-file: If a package was detected,
it's ``__init__`` file was loaded as a module. This, while being ugly, worked
in most cases, but failed if the ``__init__`` module is an extension
module (see #5131, #4346), ending in an infinite loop. This was caused by
modulegraph distinguishing between the package and its ``__init__`` module.
The solution is to switch to "modern" loaders, both being a loader for a
specific type of modules (source, extension, etc.) and having a package
characteristic (property ``is_package()``)
This commit does the following
- In ``_find_module_path()`` no longer return …

modulegraph: Use loaders to get module content. 

---

bootloader/src/pyi_utils.c
news/5255.bootloader.rst

If the temp path is removed during application runtime (by a /tmp
cleaning script for example), the application will segfault on exit due
to calling readdir on a NULL pointer. Fix this issue by returning
immediately if the opendir fails.

Avoid segfault when temp path is missing

---

bootloader/src/pyi_path.c
news/5212.bootloader.rst

Replace a `strncpy()` call in `pyi_path_dirname()` with `snprintf()` to ensure that the resulting string is always null-terminated.
Fixes potential issue that is detected and warned against by newer versions of `gcc`, e.g. `gcc` 10 on Fedora 32:
```
In file included from /usr/include/string.h:495,
from ../../src/pyi_path.c:37:
In function ‘strncpy’,
inlined from ‘pyi_path_dirname’ at ../../src/pyi_path.c:86:5,
inlined from ‘pyi_path_fullpath_keep_basename’ at ../../src/pyi_path.c:174:5:
/usr/include/bits/string_fortified.h:106:10: error: ‘__builtin_strncpy’ specified bound 4096 equals destination size [-Werror=stringop-truncation]
106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
|          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: …
```

bootloader: replace strncpy() with snprintf()

---

README.rst
bootloader/wscript
news/4627.bootloader.rst
news/4886.bootloader.rst

This will fix recent PyQt versions with the dark mode handling.
Note that bootloaders will need to be compiled against XCode 11 or newer to completely fix the linked issue.
Fixes #4627.
Fixes #4886.

Bootloader: (OSX) Bump MACOSX_DEPLOYMENT_TARGET from 10.7 to 10.13.

---

bootloader/src/pyi_utils.c
news/5276.bootloader.rst
tests/functional/scripts/pyi_pyqt5_log_events.py
tests/functional/specs/pyi_osx_event_forwarding.spec
tests/functional/test_apple_events.py

This is a resurrection of #3832 . 
It expands the already-existing "argv-emu" facility provided by the bootloader for macOS by adding additional capabilities to the bootloader.  To recap what the bootloader already could do previous to this PR:
- If a user drags/drops files onto the app icon in the GUI or clicks on a URL associated with the app, **and if the app was not already-running**, the bootloader was able to deal with this situation.
- The bootloader would, as part of the startup process, check the AppleEvents queue and translate all 'open doc' and 'open url' events into args that the subordinate program receives (as `sys.argv` in Python).
- **However**, once the app was started, clicking on URLs or dragging files to the app icon would *not* do anything.  This is because the …

OSX: Add capability for already-running apps to accept URL & drag'n drop events via Apple Event forwarding

---

tests/functional/test_libraries.py
tests/requirements-libraries.txt

Pillow tests were breaking after update to version 8.0.0. This required changing the  /tests/functional/test_libraries.py to import "frombytes" instead of "fromstring" in test_pil_plugins . This makes it compatible with PIL 8.0.0 as well as earlier PIL. Also, the changeset from an earlier commit was applied to requirements-libraries.txt to implement Pillow support based on Python version.

Tests/functional: Pillow test fixed and requirements updated for PIL 8.0.0

---

PyInstaller/utils/hooks/__init__.py
news/5300.hooks.rst

`*args` being placed after the `env` keyword argument means that the first argument intended to be passed to the script will actually end up overriding the `env`.

hookutils: fix argument order in `exec_script()` and `eval_script()`

---

PyInstaller/hooks/hook-django.py
PyInstaller/utils/hooks/django.py
PyInstaller/utils/hooks/subproc/django_import_finder.py
news/5267.hooks.rst

fixes https://github.com/pyinstaller/pyinstaller/issues/4830
Changes:
- settings - default or overriden by env variable `DJANGO_SETTINGS_MODULE`
- `find_url_callbacks` in `django_import_finder.py` was removed - has no impact in case of compiling my app, don't know whether it is needed in django 2.2+ and what problem it resolved
- ~~all files from directory are excluded (`datas += collect_data_files(package_name, excludes=os.listdir())`) - due to changed behavior of collect_data_files. Without this, I got all data copied into the result project (including development files, `.git` folder, etc.)~~ reverted after review
@Legorooj

hooks: django multiple settings hook fix

---

bootloader/tests/test_path.c
bootloader/tests/wscript
news/5318.bootloader.rst

Fix compilation of bootloader tests when compiling under Windows with Visual Studio and `cmocka` is available. Attempting to build the bootloader itself in such an environment would fail due to tests failing to build, as reported in #5314.
Fix the `test_path` battery of tests for Windows compatibility, by using `PYI_SEPSTR` and string concatenation instead of full-path string literals.
The remaining failing tests are the ones that check for behavior with paths larger than `PATH_MAX`, which trigger a bug that is caused by our use of `_snprintf()` as `snprintf()` replacement under MSC.
Fixes #5314.

bootloader: fix bootloader tests under Windows/MSC

---

bootloader/src/pyi_main.c
bootloader/src/pyi_path.c
news/5232.bootloader.rst

This is a proof-of-concept fix for #4674, #4693, and #5179. It effectively reverts ebcd49c to bring back full executable name resolution via `readlink()` on the corresponding `/proc` entry - failing to do so seems to be the cause of #4674 and #4693. The second part of PR addresses the process name issue by using `prctl()` and an environment variable to pass the process name from parent to child launcher process.
With the modified bootloader, the existing `test_symlink_basename_is_kept` tests keep passing, and the `test_appimage_loading` added by #5229 also passes now.

bootloader: on linux, fully resolve the executable name while preserving process name

---

.github/workflows/macos.yml
tests/functional/test_apple_events.py

Based on the macOS CI failures I've seen recently, this PR:
* disables `fail-fast` strategy to allow all workflows to finish. This in turn allows us to see whether the failing test is affecting all python versions or not.
* increases the delay/wait time in `test_osx_custom_protocol_handler` in an attempt to prevent random failures on the CI. The situation w.r.t. this test has improved since the tests have been marked as flaky, but the occasional failure is still there...

Improvements for macOS CI

---

tests/old_suite/test-requirements.txt

`uuid` is an unlicensed [package](https://pypi.org/project/uuid/) making it incompatible with closed source projects. It seems that the python build-in [uuid](https://docs.python.org/3/library/uuid.html) exists on 2.7 and 3.5+. Furthermore, this package doesn't seem to be used anymore.

Remove uuid from old requirements as it is unlicensed

---

PyInstaller/loader/pyimod03_importers.py
news/5346.moduleloader.rst

Remove `find_module()` and `load_module()` from `FrozenImporter`. As per comments in these two methods, they are deprecated since python 3.4 in favor of PEP-451 loader.
Also remove the `FrozenPackageImporter` class which was used only from `FrozenImporter.load_module()`.

loader: remove deprecated PEP-302 functionality from FrozenImporter

---

bootloader/src/pyi_archive.c
bootloader/src/pyi_archive.h
bootloader/src/pyi_global.c
bootloader/src/pyi_global.h
bootloader/src/pyi_launch.c
bootloader/src/pyi_main.c
bootloader/src/pyi_path.c
bootloader/src/pyi_pythonlib.c
bootloader/src/pyi_utils.c
bootloader/src/pyi_win32_utils.c
bootloader/tests/test_path.c
bootloader/wscript
doc/bootloader-building.rst
news/5320.bootloader.rst

This PR contains the following fixes and improvements for building with MSC (Visual Studio):
* remove the use of `_snprintf()` and `_vsnprintf()` as aliases for `snprintf()` and `vsnprintf()`. Visual Studio 2015 and later provide implementation of `snprintf()` and `vnsprintf()`, so use that instead. This implicitly assumes that VS2015 is minimum required version for building the bootloader, which I think is reasonable.
This fixes the bug that was revealed by bootloader's test suite - on overflow, `_snprintf()` does null-terminate the string, and returns -1 instead of number of characters that would be written. This affects our path-manipulation functions that make use of this function.
* drop the macro-based mapping of MSC-compatible function names to their POSIX equivalents. Instead, use …

bootloader: assorted fixes and cleanup for building with MSC

---

PyInstaller/utils/hooks/__init__.py
news/5301.hooks.rst

Implement `exec_statement_rc()` and `exec_script_rc()` as counterparts of `exec_statement()` and `exec_script()` that return the exit code instead of stdout. 
Implement `can_import_module()` helper (using `exec_statement_rc()`) that allows a quiet check for module availability (i.e., without printing the `ModuleNotFoundError` traceback to stderr if module is unavailable).

hookutils: implement `exec_{statement,script}_rc()` and `can_import_module()` helper

---

PyInstaller/hooks/hook-win32ctypes.core.py
news/5250.hooks.rst
tests/functional/test_libraries.py

We need a hook to collect all submodules from `win32ctypes.core.cffi` or `win32ctypes.core.ctypes` (depending on availability of `cffi`) to avoid missing module errors when using `win32ctypes` pywin32 compatibility layer.

 hooks: add a hook for win32ctypes.core

---

PyInstaller/building/utils.py
PyInstaller/utils/win32/versioninfo.py
news/5382.core.rst

Compressing a DLL that has Control Flow Guard (CFG) enabled with UPX renders it unusable. The most common example of this is the `vcruntime140.dll`, but there could be others. So instead of having users to manually exclude such DLLs, we try to identify and skip them automatically.

building: avoid using UPX with Windows DLLs that have CFG enabled

---

PyInstaller/archive/writers.py
news/5380.core.rst

This makes the .pyc modules in the PKG archive invariant to the build-environment location, and in turn enables reproducible
builds without having to match the location of the build environment.
Fixes #5377.

archive: CArchiveWriter: strip the path from .pyc modules

---

PyInstaller/hooks/hook-gi.repository.GtkosxApplication.py
PyInstaller/hooks/pre_safe_import_module/hook-gi.repository.GtkosxApplication.py
news/5385.hooks.rst

Signed-off-by: Dan Yeaw <dan@yeaw.me>
This PR fixes issues when importing GtkosxApplication for use with GTK apps in macOS. For example, I was getting the following TypeError:
```
TypeError: <GtkosxApplication.Application object at 0x112573bc0 (GError at 0x7fa8061d7420)>: unknown signal name: NSApplicationOpenFile
```

Hooks: Add hook-gi.repository.GtkosxApplication

---

PyInstaller/building/build_main.py
news/5383.core.rst

The `.pyo` file suffix is gone since python 3.5 (PEP-488), and using it when storing bytecode-optimized module files outside the PYZ archive (i.e., `noarchive` mode) will lead to module-not-found errors.
The PEP-488 replaced the .pyo suffix with `.opt-1.pyc` and `.opt-2.pyc`, but for bytecode-only module distribution, it seems that we need to use the plain `.pyc` - same as for non-optimized case.

building: avoid using .pyo module suffix in noarchive mode

---

PyInstaller/archive/writers.py
PyInstaller/lib/modulegraph/modulegraph.py
PyInstaller/loader/pyimod02_archive.py
PyInstaller/loader/pyimod03_importers.py
news/5354.core.rst
tests/functional/test_import.py

In PEP-420 namespace packages, the `__file__` attribute should be either unset (python 3.6 and earlier) or set to None (python 3.7 and later). This results in a different `repr()`, i.e.
```
<module 'package' (namespace)>
```
instead of
```
<module 'package' from '[...]/package/__init__.pyc'>
```
This PR adds tests and implements support for proper behavior and distinction between PEP-420 and non-PEP-420 namespace packages.
In the `modulegraph`, the `NamespacePackage` node is now used only for PEP-420 namespace packages, and their identification is now based on the loader type. This fixes #5338, which is caused by a spurious namespace declaration that shadows the actual package.

Improve support for PEP-420 namespace packages

---

PyInstaller/loader/pyimod03_importers.py
news/5396.bugfix.rst

Returning empty list for `submodule_search_locations` for frozen packages seems to break `importlib_resources` from `3.2.0` on (used by older python versions that don't have standard `importlib`).
Fixes #5395.

 loader: ensure that packages have submodule_search_locations set

---

PyInstaller/hooks/hook-keyring.py
news/5245.hooks.rst
tests/functional/test_libraries.py

Update `keyring` hook for compatibility with recent versions of `keyring` work. Tested on linux, Windows and macOS.
Fixes #4569.

hooks: update keyring hook

---

PyInstaller/utils/win32/winmanifest.py
news/5403.bugfix.rst
tests/unit/test_winmanifest.py

This pull request fixes a Python 3 incompatibility still lurking in the code.

utils\win32: Fix reading manifest from PE files.

---

PyInstaller/building/api.py
PyInstaller/building/makespec.py
PyInstaller/building/utils.py
PyInstaller/utils/win32/icon.py
appveyor.yml
bootloader/Vagrantfile
bootloader/windows/run.rc
bootloader/windows/runw.rc
news/2995.bugfix.rst
news/4700.feature.rst
news/870.bugfix.rst

Fixed default icons still being present in the executable after setting a custom icon.
Added --icon=NONE functionality, so that the OS default icon for the file type will be used.
Closes #870 and #2995 (possibly)

Fix default icons still being present in the executable

---

bootloader/src/pyi_utils.c
news/3301.bugfix.rst
news/4579.bugfix.rst
news/4720.bugfix.rst

As background, the --runtime-tmpdir option was failing to extract bundled executables to the specified location.  Usually, they would end up in simply the root directory of the drive (e.g. `C:\` even though `C:\something_else` was specified).  As a result, this option was useless for users who needed it extracted elsewhere besides %TEMP%, as contents in the temporary folder are subject to deletion at any given moment (see relevant issues below).  This is a major problem for long running applications and Window services/daemons, who would find their files in `_MEIPASS` deleted after a week or so (e.g. in my case, `cacert.pem` was being deleted, causing TLS issues).
The problem was that the --runtime-tmpdir option did not resolve environment variables, nor did it create directories as …

Fix --runtime-tmpdir and deletion of temporary files

---

PyInstaller/utils/conftest.py
tests/functional/test_hooks/test_six.py

Fix the test skip message due to unsupported platform - currently, running the test suite on linux produces `runs only on linux` skip messages for Windows-only test.
Add `@importorskip` decorators to `test_six_moves˙ and `test_six_moves_2nd_run` to prevent test failures when `six` is not installed.

Couple of fixes for test suite

---

PyInstaller/utils/win32/winmanifest.py
news/5424.feature.rst

Enables long paths on Windows 10 v.1607 and later.
Fixes #5423.

winmanifest: enable longPathAware option in application's manifest

---

PyInstaller/hooks/hook-PyQt5.QtNetwork.py
PyInstaller/hooks/hook-PyQt5.QtQml.py
PyInstaller/hooks/hook-PyQt5.QtWebEngineWidgets.py
PyInstaller/hooks/hook-PyQt5.py
PyInstaller/hooks/hook-PySide2.QtNetwork.py
PyInstaller/hooks/hook-PySide2.QtQml.py
PyInstaller/hooks/hook-PySide2.QtWebEngineWidgets.py
PyInstaller/hooks/hook-PySide2.py
news/5425.hooks.rst

Replace the truthyness check of `{pyside2,pyqt5}_library_info.version` with explicit not-`None` check. The check is meant to ensure that the library is importable, however, the version information is not available in older Qt5 versions (`QLibraryInfo::version()` was added in Qt 5.8).
Therefore, an empty version array indicates that the library is available, but is too old to have the version information exposed. The library failing to import, however, should result in corresponding `library_info` structure to have version set to `None`.
Fixes #5381.

hooks: PySide2/PyQt5: fix the availability check for older Qt5 versions

---

bootloader/src/pyi_win32_utils.c
news/5216.bootloader.rst

Retrieve and use current user's SID instead of using S-1-3-4, which is unsupported by wine. Fixes #4628.
----
This is a possible work-around on our side to address #4628. Instead of creating directory with permissions specified under SID "S-1-3-4" (which is unsupported by wine), we look up and use the user's SID.

bootloader: on Windows, use user's SID to create directories

---

PyInstaller/hooks/hook-gi.repository.GdkPixbuf.py
PyInstaller/hooks/rthooks/pyi_rth_gdkpixbuf.py
news/5435.hooks.rst

Fixes #5422.
GdkPixbufLoader is by default stored in a `lib/gdk-pixbuf-2.0/2.10.0/loaders` directory and the current GdkPixbuf hooks package it in the same directory structure. When trying to code
sign a macOS app, Apple treats directories in `Contents/MacOS/` with a period in the name as a bundle and causes the code signing to fail. This change moves this library to `lib/gdk-pixbuf/loaders`.

Hooks: Fix unable to code sign macOS GTK app

---

PyInstaller/hooks/hook-scipy.spatial.transform.rotation.py
news/5456.hooks.rst

As of `scipy` 1.6.0, `scipy.spatial.transform.rotation` is cython compiled, so we fail to automatically pick up its imports. Therefore, `scipy.spatial.transform._rotation_groups` needs to be added to hidden imports.
Fixes #5440.
Fixes #5454.

hooks: add hook for scipy.spatial.transform.rotation

---

PyInstaller/utils/hooks/__init__.py
news/5426.hooks.rst

Fix the scenario where a single failed subpackage import during a package inspection by `collect_submodules()` prevents the remainder of the package from being inspected/collected.
Instead of re-raising the exception and aborting the package-walking, we now print a message to `stderr` and continue, in an attempt to salvage the situation based on the following rationale: if the problematic sub-package is required by the program, then the unfrozen version would have hit the same problem (and there's nothing we can do about it). On the other hand, if the problematic sub-package is not required by the program, we now properly collect all other sub-packages and allow the program to work, as opposed to breaking it by not collecting the remaining sub-packages at all.

hookutils: collect_submodules: limit the impact of a failed subpackage import

---

PyInstaller/utils/misc.py
PyInstaller/utils/win32/versioninfo.py
news/5445.bugfix.rst
tests/unit/test_miscutils.py

This fixes "toc is bad" error messages if a VSVersionInfo is passed as 
the version parameter of the EXE function, which leads to spurious rebuids.

utils/win32: Fix serializing VSVersionInfo.

---

PyInstaller/building/utils.py
PyInstaller/depend/dylib.py
news/5062.bugfix.rst
news/5272.bugfix.rst
news/5434.bugfix.rst
news/5451.feature.rst

Recent version of python on macOS have their `Python` shared library signed due to Gatekeeper requirements. Due to partial collection of content from the `Python.framework`, the copy of Python shared library that we bundle with frozen application ends up with its signature invalidated, and refuses to load regardless of Gatekeeper settings.
Manually stripping the (now invalid) signature using `codesign --remove-signature` fixes the problem, but can be performed
only with `onedir` builds. Therefore, we now attempt to detect the signature and automatically strip it away in order to accomodate
both `onefile` and `onedir` builds.
Fixes #5062.
Fixes #5272.
Fixes #5434.

building: macOS: strip the signature off the collected Python shared library

---

PyInstaller/compat.py
PyInstaller/utils/hooks/__init__.py
PyInstaller/utils/hooks/conda.py
doc/_common_definitions.txt
doc/conf.py
doc/hooks.rst
news/5213.feature.rst
news/5213.hooks.rst
requirements.txt
setup.cfg

I explain more fully in the commit message but this PR adds a new `conda_support` submodule to `PyInstaller.utils.hooks` which parses some metadata jsons stored inside a Conda installation. These jsons are like the Conda package equivalent of a `MANIFEST.in` in that it lists all the files belonging to a particular package. This will hopefully replace our disastrous attempts to find DLLs for packages such as numpy which Conda has heavily altered.
This is still very much a draft so no need to review it in full yet. But I'd like everyone's thoughts on some of the concepts. Namely:
- Should this be only a hook utility? Or should we try to integrate it into PyInstaller's analysis by default?
- Currently I've put all the API into its own module which can only be accessed if in a Conda …

Hooks: Use Conda's metadata files to identify binary dependencies.

---

bootloader/src/pyi_launch.c
bootloader/src/pyi_python.c
bootloader/src/pyi_python.h
news/5446.bugfix.rst

The `windowed`+`debug` variant of the bootloader on Windows (`runw_d.exe`) [has the ability to display information about the uncaught exception that terminated the program execution](https://github.com/pyinstaller/pyinstaller/blob/b4ad0b0d905163cca42415d09ab32996a07ea5e7/bootloader/src/pyi_launch.c#L425-L469). I.e., after the `Failed to execute script <name>` dialog, it shows dialogs with `Error: <message>` and `Traceback: <traceback>`.
Unfortunately, at the moment, the extra dialogs always show `Error: NULL` and `Traceback: NULL`. This is because as per [docs](https://docs.python.org/3.9/c-api/exceptions.html#c.PyErr_PrintEx), the preceding `PyErr_Print()` call clears the error information, so `PyErr_Fetch()` comes up empty.
Therefore, we need to rearrange the calls so that exception …

bootloader: retrieve failed script error details before they are cleared

---

doc/spec-files.rst
news/5476.doc.rst

The version option for the spec file macOS bundle was not documented. This PR updates the docs to include this option.

Doc: Add version spec file option for macOS Bundle

---

PyInstaller/depend/bindepend.py
news/5107.bugfix.rst

Starting with macOS Big Sur, the system libraries are hidden. This results in a slew of error messages about missing libraries when
a shared library is scanned for imports. However, all these error messages are harmless, because we avoid collecting system libraries on macOS, nor do we need to further analyze them for dependencies (as they can depend only on other system libraries). Therefore, suppress the missing-library error messages for system libraries.
Closes #5107.

bindepend: suppress missing library messages for macOS system libraries

---

.github/workflows/macos.yml
.travis.yml
PyInstaller/compat.py
README.rst
appveyor.yml
doc/hooks.rst
doc/index.rst
doc/man/pyinstaller.rst
doc/usage.rst
doc/when-things-go-wrong.rst
news/5439.core.rst
requirements.txt
setup.cfg
tests/functional/scripts/pyi_getfilesystemencoding.py
tests/functional/test_apple_events.py
tests/functional/test_django.py
tests/functional/test_linux_appimage.py
tests/requirements-libraries.txt

* drop 3.5 from the CI matrices
* bump the check in compat.py so PyInstaller no longer runs on 3.5
* Remove/update most python 3.5 references in the docs
* update requirements.txt so that 3.5-specific dependencies are removed
* update setup.cfg so that PyInstaller won't install on python 3.5
* update the readme

breaking: drop python 3.5 support

---

PyInstaller/hooks/hook-gi.repository.GtkosxApplication.py
news/5475.hooks.rst

This PR updates the hook to import the correct typelib instead of HarfBuzz.
Also puts a guard in place to only use the hook when in macOS to prevent a traceback caused by an import error in Linux and Windows:
```
10786 INFO: Loading module hook 'hook-gi.repository.GtkosxApplication.py' from '/home/dan/Projects/gaphor/packaging/hooks'...
File "<string>", line 7, in <module>
gi.repository.GLib.Error: g-irepository-error-quark: Typelib file for namespace 'GtkosxApplication', version '1.0' not found (0)
```

Hooks: Import correct typelib for GtkosxApplication

---

bootloader/src/pyi_launch.c
news/5480.bugfix.rst
tests/unit/test_systemexit.py

Keep the bootloader's return code consistent with that of python interpreter, which returns 1 if it exits due to exception in the python script.
Fixes #5480.

bootloader: return 1 if frozen python script exits due to exception

---

PyInstaller/loader/pyimod03_importers.py
news/4213.bugfix.rst

The `FrozenImporter` in `pymod03_importers` uses `trace()` function if `sys.flags.verbose` is enabled to trace the imports to `sys.stderr`. This results in the following error:
`Failed to execute script pyiboot01_bootstrap`
when `sys.stderr` is unavailable (is `None`), which happens on Windows when windowed bootloader is used in combination with
`sys.flags.verbose` enabled (i.e., `--debug imports` or `--debug all` is passed on the command-line).
The problem is that while `pyiboot01_bootstrap` does install its `NullWriter` for `sys.stderr` when the latter is unavailable, that
happens too late; there is an `import os` that happens between the end of bootstrap process (the `pyimod03_importers.install()` call) and monkey-patching `NullWriter()` into `sys.stderr`.
While the problem could also …

loader: disable import tracing if sys.stderr is unavailable

---

PyInstaller/configure.py
news/5537.bugfix.rst

I recently used pyinstaller on Windows and later noticed that there were about 200MB of files syncing into my corporate Roaming Profile.
I think that the default cache directory should not be in the Roaming profile (`%APPDATA%` i.e. `C:\Users\<UserName>\AppData\Roaming\pyinstaller`) but much rather in the Local profile (`%LOCALAPPDATA%` i.e. `C:\Users\<UserName>\AppData\Local\pyinstaller`) by default, since there is no need to synchronize them between computers.
I know that I can change the behavior by setting the `PYINSTALLER_CONFIG_DIR` or disable syncing that folder, but I think that it would be better to adhere to Microsofts recommendation in terms of what to use the Roaming profile for. Also please note that this is of course opinionated/controversial as there is a lot of other …

Changed the default cache directory on Windows.

---

setup.cfg

Using `--ignore` completely overrides the ignore list, while `--extend-ignore` (introduced in `flake8` v.3.6) extends the default settings.
Overriding the built-in defaults seems to enable both `W503` and `W504`, which are impossible to satisfy at the same time.

tests/ci: use flake8 --extend-ignore instead of --ignore

---

bootloader/src/pyi_archive.c
bootloader/src/pyi_global.h
bootloader/src/pyi_launch.c
bootloader/src/pyi_python.c
bootloader/src/pyi_pythonlib.c
bootloader/tests/wscript
bootloader/wscript

This PR places the endianess conversion for multi-byte integer fields in COOKIE and TOC structures in a single place, i.e., after the data is read from the file (as opposed to performing it on every field access). The main motivation is to simplify the eventual transition from 32-bit integers to 64-bit ones to increase maximum archive file size.
On Windows, replace the use of `ntohl()` from `ws2_32` library with compiler-provided byte-swap functions. This allows us to drop otherwise unneccessary dependency on `ws2_32` in bootloader executables.

bootloader: clean up endianess conversion

---

PyInstaller/depend/utils.py
news/5563.bugfix.rst

Strip paths from modules collected into `base_library.zip`, to enable reproducible builds regardless of python's install location.
Fixes #5563.

depend/utils: strip paths from modules collected into base_library.zip

---

PyInstaller/archive/readers.py
PyInstaller/utils/cliutils/archive_viewer.py
news/2372.bugfix.rst
news/5554.bugfix.rst

Implement full back-to-front file scan for the `MAGIC` pattern in the `CArchive` reader, as per discussion in #2372. This allows `archive_viewer` to find embedded package in binaries with additional appended data (e.g., digital signature). This also synchronizes the pattern search behavior in python-side `CArchive` implementation with bootloader-side changes proposed in #5511.
Fixes #2372.
The second commit fixes an assertion-related crash in `archive_viewer` that was uncovered during testing, and occurs when quitting the application or moving up a level.

archive_viewer: implement full front-to-back file scan & fix crash on exit

---

PyInstaller/building/api.py
PyInstaller/utils/win32/winutils.py
bootloader/wscript
news/5579.feature.rst
tests/functional/test_basic.py

#5579 explains the what/why for this PR well.
Windows executables contain an optional checksum to protect against corruption. It turns out that several of antiviral programs
raise false positives if this checksum is missing or wrong. Setting this checksum appeases McAfee and inconsistently fixes
MS Defender which are probably the most common (and also dumbest) AVs for Windows. 
Sod's law says that in a few months the AV programs will notice that we've rumbled their *I am not a virus* metadata tag and come up with something even less effective to waste our time with but in the meantime we get to enjoy a little ironical break from the constant false-positive reports.
This PR sets the checksum for built executables. We probably should apply this directly to the bootloaders too but I can't do …

Building: Windows: Set EXE checksums (#5579).

---

PyInstaller/hooks/hook-matplotlib.py
news/5568.bugfix.rst

Fixes #5567. The bigger question is if this breaks earlier versions of matplotlib and how to deal with that if so.

Use public get_data_path for matplotlib hook

---

bootloader/src/pyi_archive.c
news/5551.bootloader.rst

Perform file extraction and decompression in a streaming manner, using small data chunks (8 KiB) in order to reduce the memory footprint while unpacking a onefile build containing large data files.

bootloader: archive: implement chunked i/o for file extraction

---

bootloader/src/pyi_archive.c
news/5330.bugfix.rst
news/5511.bootloader.rst

Implement full back-to-front file scan for finding the embedded archive's cookie. This saves us from having to make assumptions
about the cookie's positon, which both simplifies the search and makes it more robust.
Currently, we are searching within fixed-sized search window either from the end of file or from end of file's digital signature (if
present; on Windows and macOS only).
This breaks when a 3rd party tool appends extra data at the end of executable; for example, with PIE bootloader executable,
`staticx` tool on linux will append extra sections at the end of file, which is perfectly valid behavior, but it breaks our fixed-size
search window assumptions. Therefore, full back-to-front search fixes #5330 and JonathonReinhart/staticx#71.
Another motivation for brute-force search is …

 bootloader: implement full back-to-front scan for embedded archive

---

PyInstaller/archive/writers.py
news/5569.bugfix.rst

When building CArchive package under MSYS, `os.path.sep` is Unix-style forward clash separator that is incompatible with bootloader (which on Windows expects back slash separators). Therefore, if we are on Windows and `os.path.sep` is forward slash, `os.path.normpath()` in `CTOC.add()` needs to be followed by explicit replacement of forward slashes with back slashes.
Otherwise, bootloader fails to extract nested files from archive in onefile builds that are created in MSYS environment.
Fixes second part of the issue reported in #5560.

archive: fix stored paths when building under MSYS

---

bootloader/src/pyi_python.c
bootloader/src/pyi_python.h
bootloader/src/pyi_pythonlib.c
doc/spec-files.rst
news/1441.feature.rst
tests/functional/scripts/pyi_unbuffered_output.py
tests/functional/specs/pyi_unbuffered_output.spec
tests/functional/test_unbuffered_stdio.py

Setting `Py_UnbufferedStdioFlag` enables unbuffered stdio mode in the Python library. 
This enables unbuffered binary layer of `stdout` and stderr streams in all supported Python versions, while unbuffered text layer requires Python 3.7 or later.
Closes #1441.

bootloader: use Py_UnbufferedStdioFlag to enable unbuffered output

---

appveyor.yml
bootloader/src/pyi_path.c
news/5617.bugfix.rst
tests/functional/test_basic.py

On Windows, `pyi_path_fopen()` erroneously uses `MAX_PATH` (260) instead of `PATH_MAX` (4096) to convert the filename to wide characters, which causes `MultiByteToWideChar()` call in `pyi_win32_utils_from_utf8()` to fail with
```
MultiByteToWideChar: The data area passed to a system call is too small.
```
when we try to open a file with a long filename (> 260).
Due to lack of error checking, the resulting `wfilename` array ends up with random content, and the `_wfopen()` call either fails
(in read-only mode) or creates a randomly-named file (in write mode).
Fixes #5615.

bootloader: replace stray MAX_PATH with PATH_MAX

---

PyInstaller/hooks/hook-pandas.py
news/5630.hooks.rst

`pandas` 1.2.0 and later require hidden import of `cmath` on linux and macOS.

hooks: pandas: update for compatibility with pandas 1.2.0 and later

---

PyInstaller/building/api.py
news/5625.bugfix.rst
tests/functional/test_basic.py

... regardless of the icon setting.
The `onefile` builds on Windows may not have manifest embedded if icon was explicitly disabled via `--icon NONE`. This in turn causes subtle issues, such as #5624.
Fixes #5624.
Side note: with 3c3228d, the behavior of this issue became inverted; before it (i.e., PyInstaller 4.1 and older), the manifest would not be embedded if icon was not provided (i.e., `self.icon` was falsy), i.e., by default. So this may also explain some weird behavior of Windows `onefile` builds made with PyInstaller 4.1 and older (which mysteriously went away if --icon was specified).

building: ensure that onefile builds on Windows have manifest embedded

---

PyInstaller/hooks/hook-matplotlib.py
news/5629.hooks.rst
tests/requirements-libraries.txt

If the statement in `exec_statement()` fails for whatever reason, `mpl_data_dir` ends up empty, which in turn cases the current working directory being collected as `matplotlib/mpl-data`.
This leads to difficult-to-debug issues (see confusion around `.git` directory under #5504), so it's better to just signal the error.

hooks: matplotlib: assert that mpl_data_dir is not empty

---

PyInstaller/compat.py
news/5640.bugfix.rst

Extend the architecture setting in `__wrap_python()` on macOS to handle `arm64`. Fixes helper-spawned python sub-processes failing to start with `Bad CPU type in executable` when running under `arm64`-only version of Python on Apple M1.
Fixes #5640.

compat: fix forced arch for helper-spawned python processes on macOS

---

PyInstaller/depend/analysis.py
news/3825.bugfix.rst

If `ctypes` is (manually) added to hidden imports under python 3.7, one of `referers` entries processed in `get_co_using_ctypes()` method of `PyiModuleGraph` ends up being None. This in turn causes error when its `identifier` property is accessed, causing #3825.
Work around the problem by explicitly skipping `None` entries.
Fixes #3825.

depend: work around the potential None referer in get_co_using_ctypes

---

PyInstaller/archive/readers.py
PyInstaller/archive/writers.py
bootloader/src/pyi_archive.h
news/3939.feature.rst

Switch the offsets and lengths in `CTOC` and `CArchive` python data structures from signed 32-bit integers to unsigned 32-bit integers. Adjust the field definitions in bootloader's `CArchive` reader code accordingly.
Increases the maximum allowed CArchive size from 2 GiB to 4 GiB.
Fixes #3939.

archive: switch offsets and lengths to unsigned 32-bit integers

---

PyInstaller/building/api.py
news/5652.bugfix.rst

A duplicated TOC entry (e.g., a resource being once listed as binary in `Analysis.binaries` and once as data in `Analysis.datas`) in the first `Analysis` being passed to `MERGE()` ends up generating a spurious `DEPENDENCY` entry with a self-reference to itself.
Therefore, the `dependencies` TOC of the primary `Analysis` object ends up non-empty, and if passed to `EXE()`, results in a non-functional executable.

Prevent MERGE from creating self-references for duplicated TOC entries

---

news/5678.bugfix.rst
pyproject.toml

Pip prefers to install sdists by building a .whl then installing that. If the `wheel` package is not installed then it defaults to the older `python setup.py install`method. This older method breaks if it encounters unicode paths so ideally we want to `wheel` installed before attempting to install PyInstaller itself. PEP517's build-system.requires adds this option.
One downside of this is that it makes source installations slower because it creates a full blown virtual environment to build this wheel in - even if you already have wheel installed. Another interesting caveat is that it doesn't change `pip install -e .`.

Setup: Fix unicode path related installation errors (#5678).

---

.github/workflows/macos.yml
.travis.yml
PyInstaller/depend/imphook.py
PyInstaller/utils/conftest.py
appveyor.yml
setup.cfg

My war against noisy build logs:
- Move flaky testing to CI only. And disable flaky reporting which doesn't tell us anything we don't already know.
- Demote noisy logging of excluded imports to DEBUG.
- Drop pytest's log level to INFO.
I imagine we'll want to squash these but I've kept them separate in case anyone is particularly opposed to one of them.

Declutter CI/CD logs.

---

bootloader/src/pyi_launch.c
doc/runtime-information.rst
news/5649.bootloader.rst
news/5649.break.rst
news/5649.doc.rst
tests/functional/scripts/pyi_filename.py

Set `__file__` attribute in `__main__` module to full path (i.e., including absolute path to `_MEIPASS`) instead of just entry-point
script  name. This ensures consistent behavior with that of `__file__` attributes in packages/modules, where the full path to
file is returned, as if it existed inside the `_MEIPASS`.
Fixes #5626.

bootloader: set __file__ in __main__ module to full path

---

tests/functional/test_unbuffered_stdio.py

The test seems to be occasionally failing on the CI, so skip it for now to minimize the damage.

tests: skip test_unbuffered_stdio on CI

---

PyInstaller/loader/pyimod03_importers.py
news/5697.feature.rst

Provide basic `FrozenImporter.get_source()` implementation that allows loading of source from `.py` files that have been collected by hooks as data files.
This is, for example, required by PyTorch's JIT compilation mechanism. 
The issue of missing source code inside frozen application, which is required by some packages, is tracked under #4764. However, it seems the primary solution discussed there is collecting `.py` files into PYZ archive. This PR instead adds support only for loading source from on-filesystem `.py` files that have been collected via `collect_data_files()` with `include_py_files=True`, which was also suggested by https://github.com/pyinstaller/pyinstaller/issues/4764#issuecomment-633777790. But in the end, the two approaches are complementary, and even if we really …

loader: implement FrozenImporter source loading from .py files

---

PyInstaller/building/makespec.py
PyInstaller/building/templates.py
news/5391.feature.rst

Add new command-line options that map to the corresponding functions from the hookutils:
* --collect-submodules: collect_submodules()
* --collect-data: collect_data_files()
* --collect-binaries: collect_dynamic_libs()
* --collect-all: collect_all()
* --copy-metadata: copy_metadata()
The hookutils calls are added to the generated .spec files. They may be specified multiple times, and their results supplement
the entries that are manually passed via existing --add-data, --add-binary, and --hidden-import switches.
This allows hookutils calls to be added from command-line, without having to manually edit the .spec file.

building: makespec: add new command-line switches for hookutils functions

---

PyInstaller/depend/utils.py
news/5730.bugfix.rst

This allows PyInstaller to work with embedded python on Windows, provided that the user worked around the lack of support for
collecting files from `python3X.zip` (i.e., by replacing the `python3X.zip` file with same-named folder that contains unpacked
contents of the zip).
In python 3.7 and later, the collected modules end up with hash that is derived from the raw contents of the original compiled
module (as opposed to source, which is unavailable). While this is technically incorrect, it should also be irrelevant in a
frozen application, and is therefore not explicitly addressed (e.g., by copying hash from the original compiled module).

depend: allow compiled modules to be collected into base_library.zip

---

bootloader/wscript
doc/bootloader-building.rst
news/5733.bootloader.rst

- Fix the waf file to allow cross compiling for FreeBSD. It doesn't need any special handling. It just needs the 'this
is untested' check removed.
- Add developer docs explaining how to do it.

Bootloader: waf: Support cross-compile for FreeBSD. [skip-ci]

---

PyInstaller/depend/utils.py
news/5734.bugfix.rst
tests/functional/test_regression.py

On some Linux C compiler combinations:
```python
ctypes.util.find_library("libc.so")
```
Unintentionally trips a FileNotFoundError instead of simply returning None.
Fixes #5734.

Analysis: ctypes: Guard against errors triggered by find_library(). (#5734)

---

PyInstaller/utils/hooks/__init__.py
doc/conf.py
doc/hooks.rst
news/5734.feature.rst
tests/functional/scripts/list_pytest11_entry_point.py
tests/functional/specs/list_pytest11_entry_point.spec
tests/functional/test_hook_utilities.py

For cases where *collect all backends/plugins* really is what you want. My main motivation for this is collecting pytest plugins but it could also mop up the mess that is our keyring support or possibly be used to allow 3<sup>rd</sup> party matplotlib backends.
Provides an easy fix to #5016 and #1188.

Add hook utility for collecting setuptools entrypoints.

---

.github/workflows/ci.yml
tests/requirements-tools.txt

For some reason that we can't work out, using pytest-xdist
on Windows Github Actions causes tests to fail.
For the record, we've also tried:
- reducing the maximum number of concurrent processes (#5741).
- greatly increasing timeout limits (again #5741)
- increasing flaky retry limit ([bwoodsend/super-flakey branch](https://github.com/bwoodsend/pyinstaller/runs/2375784301))
None of which made any noticeable difference.
The CI/CD for this PR should confirm that this works but [here](https://github.com/bwoodsend/pyinstaller/runs/2375768917) is a spotlessly working build log.

CI/CD: Disable parallel testing.

---

PyInstaller/compat.py
news/5749.bugfix.rst

Fix python library lookup for recent versions of python packaged through RH SCL, which uses non-standard naming scheme:
```
lrwxrwxrwx  libpython3.8.so -> libpython3.8.so.rh-python38-1.0
-rwxr-xr-x  libpython3.8.so.rh-python38-1.0
-rwxr-xr-x  libpython3.so.rh-python38
```
This is an extension of b748881 that added support for earlier versions of RH SCL python.
Fixes #5749.

compat: fix python library lookup for recent versions of RHSCL python

---

bootloader/src/pyi_archive.c
news/5762.bugfix.rst

The magic pattern buffer that we use for finding the `CArchive`'s `COOKIE` structure is itself stored in the executable as binary data, and can produce a match.
This is not a problem if `CArchive` is actually embedded in the executable, as it is matched first. However, for the builds with
side-loaded `CArchive` .pkg and "empty" bootloader executable, the full-file scan introduced in 698ad70 causes a spurious match in the executable, and leads to undefined behavior as we try to interpret the subsequent data as `CArchive`'s header and `TOC`.
Obfuscating the pattern by splitting it in two and separating it with unused data prevents the spurious match when scanning
an "empty" bootloader executable, i.e., one without appended `CArchive` package.
Fixes #5762.

bootloader: obfuscate the CArchive MAGIC pattern stored in executable

---

PyInstaller/depend/dylib.py
news/5770.bugfix.rst

Enable collection of `msvcp140{,_1,_2}.dll` and `vcruntime140_1.dll`. Collecting these DLLs should allow the frozen application to run on Windows systems that do not have *Visual Studio 205/2017/2019 Redistributable* installed.
Fixes #5768 (and likely other similar issues that we've seen in the past).

depend: expand _win_includes list with additiona DLLs from vcredist

---

.github/workflows/ci.yml

The macOS pipeline seems to have been ignoring `test_libraries.py` ever since it has been migrated from Travis. This looks like a mistake originating from tests being split between Base and Libraries on the Travis pipeline.

CI/CD: test libraries on macOS runners as well

---

PyInstaller/depend/dylib.py

Required for skimage-enabled frozen applications to run on systems without VC redistributable installed.
Fixes #5777.

depend: add vcomp140.dll to _win_includes list

---

PyInstaller/hooks/hook-gevent.py
PyInstaller/utils/hooks/__init__.py
doc/hooks.rst
news/5774.bugfix.rst
tests/unit/test_hookutils.py

Prevent metadata folders such as `foo-1.2.3.dist-info` from being renamed to `foo-1.2.3.egg-info` which breaks usage of:
```python
pkg_resources.get_distribution("foo").requires(extras=["..."])
```
This commit, in essence, reverts the patch applied to resolve #1888, which forcibly renamed everything to use `.egg-info` to avoid destination collisions caused by egg-info paths such as `site-packages/pyhook-1.5.1-py2.7-win32.egg/EGG-INFO` formally being copied into bundles as just `EGG-INFO`.
Now, in the above scenario, the destination folder is `pyhook-1.5.1-py2.7-win32.egg/EGG-INFO` which prevents both the naming collision and avoids renaming dist-infos to eggs.
Also merge the docstring documentation for copy_metdata() with the website version via sphinx.ext.autodoc.
Fixes #3033.

Hook-utils: copy_metadata(): Preserve metadata folder name.

---

MANIFEST.in
setup.cfg
setup.py

Build separate wheels for each platform containing only the correct bootloaders for said platform with no C source code/build scripts. Set the platform tag so that the correct wheel will be selected automatically by pip.
To facilitate cross compiling (or rather cross platform wheel building), add new cross-build wheel commands to the setup.py and a "build the lot" command (bdist_wheels) to run them all:
```bash
> python setup.py --help-commands
...
Extra commands:
...
wheel_windows_64bit  Create a Windows-64bit wheel
wheel_windows_32bit  Create a Windows-32bit wheel
wheel_linux_64bit    Create a Linux-64bit wheel
wheel_linux_32bit    Create a Linux-32bit wheel
wheel_darwin_64bit   Create a Darwin-64bit wheel
...
bdist_wheels         Build all available wheel types
...
```
With the above …

setup: Build per-platform wheels.

---

MANIFEST.in

Without them MSYS2 users are forced to build from source because wheels don't work on MSYS2 and pip won't simply use the Windows wheel - even though it would be compatible.

setup: Put Windows bootloaders back in the sdist.

---

bootloader/src/pyi_pythonlib.c

```
"find yout why and foor what modules"
=>
"find  out why and for  what modules"
```

Typo fix in comment

---

PyInstaller/utils/conftest.py
tests/requirements-tools.txt

#5765 may have eliminated the need for these patches.

tests/ci: revert changes to xdist/rerunfailures

---

setup.py

Amend #5787 (again). Fixes the issue highlighted in #5802 that `pip install .` doesn't take the bootloaders with it.

setup: Collect all bootloaders for default bdist_wheel.

---

.github/workflows/ci.yml
MANIFEST.in
setup.py

Ensure that the following files are collected into sdist and wheels (it seems we need to collect them explicitly):
* PyInstaller/fake-modules/site.py
* PyInstaller/hooks/rthooks.dat
* PyInstaller/lib/README.rst

setup: fix missing files in sdist and wheels

---

PyInstaller/building/build_main.py
PyInstaller/compat.py
PyInstaller/depend/bindepend.py
news/5816.feature.rst

When running under Microsoft App Store Python, `sys.executable` and `sys._base_executable` point to an empty shim exe file, located inside `%LOCALAPPDATA%\Microsoft\WindowsApps\PythonSoftware[...]`.
The empty executable file causes errors when PyInstaller tries to analyze it to determine reference arch and obtain assembly
dependencies that need to be added to manifest. (This part actually uses only `sys.executable`, and can be worked around by using `venv`, which provides a non-empty copy of executable).
In addition, executable being empty causes failure to determine the name of the python library from the executable itself (as reported in #5815).
To fix these problems, we introduce new variables in `compat` module:
* `is_ms_app_store`: set to `True` when running under MS app store python …

Implement support for Microsoft App Store Python

---

PyInstaller/hooks/hook-PyQt5.QtQml.py
PyInstaller/hooks/hook-PyQt5.QtWebEngineWidgets.py
PyInstaller/hooks/hook-PyQt5.py
PyInstaller/hooks/hook-PySide2.QtQml.py
PyInstaller/hooks/hook-PySide2.QtWebEngineWidgets.py
PyInstaller/hooks/hook-PySide2.py
PyInstaller/hooks/rthooks/pyi_rth_pyqt5.py
PyInstaller/hooks/rthooks/pyi_rth_pyqt5webengine.py
PyInstaller/hooks/rthooks/pyi_rth_pyside2.py
PyInstaller/utils/hooks/qt.py
news/5631.hooks.rst
tests/requirements-libraries.txt

Extend `Qt5LibraryInfo` with new property, `qt_rel_dir`, which denotes the relative Qt data path in the frozen application. Its value
varies between `PyQt5` and `PySide2`, their versions, and platforms:
* `PyQt5/Qt` for `PyQt5 <= 5.15.3` on all platforms
* `PyQt5/Qt5` for `PyQt5 >= 5.15.4` on all platforms
* `PySide2/Qt` for `PySide2` on Linux and macOS
* `PySide` for `PySide2` on Windows
This way, we now have a unified, central location when this path is determined, instead of the corresponding functionality being scattered across the hooks.
Adds support for `PyQt5 5.15.4`, and fixes #5631.
The paths used by rthooks also need to be adjusted to handle `PyQt5/Qt` vs `PyQt5/Qt5` switch, and to handle the difference between `PySide2` on Windows and `PySide2/Qt` on other platforms (as we now …

hooks: PySide2/PyQt5: unify handling of relative Qt directory

---

PyInstaller/building/build_main.py

An `open_file()` slipped through #5818, and is causing errors when running with `--log-level DEBUG`.

refactor: remove a stray open_file in build_main.py

---

MANIFEST.in
setup.py

Instead of collecting just `fake-modules/site.py`, collect all py files via `fake-modules/*.py` glob. This future-proofs the packaging
against new file additions.

setup: collect all .py files from fake-modules using glob

---

PyInstaller/compat.py
bootloader/wscript

The addition of support for compiling bootloader under Cygwin (bc0354278f31a796566f51d5509beb8820d3d1a3) introduced a cosmetic regression where compiling on any other platform is detected as cross-compiling. This is because the addition of `DESTOS_TO_SYSTEM['cygwin']: 'cygwin'` entry to `SYSTEM_TO_BUILDOS` and `'cygwin': platform.system()˙ entry to `DESTOS_TO_SYSTEM` causes `BUILD_OS˙ to always become `cygwin`.
To fix that, modify the `wscript` to explicitly check for `sys.platform == 'cygwin'` and in that case ignore `platform.system()`, which on Cygwin contains an identifier that does not fit the PyInstaller's OS naming scheme (i.e., `MSYS_NT-10.0-19042`, `CYGWIN_NT-10.0-19042`). Instead, manually force the system name to `'Cygwin'`.
Similarly, manually override `compat.system` to …

bootloader: fix cross-compilation detection, improve Cygwin handling

---

PyInstaller/building/api.py
PyInstaller/utils/osx.py
news/5827.bugfix.rst
news/5839.bugfix.rst

Ensure that the macOS SDK version reported by the frozen application (`sdk` field of `LC_VERSION_MIN_MACOSX` load command in executable's headers) corresponds to the minimum of the SDK version used to build the bootloader and the SDK version used to build the Python library (and by extension, other python-bundled libraries, such as Tcl/Tk).
Having the application report more recent version that Python library may result in macOS attempting to enable additional features that are not available in the Python library, which may in turn case inconsistent behavior and UI issues with `tkinter`. Overall, matching the SDK version of Python library should ensure the most consistent behavior w.r.t. python interpreter executable, which reports that same version.
An example of SDK-version-based …

building: adjust macOS SDK version reported by frozen application

---

PyInstaller/utils/hooks/__init__.py

In `is_module_satisfies()`, before trying to query module's version via `get_module_attribute()` in the fallback path, check if the module can be imported at all via `can_import_module()`.
This prevents a `ModuleNotFoundError` from being dumped to stderr when calling `is_module_satisfies()` for package that is not
installed.

hookutils: is_module_satisfies: check if module can be imported

---

PyInstaller/depend/analysis.py
PyInstaller/loader/pyiboot01_bootstrap.py
PyInstaller/loader/pyimod04_ctypes.py
news/5797.bugfix.rst
tests/functional/test_basic.py
tests/functional/test_regression.py

Move the `ctypes` hooks from bootstrap script into separate module (`pymod04_ctypes`). The main motivation for this is to prevent the modifications to global namespace from affecting the `ctypes` hooks code; specifically, if user decides to use `sys` or `os` as variables in the global namespace, that should not effect the `ctypes` hook function `_frozen_name()`, which treats `sys` and `os` as names of modules (which were bound to those names when the bootstrap script was executed).
Fixes #5797.
This commit is a cleaned-up and modernized version of selected commits from #3038, plus additional test that re-creates situation from #5797.

loader: move ctypes hooks into a module

---

PyInstaller/building/splash.py
PyInstaller/utils/hooks/tcl_tk.py

Currently, the Tcl/Tk library search on macOS first calls `bindepend.selectImports()` and then as fallback `bindepend.getImports()`.
`bindepend.selectImports()` ignores the imports that were encountered during previous invocation. This means that if the
search was ran twice (e.g., once when trying to locate data directories for `_tkinter` hook and once for splash screen), the second run might behave differently than the first one. And since `selectImports()` coming up empty is interpreted in certain way, this may lead to errors.
So instead, reimplement the library search function using only `bindepend.getImports()`, based on implementation of similar
functionality in `Splash._get_dlls()`. Then, replace the use of `Splash._get_dlls()` with the new reimplemented function.

hookutils: tcl/tk: clean up Tcl/Tk library search on macOS

---

PyInstaller/hooks/hook-importlib_metadata.py

This goes against what was said in #5830 and e800e0de8b33f177ef419cf9b90b4bcf78089bd0 - that we never need to use `copy_metadata()` in a hook ever again. Because `PyiModuleGraph.get_co_using()` ignores self references, if `importlib_metadata` uses `importlib_metadata` to access its own metadata then this goes undetected. Older versions of `importlib_metadata` do this and are therefore broken. This has previously not been picked up by CI because it uses the latest version of `importlib-metadata` which no longer checks its own version but caused [a failure](https://travis-ci.org/github/pyinstaller/pyinstaller-hooks-contrib/jobs/772514679) in pyinstaller/pyinstaller-hooks-contrib#122 because Travis used an older version.
Partially reverts e800e0de8b33f177ef419cf9b90b4bcf78089bd0.

Hooks: Re-collect importlib-metadata's metadata.

---

PyInstaller/building/utils.py
PyInstaller/utils/misc.py
news/4178.feature.rst

UPX is known to "corrupt" Qt plugins (it removes the `.qtmetad` section and `QTMETADATA` magic string - see upx/upx#107).
Instead of requiring users to manually exclude Qt plugins from UPX processing, do it automatically based on the file analysis, i.e.,
full back-to-front scan for the `QTMETADATA` magic string.
Fixes #4178.

building: automatically exclude Qt plugins from upx processing

---

bootloader/wscript

Remove the low-level setting of macOS deployment target via `-mmacosx-version-min` switch in `CFLAGS` and `LDFLAGS`. Instead, use only `MACOSX_DEPLOYMENT_TARGET` environment variable.
Move setting the default `MACOSX_DEPLOYMENT_TARGET` for bootloader (if the variable is not defined in the environment already) before first test/check that requires compiler. Otherwise, the environment variable is automatically set to the toolchain's default.
We should now be targeting 10.13 by default, but the target can be changed by setting `MACOSX_DEPLOYMENT_TARGET` in environment before calling `waf`.

bootloader: wscript: fix setting of MACOSX_DEPLOYMENT_TARGET

---

MANIFEST.in
PyInstaller/utils/osx.py
setup.py

Implements the changes from #5879.
This turned out to be much simpler than I expected. All it takes is replacing `x86_64` in the wheel platform tag to `universal2`. But because the macOS bootloaders can now be compiled in 3 different ways (`x86_64`, `arm64` or both), I've made the wheel tag automatically determinant on what bootloaders. And to reduce the number of places we have to hardcode it, I've done the same with the macOS deployment target - i.e. the minimum required macOS version in the wheel tag is derived from that of the bootloaders.
This makes macholib (irregardless of platform) and PyInstaller itself a build dependency of `setup.py wheel_darwin_64bit` but neither *should* be a problem.

Enable building universal2 wheels for macOS

---

bootloader/Vagrantfile
doc/bootloader-building.rst

Update MACOSX_DEPLOYMENT_TARGET from 10.11 to 10.13 when cross-compiling macOS bootloaders in `linux64` VM.
Improve selection of macOS SDK in `build-osxcross` VM - always select the latest available version of the SDK. Fixes building with SDKs extracted from Xcode command line tools 12.5, which provide two variants of SDK with major version 11 - "11" and "11.3".
Upgrade VS toolchain in `windows10` VM from VS2015 to VS2019.

Update Vagrant VMs

---

PyInstaller/depend/dylib.py

Required for `tensorflow`-enabled frozen applications to run on systems without VC redistributable installed.
Yet another follow-up on #5770.
At least partially fixes ghalter/VIAN#340 and possibly #5898 (assuming they are related).

depend: add concrt140.dll to _win_includes_list

---

PyInstaller/loader/pyimod04_ctypes.py
news/5907.hooks.rst

Modify the `_frozen_name()` so that it first checks if the given (file)name exists, before falling back to searching `sys._MEIPASS`
for it.
This effectively switches the search order: whereas formerly we would first check `sys._MEIPASS` and use the given name as fallback, we now first check the given name and then search `sys._MEIPASS` as a fallback.

loader: ctypes: switch the search order for frozen libraries

---

PyInstaller/__main__.py
PyInstaller/utils/cliutils/makespec.py
PyInstaller/utils/hooks/__init__.py
PyInstaller/utils/hooks/conda.py
doc/CHANGES-3.rst
doc/Makefile
doc/_static/css/pyinstaller.css
doc/advanced-topics.rst
doc/bootloader-building.rst
doc/conf.py
doc/feature-notes.rst
doc/help2rst.py
doc/hooks.rst
doc/make.bat
doc/man/pyi-makespec.rst
doc/operating-mode.rst
doc/runtime-information.rst
doc/spec-files.rst
doc/usage.rst
doc/when-things-go-wrong.rst

An assortment of doc refactorings to better leverage `sphinx.ext.autodoc` and `sphinx.ext.intersphinx`.
- Use autodoc throughout `PyInstaller.utils.hooks`and `PyInstaller.compat` so that:
- We don't have to maintain doctrings and website docs.
- Each function/class/variable has a both a unique url target such as [hooks.html#PyInstaller.utils.hooks.collect_submodules](http://pyinstaller.readthedocs.io/hooks.html#PyInstaller.utils.hooks.collect_submodules) and a unique rst target ``:func:`PyInstaller.utils,hooks.collect_submodules` ``.
- Replace ``` ``xyz()`` ``` with ``:func:`xyz` `` for standard library functions where possible. This turns them into links to Python's own documentation.
- Make each CLI option a reference-able and promote plain literal options ``` ``--hiddenimport`` ``` to …

Doc: Let there be cross references!

---

bootloader/src/pyi_main.c
bootloader/src/pyi_utils.c
bootloader/src/pyi_utils.h
news/5436.bugfix.rst
news/5908.bugfix.rst
news/5920.bugfix.rst
news/5920.feature.rst
tests/functional/specs/pyi_osx_custom_protocol_handler.spec
tests/functional/specs/pyi_osx_event_forwarding.spec
tests/functional/test_apple_events.py

Have the `onedir` codepath in `windowed` mode (macOS app bundle) perform a single iteration of `apple_process_events()`, in order to process any `odoc` and `GURL` events that an .app bundle may have received. The events are converted into corresponding `sys.argv` arguments.
Fixes #5908. Fixes #5436.
The `test_osx_custom_protocol_handler` and `test_osx_event_forwarding` are now performed in both `onedir` and `onefile` mode, and all of them pass.
The core of the patch is the same as the proof-of-concept given in #5436 (i.e., running a single iteration of `apple_process_events()` and pass modified arguments to frozen python script), except we take additional care not to do this in a child process of `onefile` built (as it seems to upset `test_osx_event_forwarding[onefile]`, presumably …

macOS: add Apple event processing for onedir .app bundles

---

.github/workflows/ci.yml
PyInstaller/depend/utils.py
tests/functional/test_import.py

Fix regression in names of binaries obtained from scanning for uses of `ctypes.util.find_library`, introduced by the `ctypes` scanning code refactoring (416f42b). 
The new code does not account for the fact that the input to `ctypes.util.find_library()` is library "base" name (i.e., without "lib" prefix and without suffix), and therefore obtained name needs to be resolved.

depend/utils: fix regression in ctypes.util.find_library scanning

---

tests/functional/test_linux_appimage.py

Fix the check for `appimagetool` in `test_appimage_loading`; due to missing negation, the test currently fails if `appimagetool`
is not installed, and is skipped if it is installed.

tests: appimage: fix check for appimagetool

---

PyInstaller/hooks/rthooks.dat
PyInstaller/hooks/rthooks/pyi_rth_inspect.py
news/5963.bugfix.rst
tests/functional/modules/pyi_inspect_getmodule_from_stackframes/helper_package/__init__.py
tests/functional/modules/pyi_inspect_getmodule_from_stackframes/helper_package/helper_module.py
tests/functional/test_misc.py

Add an rthook for `inspect` and override `inspect.getsourcefile` with our own implementation that handles module paths (especially relative ones, as obtained from `inspect`'s stack frames) in PyInstaller-compatible way. 
Fixes #5963.

Fix inspect.getmodule() failing to resolve module from stack-frame

---

PyInstaller/loader/pyimod03_importers.py
bootloader/src/pyi_launch.c
news/5897.bugfix.0.rst
news/5897.bugfix.1.rst
tests/functional/test_misc.py

Make `__main__` module recognized as module instead of built-in, by setting its `__loader__` to `FrozenImporter` instance.
Enable retrieval of code object for `__main__` via `FrozenImporter.get_code` (by having bootloader store it in `_pyi_main_co` attribute of `__main__` module, as otherwise python code is unaware of frozen entry-point scripts).
Fixes #5897. Requires bootloader to be rebuilt.

loader: fix __main__ being recognized as built-in & allow retrieval of its code-object

---

.github/workflows/ci.yml
bootloader/wscript
doc/bootloader-building.rst

Auto-detect whether the toolchain supports building `universal2` binaries, and enable/disable building of `universal2` bootloader
accordingly (unless `--universal2` or `--no-universal2` is explicitly passed on command-line).
Allows compiling bootloader on older toolchains without having to explicitly specify `--no-universal2`.

bootloader: waf: automatically enable/disable universal2 bootloader

---

PyInstaller/building/osx.py
news/4413.bugfix.rst
news/5442.bugfix.rst

Remove spurious `MacOS/` prefix from `CFBundleExecutable` in the generated `Info.plist` when building an app bundle. As discussed in #4413 and #5442, the `CFBundleExecutable` should contain only executable name.
Having the `MacOS/` prefix causes the following warning to be shown in macOS Console.app when the bundle is launched on macOS 10.14 Mojave (the later versions of macOS seem unaffected):
```
com.apple.xpc.launchd.domain.pid.<Application Name>.<PID>): Could not resolve origin of domain. XPC services in this domain's bundle will not be bootstrapped: error = 107: Malformed bundle, taint = missing executable
```
Effectively reverts 6b99e01.
Fixes #5442.
Fixes #4413.

building: osx: remove spurious MacOS/ prefix from CFBundleExecutable

---

PyInstaller/hooks/hook-setuptools.py
news/5979.hooks.rst

This reverts commit 00dcae2a77ead2eed805bdc25eaff4927ecf2b46.
While the `setuptools.py27compat` and `setuptools.py33compat` are aimed at obsolete python versions, their exclusion and subsequent absence causes `ModuleNotFoundError` when `setuptools` tries to import them from its other modules (see #5973).
This affects older versions of `setuptools` (e.g., 40.x that comes with python 3.6). In newer versions, these modules are not present anymore (and them being in excludedimports probably generates "Import to be excluded not found" warnings during build process).

Revert "hooks: setuptools: Exclude outdated compat modules."

---

PyInstaller/hooks/rthooks.dat
PyInstaller/hooks/rthooks/pyi_rth_pkgutil.py
news/1905.feature.rst
tests/functional/scripts/pyi_pkgutil_iter_modules.py
tests/functional/test_pkgutil.py

Implement support for `pkgutil.iter_modules`. 
This is done by an rthook that monkey-patches the function with our implementation, which extends the contents listed by original implementation (on-filesystem resources) with PYZ-embedded resources.
Closes #1905.
Fixes #5167 (the `iter_modules` not returning anything unless `noarchive` is used; however, the modules still need to be collected by `collect_submodules` in the first place).
Fixes #5799.

Add support for pkgutil.iter_modules

---

bootloader/src/pyi_main.c
news/6000.bugfix.rst

When processing dependencies of a DLL under Cygwin, the Windows' internal mechanism is used, which means that `LD_LIBRARY_PATH` has no effect, and the DLL search path needs to be established either via `PATH` or by calling `SetDllDirectory()`. The second option is already used in Windows codepath, so we extend it for Cygwin as well.
Failing to add _MEIPASS to DLL search path prevents python shared library from being loaded by a onefile build made under
cygwin when ran outside of cygwin environment, as it fails to resolve the dependent DLLs (see #6000). Onedir builds are unaffected because DLLs are located in the same directory as the executable. And both builds are unaffected when ran within cygwin environment, because the DLLs are in the `PATH`.
Fixes #6000.

bootloader: Cygwin: set _MEIPASS as DLL search directory

---

bootloader/src/pyi_launch.c
bootloader/src/pyi_launch.h
bootloader/src/pyi_main.c
bootloader/src/pyi_path.c
bootloader/src/pyi_pythonlib.c
bootloader/src/pyi_utils.c
bootloader/src/pyi_win32_utils.c

Minor cleanup in bootloader's code:
* ensure all `VS()` and `*ERROR()` messages end with newline (`\n`)
* remove two unused functions, `callSimpleEntryPoint` and `cleanUp`

bootloader: minor cleanup

---

PyInstaller/hooks/hook-pandas.io.formats.style.py
news/6010.hooks.rst
tests/functional/test_libraries.py

Add `jinja2` to hiddenimports and collect data files from `pandas.io.formats` to include the missing template file (`pandas/io/formats/templates/html.tpl`).
Fixes #6008.
Fixes #6009.

Add hook for pandas.io.formats.style

---

PyInstaller/hooks/rthooks/pyi_rth_pkgutil.py
news/6018.bugfix.rst

Otherwise, `SYS_PREFIX` from `pyi_rth_pkgutil` clashes with `SYS_PREFIX` from `pyi_rth_pkgres` and causes #6018 when both rthooks are used.

hooks: pkgutil rthook: declare SYS_PREFIX as function-local symbol

---

PyInstaller/building/build_main.py
PyInstaller/depend/bytecode.py
PyInstaller/depend/utils.py
news/6007.bugfix.rst
tests/unit/test_bytecode.py

All bytecode instructions come in OPCODE, ARGUMENT pairs of bytes so that every even byte is an OPCODE and every odd one is an ARGUMENT.
Formally, this wasn't enforced by our bytecode scanner, leading to false positive matches when a sequence of pairs' ARGUMENTS just happens to be the sequence of bytes as the OPCODEs which the scanner is looking for. These false positive matches are likely to become invalid after further parsing which led to
index errors (such as in #6007).
The fix is simply to skip any `re.Match` found that does not satisfy `match.start() % 2 != 0`.
To streamline any other issues regarding bytecode scanning, the top level code which invokes the bytecode scanner now catches and reraises errors, adding exactly which module it failed to scan to the error message.
Fixes …

Depend: Bytecode scanner: Skip false positive matches starting on odd bytes.

---

doc/hooks-config.rst
doc/index.rst
news/6025.doc.rst

Primarily intended as a registry of all options that are available in hooks provided by PyInstaller.

docs: add a page on hook configuration options

---

bootloader/wscript
news/6010.build.rst

A pair of fixes for building the bootloader on OpenWRT Linux which uses sstrip on its libraries, making them effectively unlinkable against.
* Extend the test for zlib availability to reference zlib symbols and thus capture this scenario.
* And an option to statically link zlib like we do on Windows.

Fixes for #6006

---

PyInstaller/building/build_main.py
news/6028.bugfix.rst
news/6032.core.rst

Limit the effect of a failing hook entry point, e.g. due to a package with missing dependency that is not actually used by the program.
Fixes #6028.

building: handle exceptions thrown during hook entry points loading

---

doc/development/changelog-entries.rst
scripts/verify-news-fragments.py

The towncrier is configured to look for `breaking` entries, but the verify-news-fragment.py script incorrectly looks for `break`
ones. Similarly, the `news/README.rst` incorrectly lists `break` as a category. Fix both to use `breaking` instead.

ci: fix news fragment validation for breaking changes

---

PyInstaller/utils/osx.py
news/6039.bugfix.rst

Compute the new value of `__LINKEDIT` segment's `vmsize` as value of modified `filesize`, rounded up to full page size (0x4000 on `arm64`, 0x1000 elsewhere). Fixes #6039.

building: macOS: modify vmsize when fixing up __LINKEDIT segment

---

PyInstaller/building/build_main.py
PyInstaller/building/utils.py
doc/spec-files.rst
tests/unit/test_building_utils.py

This implements the feature requested in issue #2732.  It adds a
method in the Analysis class called exclude_system_libraries
that excludes all but python system libraries by default, and
accepts a list of exceptions that are file wildcards of libraries
to continue to including.

building: Add exclude_system_libraries method

---

PyInstaller/depend/bindepend.py
PyInstaller/depend/dylib.py
news/6015.bugfix.0.rst
news/6015.bugfix.1.rst
news/6015.bugfix.2.rst
news/6015.bugfix.3.rst

This PR is a collection of changes that aim to improve missing-library messages generated during binary dependency scanning.
First, downgrade messages from ERROR to WARNING, because it is a pain having to explain to users that the build process did finish nevertheless and that they should try running the generated binary. (It is actually quite reasonable to assume that something has gone terribly wrong when you see that message, unless you've worked with PyInstaller before).
Display warnings for missing libraries on linux systems (i.e., `libsomething.so => not found` lines in `ldd` output). Currently, we are quietly swallowing those, which leads to issues like #5863 that would have been otherwise easy to figure out. This probably captures only output generated by glibc-based `ldd` on …

Improve missing linked library warnings

---

PyInstaller/hooks/hook-PyQt5.QtWebEngineWidgets.py
PyInstaller/hooks/hook-PySide2.QtWebEngineWidgets.py
PyInstaller/utils/hooks/qt.py
news/6020.hooks.rst
tests/functional/test_qt.py

Use a common helper function to collect `QtWebEngine` binaries and data files in order to reduce code duplication and simplify maintenance of the hooks.
This will hopefully simplify addition of corresponding hooks for Qt6 which will re-introduce QtWebEngine in the upcoming 6.2 version. But it will also make it easier to sort out the macOS mess, once I get other prerequisites ready.
I've also cleaned up the code of both QtWebEngine tests to make their code visually the same, as well to synchronize their behaviors.

hooks: unify PySide2 and PyQt5 QtWebEngineWidgets hooks

---

doc/spec-files.rst
news/6022.feature.rst

The last version of the commit in pr #6022 which was merged accidentally
left out the news file.  This adds it back.  In addition, the example in
the documentation used a format for the Analysis step that was inconsistent
with examples in the immediately following sections.  This makes the format
consistent.

building: Complete the exclude_system_libraries feature

---

bootloader/src/pyi_main.c
news/6043.bugfix.rst
news/6048.breaking.rst
tests/functional/test_apple_events.py

Disable macOS `argv` emulation for `onedir` application bundles, which was introduced by #5920. Processing Apple events in
the main (and for onedir application, the only) process swallows up initial OAPP (`kAEOpenApplication`) event, which seems to
cause crashes in `tkinter`-based `onedir` bundles created with Homebrew python 3.9 and Tcl/Tk 8.6.11 (reported in #6043).
Therefore, until the exact cause of the crashes is determined and fixed, we need to disable Apple event processing for
`argv` emulation in `onedir` mode. This effectively reverts the corresponding part of #5920, while keeping other changes introduced there (code refactoring, filtering of `-psn*` argument from `argv`).
Fixes #6043.
Re-opens #5436 and #5908.

bootloader: macOS: disable onedir argv emulation

---

PyInstaller/utils/tests.py
tests/functional/test_pkgutil.py
tests/functional/test_qt.py

This should have been removed #6023 and is (we think) the cause of some sporadic test failures on CI.

Tests: Remove one remaining usage of pytest.importorskip().

---

bootloader/src/pyi_launch.c
bootloader/src/pyi_python.h
news/6070.bugfix.rst

Fix a crash I came across on macOS in windowed (app bundle) mode.
Also remove Py_*REF macros, because every time I see them I start wondering whether they can be passed NULL or not...

bootloader: fix crash in windowed mode when traceback is unavailable

---

bootloader/src/pyi_python.c
bootloader/src/pyi_python.h
bootloader/src/pyi_pythonlib.c
news/6054.bugfix.rst
news/6065.feature.rst
tests/functional/test_misc.py

Enable [PEP540](https://www.python.org/dev/peps/pep-0540/) UTF-8 mode if `PYTHONUTF8` environment is set to 1 (on all OSes, regardless of locale setting). On non-Windows, enable PEP540 UTF-8 mode for `C` and `POSIX` locales to match the behavior of the python interpreter.
Fixes #6054.
The UTF-8 mode handling code is separate from other runtime options handling, because it seems that `Py_UTF8Mode` needs to be set *before* `Py_SetPath()` is called to have any effect. On the other hand, it seems that setting the warning flags via `PySys_AddWarnOption()` in `pyi_pylib_set_runtime_opts()` needs to be  done *after* `Py_SetPath()` is called. Therefore, UTF-8 mode handling code is implemented as a separate utility function and called at the beginning of `pyi_pylib_start_python()`, while the call …

 bootloader: implement support for PEP540 UTF-8 mode

---

bootloader/src/pyi_utils.c
bootloader/src/pyi_win32_utils.c
bootloader/src/pyi_win32_utils.h
news/6074.bugfix.rst
tests/functional/test_misc.py

bootloader: prevent onefile cleanup from recursing into symlinked directories

---

PyInstaller/building/build_main.py
PyInstaller/hooks/hook-PySide2.Qwt5.py
PyInstaller/hooks/hook-django.py
PyInstaller/hooks/hook-gi.repository.Gst.py
PyInstaller/hooks/hook-matplotlib.py
PyInstaller/hooks/pre_safe_import_module/hook-setuptools.extern.six.moves.py
PyInstaller/hooks/pre_safe_import_module/hook-six.moves.py
PyInstaller/hooks/pre_safe_import_module/hook-urllib3.packages.six.moves.py
PyInstaller/isolated/__init__.py
PyInstaller/isolated/_child.py
PyInstaller/isolated/_parent.py
PyInstaller/utils/hooks/__init__.py
PyInstaller/utils/hooks/gi.py
doc/hooks.rst
news/6052.feature.1.rst
news/6052.feature.rst
tests/unit/hookutils_files/hookutils_package/raises_error_on_import_1/__init__.py
tests/unit/hookutils_files/hookutils_package/raises_error_on_import_2/__init__.py
tests/unit/test_hookutils.py
tests/unit/test_isolation.py

I've long felt that our `PyInstaller.utils.hooks.exec_statement()`, with its stdout pollution issues, its lack of exception handling and the need to manually serialise/deserialise non trivial return values, is hopelessly inadequate. So I've finally buried my nose into the murky depths of `os.pipe()` long enough to come up with a replacement.
So... define a new `PyInstaller.isolated` submodule with functions to supersede and eventually replace `utils.hooks.exec_statement()` and friends.
Example:
```python
from PyInstaller import isolated
@isolated.decorate
def get_matplotlib_backends():
"""Get matplotlib's backends and the current backend."""
import matplotlib
print("This print statement will not affect the output. It could just be used for debugging.")
return …
```

A new flavour of exec_statement().

---

.github/workflows/ci.yml
bootloader/src/pyi_archive.c

Move the declaration of index variable outside of the for-loop statement to avoid requiring C99 mode.
Fixes #6081.

bootloader: restore compatibility with -std=gnu90

---

PyInstaller/hooks/hook-matplotlib.backends.py
doc/hooks-config.rst
news/6024.breaking.rst
news/6024.hooks.rst
tests/functional/test_hooks/test_matplotlib.py

Rework the `matplotlib` backend selection, so that it supports three distinct modes, controlled by hook config (`"matplotlib"` -> `"backends"`).
If the config key is set to `"auto"`, auto-detection is performed. This is also the new default mode. It first scans the code for any uses of `matplotlib.use()` or `mpl.use()` and constructs the list of corresponding backends. If none are found, the default  backend
is queried via `matplotlib.get_backend()`.
If the config key is set to `"all"`, then old behavior that brute-force collects all (importable) backends is enabled.
Otherwise, if the key is any other string, it is treated as a backend name. Similarly, if it is a list, it is treated as list of backend names.
In all three cases, the initial obtained list of backends is further filtered to …

hooks: rework matplotlib.backends hook
